### ISSUE TITLE
OpenAPIV3Parser#getExtensions() not finding extensions on OSGi

### ISSUE THREAD

**Issue by fmoussallam** [swagger-api/swagger-parser#1003]
I am using the swagger-parser-v3 library from within an OSGi bundle.

The issue I am facing is that the ServiceLoader.load(SwaggerParserExtension.class) mechanism uses the current thread's class loader (see https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html#load-java.lang.Class-).

With that default behavior, getExtensions() does not return anything, and I can't parse v2 specifications.

I can workaround this by forcing the current thread classloader to SwaggerParserExtension.getClass().getClassLoader() but that is ugly.

Would it be possible to add a ParseOption to allow selecting the class loader?

Thank you

**Comment by gracekarina** [comment]
Hi, please provide us with a PR and a failing test where we can see what you mean. Thanks

**Comment by fmoussallam** [comment]
This test would fail for a v2 swagger.json spec:

```    @Test
    public void testIssue1003() {
    	ClassLoader ctcl = Thread.currentThread().getContextClassLoader();
    	try {
    		final ClassLoader cl = new URLClassLoader(new URL[] {});
    		Thread.currentThread().setContextClassLoader(cl);
            assertNotNull(new OpenAPIV3Parser().read("src/test/resources/swagger.json"));
    	} finally {
    		Thread.currentThread().setContextClassLoader(ctcl);
    	}
    }

```
Problem is where to place that test. OpenAPIV3ParserTest does not have any loadbale extension on its classpath anyway.

Are there any tests actually loading extensions?

Thanks

**Comment by gracekarina** [comment]
Hi, can you place it at swagger-parser module, and test? what do you mean here: `Would it be possible to add a ParseOption to allow selecting the class loader?`

**Comment by cvgaviao** [comment]
In order to the new version to work with OSGi you need to install an OSGi ServiceLoader Mediator implementation. The one that I know is  [Aries SPI Fly](http://aries.apache.org/modules/spi-fly.html#usage).

**Comment by fmoussallam** [comment]
I propose https://github.com/swagger-api/swagger-parser/pull/1068 for your review.

The unit test is not great but at least it verifies that both classloaders are given a chance to provide extensions. This was separately tested in an OSGi environment.

**Comment by gracekarina** [comment]
closed by #1068.

**Comment by jmini** [comment]
@fmoussallam: I have the feeling there is the exact same issue with `OpenAPIParser`:

https://github.com/swagger-api/swagger-parser/blob/0a4ed0b346c7125ff8bd8b2da2ac78fc5a57c73f/modules/swagger-parser/src/main/java/io/swagger/parser/OpenAPIParser.java#L41-L51

Can you confirm this?

**Comment by fmoussallam** [comment]
Humm, definitely looks like the same issue. I was not aware OpenAPIParser was upward compatible with V3 (which I find a little bit confusing I have to say)

**Comment by jmini** [comment]
@fmoussallam: is this also a problem in an OSGi context? Do you want to push a similar patch for that as well?

**Comment by fmoussallam** [comment]
Sure will do. I would also want to submit another PR for https://github.com/swagger-api/swagger-parser/issues/997 which is trivial. Is that ok?
