### ISSUE TITLE
schema with enum containing null

### ISSUE THREAD

**Issue by rienafairefr** [swagger-api/swagger-parser#1008]
Hi,
I encountered something weird when parsing a spec, and I think there is a bug in swagger-parser. This is related to a `null` value in the `enum` property of a Schema:
```
openapi: 3.0.1
paths:
  /test:
    summary: test
info:
  description: test
  version: 1.0.0
  title: test
components:
  schemas:
    Type:
      properties:
        prop:
          enum: [A, B, C, null]
          type: string
```
The `null` value in enum is apparently perfectly fine and properties is a valid JSONSchema according to [this](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1)
Right now, the parser parses all values passed in the enum array as text [here](https://github.com/swagger-api/swagger-parser/blob/d0aa5a4f93aba5097609b5d7ca586fe3cd5e6918/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L478), and this is wrong. This might also be wrong when an enum has value typed differenly than string (like boolean, numeric values). 
Am I understanding everything correctly ?

**Comment by frantuma** [comment]
Thanks for reporting this, should be fixed by related core PR and core version update in #1009
