### ISSUE TITLE
Parse error when default value for string array property is a string array

### ISSUE THREAD

**Issue by padamstx** [swagger-api/swagger-parser#1015]
I have an OpenAPI 3 apispec with the following schema defined:
```
            "DocFilterSettings": {
                "type": "object",
                "description": "This model describes the attributes used to filter a document.",
                "properties": {
                    "tag_list": {
                        "description": "This is the set of tags to include in the output.",
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "default": [
                            "h1",
                            "h2"
                        ]
                    }
                }
            }
```
So... a property which is an array of strings with a default value which is also an array of strings.
Unfortunately, when I use swagger-parser v2.0.8 to read in this apispec, I get this error returned in the SwaggerParseResult object:
```
attribute components.schemas.DocFilterSettings.default is not of type `string`
```
I initially found this in swagger-parser v2.0.4 but it also occurs with the latest (2.0.8).

It seems like the default value for an array of strings should itself be an array of strings, no?
Also, a secondary issue is that the error message doesn't reference the actual name of the schema property which was found to be in error.

Here's a small code snippet (part of a unit test) which shows the code I'm using to read in the apispec:
```
        ParseOptions options = new ParseOptions();
        options.setResolve(true);
        options.setResolveCombinators(true);
        SwaggerParseResult parseResult = new OpenAPIParser().readLocation(path, null, options);
        if (parseResult.getMessages() != null && !parseResult.getMessages().isEmpty()) {
            parseResult.getMessages().forEach(s -> System.out.println(s));
            fail("Error while loading apispec!");
        }

        OpenAPI apispec = parseResult.getOpenAPI();
        assertNotNull(apispec);
```

**Comment by gracekarina** [comment]
Hi @padamstx  thanks for reporting this. Can you please send a spec that exposes the issue?

**Comment by padamstx** [comment]
Hi @gracekarina, yep... should have done that when I opened the issue.   
Here it is: 
[issue-1015.zip](https://github.com/swagger-api/swagger-parser/files/2866032/issue-1015.zip)

**Comment by gracekarina** [comment]
thanks for the quick response!

**Comment by padamstx** [comment]
@gracekarina, FYI... I recently submitted a swagger-core PR to do some cleanup in the various schema classes (https://github.com/swagger-api/swagger-core/issues/3094) and that has been merged into master.   This issue existed prior to that PR and continues to exist.   I tried some changes to the ArraySchema class to try to fix this issue (mainly subclass Schema<List<Object>> instead of just Schema<Object>) but ended up backing those particular changes out because they didn't resolve the issue and I think there might also be a fix needed in swagger-parser.   So, I thought it would be better to report the issue and hope that someone more experienced in all this code could take a look :)

**Comment by gracekarina** [comment]
@padamstx thanks for the heads up, I'm looking into it (in parser) right now.

**Comment by gracekarina** [comment]
Please let us know is this issue keeps happening. @padamstx

**Comment by padamstx** [comment]
@gracekarina Thanks for fixing this so quickly!   Can't wait to try it out :)
