### ISSUE TITLE
Nested objects flattening loose lot of information ("required" for example)

### ISSUE THREAD

**Issue by MercurieVV** [swagger-api/swagger-parser#1018]
When I use nested objects (without reference), flattening phase loose lot of info from it. For example "required"
```components:
  schemas:
    ReturnInformation:
      type: object
      properties:
        manufacturer_signin_credentials:
          type: object
          properties:
            login:
              type: string
            password:
              type: string
          required:
            - login
            - password
```
geberate ReturnInformationManufacturerSigninCredentials which fields are optional, but should be required from spec.
I found its ahppening during flattening phase. In `InlineModelResolver.modelFromProperty()` method which copy only few properties.

**Comment by gracekarina** [comment]
@MercurieVV Thanks for reporting this. We merged a fix for it. Please let us know if it's still an issue.
