### ISSUE TITLE
swagger-parser not resolving external schema references

### ISSUE THREAD

**Issue by jphorx** [swagger-api/swagger-parser#1025]
I've found that when using swagger-parser on valid OpenAPI specifications that use references for schemas, these references can not be successfully resolved by the parser.  Other types of references seem to work fine.

Affected version: 2.0.9, though I tried earlier ones and also 2.0.10-SNAPSHOT and they seemed to have similar issues.

I've attached a simple maven project I built to demonstrate the issue, along with a stripped down 'petstore' spec example with external schema references.

[swagger-parser-bug.zip](https://github.com/swagger-api/swagger-parser/files/2886136/swagger-parser-bug.zip)

Once built, just run:  java -jar jarname.jar /resources/petstore.yaml

**Comment by gracekarina** [comment]
Hi, @jphorx I've review the `.zip` you sent and the petstore.yaml file is trying to reference a `Pets` schema which is not in the remote location. please review if there is an issue.

**Comment by jphorx** [comment]
Hi @gracekarina I apologize, I must have bundled the wrong supplementary .yaml or made another error.  I'll try to figure out which it is and I'll update here / close the issue as needed.

**Comment by jphorx** [comment]
Apologies but I can no longer reproduce the issue I was observing earlier.  If it recurs I'll open a new issue.
