### ISSUE TITLE
Will FileSchema eventually be used?

### ISSUE THREAD

**Issue by skrysmanski** [swagger-api/swagger-parser#1027]
I'm writing my own swagger-codegen plugin and was wondering whether the type [FileSchema](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/FileSchema.java) will ever be used in OpenAPI.

It's currently not used in [SchemaTypeUtil](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/SchemaTypeUtil.java) (which I'm guessing is the place that creates all the schemas being used).

Or is this *only* for compatibility with v2 (which [seems to be the case](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java) at the moment)?

If it is for compatibility only, is `BinarySchema` the replacement? As in: every time you see `BinarySchema`, assume "file upload"?

In my opinion, this would be a "shame" because `FileSchema` clearly communicates "file upload" while `BinarySchema` basically just communicates "byte array".

**Comment by frantuma** [comment]
You're right by saying that `FileSchema` is there for compatibility, actually it's more a left-over used in a few places like converter, but which would indeed need to be fixed to use `BinarySchema` instead (possibly in scope of this ticket). I understand your point, but OpenAPI 3.0 [drops `file` datatype](https://github.com/OAI/OpenAPI-Specification/blob/3.0.2/versions/3.0.2.md#considerations-for-file-uploads) and FileSchema should be dropped as well; "internally" they both represent a schema of type `string` and format `binary`.

**Comment by skrysmanski** [comment]
@frantuma Thanks for the clarification. That's all I was asking for and now this is kind of documented in this issue. So I'm going to close it.
