### ISSUE TITLE
PR #1019 broke defaults for integer parameters.

### ISSUE THREAD

**Issue by abassouk** [swagger-api/swagger-parser#1029]
Hi al,
The PR #1019 broke default handling of integers and numbers. Specifically the lines at
https://github.com/swagger-api/swagger-parser/blob/2f17c3695f06e1d50a8ef62df6a1e467fc2fc4c7/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L2280-L2286 are breaking both integer and floating-point defaults.  

This should fix the issue:
```
            } else if(schema.getType().equals("integer")) {
                Integer number = getInteger("default", node, false, location, result);
                if (number != null) {
                    schema.setDefault(number);
                }
            } else if(schema.getType().equals("number")) {
                BigDecimal number = getBigDecimal("default", node, false, location, result);
                if (number != null) {
                    schema.setDefault(number);
                }
            }
```

**Comment by gracekarina** [comment]
Hi! thanks I'll review this.

**Comment by gracekarina** [comment]
@abassouk thanks for this. Please let us know if this is still an issue after the merge of #1030
