### ISSUE TITLE
Ability to detect a swagger spec error

### ISSUE THREAD

**Issue by ndhar-1** [swagger-api/swagger-parser#103]
I tried using Swagger Parser expecting that it would report error if the Swagger JSON is not valid according to the spec.
Example: In Petstore, a snippet from the definition of a Pet

```json
  "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "category": {
                    "$ref": "#/definitions/Category"
                },
                "name": {
                    "type": "string",
                    "example": "doggie"
                }
            }
```

Here if I delete the definition of 'Category' it should throw up a Swagger Error saying-
"Reference could not be resolved: #/definitions/Category"

But the Swagger Parser doesn't do that, instead it parses the content smoothly. Thoughts ?

**Comment by fehguy** [comment]
The parser is validating the structural integrity of the swagger-spec but not deeper relationships inside the content.  I agree it'd be good to have it in the project, we'll keep this open as an enhancement.

**Comment by ndhar-1** [comment]
I have even tried this- remove "paths" field completely, this means swagger JSON has no Paths description, which is actually a required field for the spec. This case gave no parsing error with the parser. It goes smoothly.
Thanks!

**Comment by fehguy** [comment]
I'm going to leave this open.  We'll add structural and data validation in the parser.

**Comment by atdiff** [comment]
@fehguy just curious if these changes to do deeper validation have occurred yet.  I'm very interested in these as well.

**Comment by fehguy** [comment]
Hi @atdiff there have been significant updates to parser validation.  I would say it's definitely not covering all aspects though.  There is now a [SwaggerDeserializer](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java) which will do a much better job at looking into matching types, etc which can cause issues with the swagger object.

There is a new entry point to get these messages back from the parser, which is the [readWithInfo](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java#L19) method.

**Comment by atdiff** [comment]
Cool. Thanks!

**Comment by fehguy** [comment]
Please use SwaggerDeserializer and you should get these warnings.
