### ISSUE TITLE
Parser creates inconsistent ArraySchema with type != array

### ISSUE THREAD

**Issue by kerrykimbrough** [swagger-api/swagger-parser#1039]
Found in release=2.0.9...

The parser assumes any Schema object with an "items" property is an ArraySchema. In which case, the "type" property, if defined, ought to be "array".  But subsequently any value for the "type" property is accepted. So it's possible to have an inconsistent ArraySchema with type=number, etc. 

See `OpenAPIDeserializer.getSchema()`

To demonstrate, parse the following spec and inspect the result for GET /pets, parameter=tags

[petstore-array-type.yaml.txt](https://github.com/swagger-api/swagger-parser/files/2954637/petstore-array-type.yaml.txt)

**Comment by gracekarina** [comment]
Thanks for reporting this issue @kerrykimbrough. It's fixed now by the PR #1039. Please let us know if it keeps happening
