### ISSUE TITLE
Parser (v3) accepts schema with type=array but items undefined

### ISSUE THREAD

**Issue by kerrykimbrough** [swagger-api/swagger-parser#1047]
Found in version 2.0.9...

The spec says [here](https://swagger.io/specification/#schemaObject) that "items MUST be present if the type is array".  But here is an instance that contradicts that rule -- see `param1`.

[operations-6.json.txt](https://github.com/swagger-api/swagger-parser/files/2994749/operations-6.json.txt)

**Comment by ymohdriz** [comment]
Hi @kerrykimbrough,

Do you want the parser to throw any warning here?

Thanks,
Mohammed

**Comment by kerrykimbrough** [comment]
There are possibly 2 sides to the problem. 

Currently, `OpenAPIDeserializer` checks first for `items` and assumes `ArraySchema` if found. But then later will accept any `type`. So, if `items` found, then any `type` != `array` should cause a warning. Similarly, after finding `type` != `array` is found, then finding `items` should cause a warning.

**Comment by kerrykimbrough** [comment]
See PR #1101

**Comment by kerrykimbrough** [comment]
Fixed in 2.0.13
