### ISSUE TITLE
Parser (v3) doesn't handle "enum" when "format" demands decoding a string

### ISSUE THREAD

**Issue by kerrykimbrough** [swagger-api/swagger-parser#1049]
See attached example. Consider the schema for `param0`, which has type=string and format=date-time. 

Because of this format, an instance of `DateTimeSchema` is created. Then to handle the "enum" array, `OpenAPIDeserializer.getSchema()` iterates over each `TextNode` in the array, calling `DateTimeSchema.addEnumItemObject()` with the corresponding String value. This invokes `DateTimeSchema.cast()`, which should decode the String as an RFC3339 date-time. 

But it doesn't. Instead, since a String is not a Date, it just substitutes null. Yikes!

The same problem occurs with other string formats that required decoding, specifically "byte" and "date".

[string-8.json.txt](https://github.com/swagger-api/swagger-parser/files/2999720/string-8.json.txt)

**Comment by kerrykimbrough** [comment]
Found in 2.0.9

**Comment by gracekarina** [comment]
Hi @kerrykimbrough can you please send us a PR to speed things up, if you have a possible solution, if you don't just a PR with a test which should fail until fixed. Thanks.

**Comment by kerrykimbrough** [comment]
OK, PR is on the way

**Comment by gracekarina** [comment]
closed by #1062
