### ISSUE TITLE
Parser (v3) doesn't handle "default" correctly for numeric schemas

### ISSUE THREAD

**Issue by kerrykimbrough** [swagger-api/swagger-parser#1050]
Found in 2.0.9.

If the schema type is "integer", then the "default" property is ignored. If the schema type is "number", then the "default" is assumed to be an integer(?), so non-integer values like "1.234" are ignored. See attached example.

The problem is caused by an obvious defect in `OpenAPIDeserializer.getSchema()`.

[number-0.json.txt](https://github.com/swagger-api/swagger-parser/files/2999816/number-0.json.txt)

**Comment by gracekarina** [comment]
Hi @kerrykimbrough can you please send us a PR to speed things up, if you have a possible solution, if you don't just a PR with a test which should fail until fixed. Thanks. 
We did a partial solution for this here: https://github.com/swagger-api/swagger-parser/pull/1030/commits/691a7a8a41cf37c85471709316cc20e96eef7201.

**Comment by kerrykimbrough** [comment]
@gracekarina I verified that the fix for #1029 also fixes this problem. PR #1051 adds a test that fails in 2.0.9, but passes in the current 2.1.0-SNAPSHOT

**Comment by gracekarina** [comment]
Thanks for the test @kerrykimbrough  It's been merged.
