### ISSUE TITLE
I need parse swagger 2.0 and openAPI 3.0 in one project.

### ISSUE THREAD

**Issue by frankxh** [swagger-api/swagger-parser#1064]
I need parse swagger 2.0 and openAPI 3.0 in one project.

Below is the dependency in project:
		<dependency>
		  <groupId>io.swagger.parser.v3</groupId>
		  <artifactId>swagger-parser</artifactId>
		  <version>2.0.10-SNAPSHOT</version>
		</dependency>

 I can properly parse openAPI 3.0 file, but there is one issue when I parsed the swagger 2.0:
Exception in thread "main" java.lang.NoSuchMethodError: io.swagger.models.Response.responseSchema(Lio/swagger/models/Model;)Lio/swagger/models/Response;
	at io.swagger.parser.util.SwaggerDeserializer.response(SwaggerDeserializer.java:1178)
	at io.swagger.parser.util.SwaggerDeserializer.responses(SwaggerDeserializer.java:1144)
	at io.swagger.parser.util.SwaggerDeserializer.operation(SwaggerDeserializer.java:391)

**Comment by gracekarina** [comment]
Hi @frankxh, please try using these 2  maven artifacts:

```
<dependency>
    <groupId>io.swagger</groupId>
        <artifactId>swagger-parser</artifactId>
</dependency>
 <dependency>
     <groupId>io.swagger.parser.v3</groupId>
      <artifactId>swagger-parser</artifactId>
 </dependency>
```

and when implementing something like this:
```
SwaggerParseResult result = new OpenAPIParser().readContents(inputSpec, authorizationValues, options);
OpenAPI openAPI = result.getOpenAPI();
```
Let us know how it goes.

**Comment by I302609** [comment]
Hi ,
Whether this worked.. Also do you have a working example...
Thanks

**Comment by vikikamath** [comment]
Nope  @gracekarina 's solution did not work  for me.

**Comment by Allan-wis** [comment]
Has anyone solved this problem？

**Comment by frantuma** [comment]
`io.swagger.parser.v3:swagger-parser` provides parsing for OpenAPI 3.x, see [readme](https://github.com/swagger-api/swagger-parser/blob/master/README.md#usage) for usage
`io.swagger.parser:swagger-parser` provides parsing for Swagger/OpenAPI 2.x, see [readme](https://github.com/swagger-api/swagger-parser/blob/v1/README.md#usage) for usage

you can use both in your project as they are using different groups and artifacts

```java
SwaggerParseResult result = new OpenAPIParser().readContents(inputSpec, authorizationValues, options);
OpenAPI openAPI = result.getOpenAPI();

Swagger swagger20 = read(location, auths, options);
// or
SwaggerDeserializationResult result = readWithInfo(location, auths, resolve)
Swagger swagger20 = result.getSwagger();
```
