### ISSUE TITLE
`security` (authentication setting) for operations are empty (missing)

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-parser#107]
`security` (authentication setting) for all operations in the Swagger-Codegen project (using swagger-parser 1.0.11-SNAPSHOT) is currently broken due to empty authentication setting for all operations. (ref: https://github.com/swagger-api/swagger-codegen/issues/1371)

Has there been any recent changes related to `security` in the swagger-parser project?

**Comment by fehguy** [comment]
Yes, I have changed the parser to provide better feedback.  I'm guessing that caused the issue.  I'll review right now.

**Comment by fehguy** [comment]
This has been resolved and deployed to sonatype snapshots

**Comment by wing328** [comment]
Pulled the latest and confirmed the issue has been addressed.
