### ISSUE TITLE
Parser ignoring required array

### ISSUE THREAD

**Issue by martinsmith1968** [swagger-api/swagger-parser#1070]
Parser doesn't seem to support required: array on schema items.

E.g.

    AmountAndCurrency:
      additionalProperties: false
      description: >-
        Amount with a currency.
      properties:
        Amount:
          $ref: '#/components/schemas/CurrencyAndAmount_SimpleType'
        Currency:
          description: >-
            Representation of currencies and funds".
          pattern: '^[A-Z]{3,3}$'
          type: string
      required:
        - Amount
        - Currency
      type: object

Amount and Currency properties are not currently detected as being Required - this leads to inaccurate types being interpreted in dependent tools

**Comment by ymohdriz** [comment]
Hi @martinsmith1968 

We tried to reproduce the issue, it's not reproducible and newly added tests are passing.
Please have a look at the TC #1096 and check the added TC verifies the required field. If not, please provide the failing test and open api file

Thanks,
Mohammed

**Comment by gracekarina** [comment]
Hi @martinsmith1968 can does the #1096 PR helps with this issue? or do you have a spec which we can reproduced the issue? thanks
