### ISSUE TITLE
OpenAPIDeserializer- NullPointerException when setting default and schema type is null

### ISSUE THREAD

**Issue by sgadouar** [swagger-api/swagger-parser#1072]
When try to set default value, NullPonterException is thrown when checking schema type is it is not defined in spécifications.

**Comment by sgadouar** [comment]
it'is introduced by the commit c7021bd9988aed7ef2fad79326cf7e078f408a09 on Feb 15.

**Comment by gracekarina** [comment]
Hi can you please share your spec?

**Comment by sgadouar** [comment]
openapi: 3.0.0
info:
  title: Test
  version: 1.0.0

paths:
  /value:
    get:
      operationId: getValues
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentA'
components:
  schemas:
    ComponentA:
      description: Component A
      type: object
      allOf:
        - type: object
          properties:
            attributeWithoutType:
#             type: "is not deined"
              allOf:
              - $ref: '#/components/schemas/ComponentB'
              default: "coucou"
            attributeWithWrongType:
              type: object
              allOf:
                - $ref: '#/components/schemas/ComponentB'
              default: "coucou"
            correctAttribute:
              type: string
              allOf:
                - $ref: '#/components/schemas/ComponentB'
              default: "coucou"
    ComponentB:
      description: Component B
      type: string

**Comment by sgadouar** [comment]
i made a fix but i have not right tu push in a branch
could you give me right please

**Comment by sgadouar** [comment]
this is linked pull request
https://github.com/swagger-api/swagger-parser/pull/1073
Thanks a lot

**Comment by gracekarina** [comment]
Thanks for the Pr, I see the issue and will push a solution.

**Comment by gracekarina** [comment]
Hi @sgadouar the pr you summited was not passing the build. So I push a PR to avoid the NPE.
Please let me know if the issue keeps happening

**Comment by sgadouar** [comment]
Hello @gracekarina 
Sorry for late
It's fine for me, your PR corrected the issue.
Do you know when release will be done ?
i ask this question because we need this fix for open-api-generator project :)
Thanks a lot
