### ISSUE TITLE
OpenAPI 3.x parameters described with content vs schema are not resolved

### ISSUE THREAD

**Issue by darrellmay** [swagger-api/swagger-parser#1078]
From: https://swagger.io/docs/specification/describing-parameters/

In the section  schema vs content

"To describe the parameter contents, you can use either the schema or content keyword..."
"content is used in complex serialization scenarios"

For these complex types you need to "wrap the parameter schema into content/media-type"

For example this is valid in OpenAPI 3.x, but the parser doesn't resolve $ref: 'SomeYaml.yaml#/components/schemas/MyObject'

paths:
&ensp;/api-endpoint-1:
&emsp;get:
&emsp;&emsp;summary: Test Service API Endpoint 1
&emsp;&emsp;operationId: SimpleTestEndpoint1
&emsp;&emsp;parameters:
&emsp;&emsp;- name: widgets
&emsp;&emsp;&emsp;content:
&emsp;&emsp;&emsp;&emsp;application/json:
&emsp;&emsp;&emsp;&emsp;&emsp;schema:
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;$ref: 'SomeYaml.yaml#/components/schemas/MyObject'

Problem with the v3 parser, is that the schema contained in the content: tree is not resolved (via Resolve or FullyResolve option)

In Resolve mode, the Response resolver logic does  this:

in io.swagger.v3.parser.processors.ResponseProcessor.processResponse(ApiResponse response)

            Map<String,MediaType> content = response.getContent();
            for( String mediaName : content.keySet()) {
                MediaType mediaType = content.get(mediaName);
                if(mediaType.getSchema()!= null) {
                    schema = mediaType.getSchema();
                    if (schema != null) {
                        schemaProcessor.processSchema(schema);
                    }
                }
                if(mediaType.getExamples() != null) {
                    for(Example ex: mediaType.getExamples().values()){
                        exampleProcessor.processExample(ex);
                    }
                }
            }

I believe this needs to be added to the resolving of the parameters like the response body is resolved:

io.swagger.v3.parser.processors.ParameterProcessor.processParameters(List<Parameter> parameters)

        for (Parameter parameter : processedPathLevelParameters) {
            Schema schema = parameter.getSchema();
            if(schema != null){
                schemaProcessor.processSchema(schema);
            }
	    <Same logic as the ResponseProcessor>

The main issue is that not that it fails to parse, but it fails to resolve, so the schema container attached to the OpenAPI content only has schema's for parameters that are defined.

Any schema contained in a content: description of a parameter is not resolved.

This causes UNKNOWN PARAMETER issues when generating client or server stubs.

I've tested a patch and will submit a PR for this.

**Comment by gracekarina** [comment]
thanks! closed by #1079
