### ISSUE TITLE
Question: swagger-parser snapshot

### ISSUE THREAD

**Issue by roykachouh** [swagger-api/swagger-parser#109]
Hello,

I'm using the 1.0.11 SNAPSHOT artifact for the swagger parser. The reason I am doing this is because I need to use some functionality in my codegen project that was merged in a PR that I created a couple of weeks back.

https://github.com/roykachouh/swagger-core/commit/d53b2ec359a558d1850330d509355073a9949063

Today, I noticed some of my tests failing around retrieving values from the vendor extensions map.

So for example:

```javascript
java.lang.Boolean booleanExt = (java.lang.Boolean) model.getVendorExtensions().get(X_IMMUTABLE_MODEL);
```

Is throwing a `ClassCastException`

It looks like it now is parsed as a `BooleanNode`

```javascript
BooleanNode booleanNode = (BooleanNode) model.getVendorExtensions().get(X_IMMUTABLE_MODEL);
```

Is this the plan going foward? To treat all the parsed extensions as jackson data types?

**Comment by fehguy** [comment]
It is not, this is a defect.  I'll work this out and post back.  `java.lang.*` should preserve java types, and objects will be of type JsonNode.

If you see an issue with this technique please speak up!

**Comment by roykachouh** [comment]
Awesome! Thanks for the quick reply Tony!

**Comment by fehguy** [comment]
This change has been pushed to the snapshots repo

**Comment by roykachouh** [comment]
Great thanks...Confirmed java.lang are maintained

**Comment by roykachouh** [comment]
This seems to be happening. Just a general follow up, do you have a rough estimate as to when 1.1.11 will be released. Just trying to see when I can get off the snapshot?

**Comment by fehguy** [comment]
There are just a few tickets left and I'll release it but it requires a swagger core release which is more involved. I'd like to say by Friday but probably safer to say end of weekend
