### ISSUE TITLE
Regression: additionalProperties=boolean incorrectly reported as an error

### ISSUE THREAD

**Issue by kerrykimbrough** [swagger-api/swagger-parser#1099]
Found in release 2.0.12.  

The spec ([Version 3.0.2](https://swagger.io/specification/#schemaObject)) makes clear that it is valid for an object schema to specify "additionalProperties" as a boolean, either true or false. But now this setting causes the `OpenAPIDeserializer` to incorrectly report an error message. Possibly a defect caused by PR #1082.
 
See attached example. Parsing this file results in a bogus error message: 

```
attribute paths.'/object'(post).parameters.[param0].schemas.additionalProperties is not of type `object`
```

[object-0.json.txt](https://github.com/swagger-api/swagger-parser/files/3180238/object-0.json.txt)

**Comment by gracekarina** [comment]
Hi @kerrykimbrough, can you please, send us the spec that produces that message so we can reproduce and fix. thanks

**Comment by kerrykimbrough** [comment]
@gracekarina Did you try the `object-0.json.txt` file attached above?

**Comment by gracekarina** [comment]
Oops missed it. I will try and let you know. thanks.

**Comment by kerrykimbrough** [comment]
I think this problem was introduced in commit fecc74792dbe5356e7db8969a48b24e7b3e6a484 with the fix for #1039 at this line:

```
 2035     ObjectNode additionalPropertiesNode = getObject("additionalProperties", node, false, location, result);
```

The `getObject` method is designed to be a kind of assertion that the given property node is an object; otherwise, it reports an error message. S it's incorrect to use it here when a non-object node is valid.

**Comment by kerrykimbrough** [comment]
@gracekarina See PR #1100

**Comment by gracekarina** [comment]
merged! thanks
