### ISSUE TITLE
OpenAPI v2 converter - incorrect server URL when basePath begins with a '/'

### ISSUE THREAD

**Issue by alexweav** [swagger-api/swagger-parser#1113]
I have a v2 document with a `basePath` of `/nitest`, no `host`, and no `schemes`. The v2 converter prepends two forward slashes to it, returning a Server URL of `///nitest`, which is incorrect - i would expect it to be unchanged.

This prepend occurs in [SwaggerConverter.java](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java), line 424.

With a bit of guidance, I can send a PR to fix it. It seems to me that there needs to be an extra case in this method for basePaths which begin with a `/` when no schemes are available.

If this is the correct approach, or if we should take a different route, let me know - I can post a PR either way.

**Comment by alexweav** [comment]
I added a test for this, plus a fix, in separate PRs.

**Comment by gracekarina** [comment]
Hey, sorry I will be checking this pr in the next days.

**Comment by gracekarina** [comment]
Closed by #1115

**Comment by alexweav** [comment]
Thank you!
