### ISSUE TITLE
OpenAPIV3Parser encoding error

### ISSUE THREAD

**Issue by dhmahecha** [swagger-api/swagger-parser#1119]
The OpenAPIV3Parser only supports UTF-8, encoding, In the readWithInfo class method. For this reason the class converts the Latin characters to illegible characters.

example:
parámetros = par�metros.

¿Is it possible to overload the method to pass a custom encoding, in a new version?

**Comment by gracekarina** [comment]
Hi! can you please send us a test, so we can check a solution for this issue? thanks!

**Comment by dhmahecha** [comment]
Hello Grace,

In the following example, I show the encoding  problem in the OpenAPIV3Parser class. 
I attached, maven project test. Download, run maven project and you can to see results in console.

[test.zip](https://github.com/swagger-api/swagger-parser/files/3276858/test.zip)

**Comment by dhmahecha** [comment]
in the line 133 --> data = FileUtils.readFileToString(path.toFile(), "UTF-8");
The  "UTF-8" string could be changed to a class variable and validated with the java.nio.charset.StandardCharsets enum

**Comment by gracekarina** [comment]
hi @dhmahecha thanks for reporting this. please let us know if this fix your issue.
