### ISSUE TITLE
`security` structure is not parsed correctly

### ISSUE THREAD

**Issue by xhh** [swagger-api/swagger-parser#116]
For example, having the following in a spec for either the top level **Swagger Object** or an **operation**:

```json
"security": [
    {
        "api_key1": [],
        "api_key2": []
    },
    {
        "api_key3": []
    }
]
```

then the parsed result is a `List` whose size is 3, i.e. the above structure of security seems to be treated as this:

```json
"security": [
    {
        "api_key1": []
    },
    {
        "api_key2": []
    },
    {
        "api_key3": []
    }
]
```

The related source code seems to be the `securityRequirements` method [here](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java#L1132).

One notable thing is that the type of the `security` field in the [`Swagger` model](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/Swagger.java#L25) is not the same with the one in the [`Operation` model](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/Operation.java#L23).
The latter one is `List<Map<String, List<String>>>` which is consistent with what is described in swagger spec:

> security  [Security Requirement Object]
> A declaration of which security schemes are applied for this operation. The list of values describes alternative security schemes that can be used (that is, there is a logical OR between the security requirements). This definition overrides any declared top-level security. To remove a top-level security declaration, an empty array can be used.

The former one is `List<SecurityRequirement>`, which seems not to be consistent with the swagger spec, where a `Map`-like structure is expected for the element in the `List` and [`SecurityRequirement`](https://github.com/swagger-api/swagger-core/blob/master/modules%2Fswagger-models%2Fsrc%2Fmain%2Fjava%2Fio%2Fswagger%2Fmodels%2FSecurityRequirement.java) seems to stand for the entry in the security requirement map:

```java
public class SecurityRequirement {
    private String name;
    private List<String> scopes;
//    private final Map<String, Object> vendorExtensions = new HashMap<String, Object>();
    private Map<String, List<String>> requirements = new HashMap<String, List<String>>();
```

It does have a `requirements` field, but it seems to always have one entry after deserializing from the spec.

**Comment by fehguy** [comment]
this should be fixed with https://github.com/swagger-api/swagger-parser/commit/d2ee40bff9dcc7eca064371e98cab68f3491e620
