### ISSUE TITLE
OpenAPIV3Parser.readContents() encoding error

### ISSUE THREAD

**Issue by mkuraev** [swagger-api/swagger-parser#1196]
Get "Invalid UTF-8 middle byte ..." error when run java with default character encoding different from UTF-* (for example -Dfile.encoding=windows-1251) and call readContents() for swagger specification containing characters other than Latin (for example Cyrillic).

Problem in line:
mapper.readTree(swaggerAsString.**getBytes()**);
where the default encoding is used

Should be
mapper.readTree(swaggerAsString);
since there is no need to call **getBytes()**

**Comment by mkuraev** [comment]
https://github.com/swagger-api/swagger-parser/pull/1197

**Comment by gracekarina** [comment]
thanks @mkuraev this was closed by #1197 1197 PR
