### ISSUE TITLE
Parsing a valid swagger file gives a validation message

### ISSUE THREAD

**Issue by simpijain** [swagger-api/swagger-parser#1204]
Hi all, 
I am using latest swagger parser jar 'swagger-parser-1.0.46' and trying to parse below swagger.
 https://api.apis.guru/v2/specs/twitter.com/legacy/1.1/swagger.yaml

I get below validation message after parsing - 

"attribute info.contact.x-twitter is unexpected"

As per swagger spec as well as  in swagger editor this is a valid swagger file. 

Please fix the issue with the swagger parser jar.

Thanks,
Simpi

**Comment by simpijain** [comment]
Any update regarding fixing above?

**Comment by gracekarina** [comment]
hi @simpijain thanks for reporting this, please let us know if the issue keeps appearing. 
Closed by #1209
