### ISSUE TITLE
Parser fails to have a error message when true is set for both readOnly,writeOnly property field

### ISSUE THREAD

**Issue by r-sreesaran** [swagger-api/swagger-parser#1211]
Parser fails to have a error message when true is set for both readOnly,writeOnly property field
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schemaObject

**Comment by r-sreesaran** [comment]
I will raise a PR with a failing test and then subsequently have the issue fixed.

**Comment by gracekarina** [comment]
closed by #1214  thanks @r-sreesaran
