### ISSUE TITLE
URISyntaxException stacktrace printed. Always occurs when spec path has URI illegal characters

### ISSUE THREAD

**Issue by gaetPax** [swagger-api/swagger-parser#1236]
During the deserializing process, the "path" of the specfile can be used to resolve the server url.
However, if the specfile is identified by a file path (and it is not a web URL), the instantiation of the URI will always throw URISyntaxException if URI illegal characters are present in the specfile path (i.e. space characters such in  "/my folder/mySpecFile.yml").
The exception thrown is not blocking but the stacktrace is sent to output.
A control on the path should be added to avoid that.
Or at least the exception should be logged instead of printed. 

Here the aforementioned line:
https://github.com/swagger-api/swagger-parser/blob/v2.0.15/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L417

**Comment by r-sreesaran** [comment]
I have added a logging statement, when the exception occurs.

**Comment by gracekarina** [comment]
closed by #1301
