### ISSUE TITLE
complex json 

### ISSUE THREAD

**Issue by F191919** [swagger-api/swagger-parser#124]
I'm trying to use Swagger to describe web-api I'm building. The problem is that I can't understand how to describe complex json object?

For example, how to describe this objects:

{
  name: "Jhon",
  address: [
    {
      type: "home",
      line1: "1st street"
    },
    {
       type: "office",
       line1: "2nd street"
    }
  ]
}

**Comment by webron** [comment]
@F191919 - can you please post the question at the [google group[(https://groups.google.com/forum/#!forum/swagger-swaggersocket)? The question isn't directly related to swagger-parser but rather more of a generic question.

**Comment by F191919** [comment]
thanks
