### ISSUE TITLE
$ref in Path Item Object not supported

### ISSUE THREAD

**Issue by Deamon5550** [swagger-api/swagger-parser#127]
When parsing a swagger json file which contains a $ref within a path item object the parsing appears to fail completely and does not find any operation objects for that path, either within the ref or along side the ref in the path object.

Heres an [example swagger.json file](https://gist.github.com/Deamon5550/4ec40de3238b593f29ea) with an example case. When running this through the parser it fails to find any operation objects, after removing the $ref the GET operation is found as you would expect.

**Comment by fehguy** [comment]
For this scenario, you are useing a JSON pointer for a path reference in the schema references, which is not allowed.  If you want to reference a path you will need to point to an external location.  Referencing them in the local file doesn't make sense.  Please reopen if you have any questions on this.
