### ISSUE TITLE
APIListingRef no longer being used as tag

### ISSUE THREAD

**Issue by jamesecahill** [swagger-api/swagger-parser#13]
Hey @fehguy. Looks like you reverted my fix (https://github.com/swagger-api/swagger-parser/pull/6) for the apiref -> tag thing with a commit at https://github.com/swagger-api/swagger-parser/commit/580df86fc19c68aece7767848f69b6ada1ae8b4b. Was this on purpose?

**Comment by fehguy** [comment]
No it wasn't.  Will look into this shortly.

**Comment by fehguy** [comment]
Fixed here in develop:

https://github.com/swagger-api/swagger-parser/commit/5cb67ff01a177dcb8d6b16fdb5f6a242755f9ac6

I don't have any urgency for a patch release so please let me know how important the change is to you.  It's been deployed to sonatype oss snapshots as 1.0.1-SNAPSHOT.

**Comment by jamesecahill** [comment]
Thanks @fehguy.
