### ISSUE TITLE
Question: ParseOptions resolve versus resolveFully

### ISSUE THREAD

**Issue by jimschubert** [swagger-api/swagger-parser#1303]
This is a pretty simple question, I think.

Related to code starting here: https://github.com/swagger-api/swagger-parser/blob/d88d11c10252f98b052ee7ce690de334ab48adaf/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java#L66

```java
if (options.isResolve()) {
    result.setOpenAPI(resolver.resolve());
}
if (options.isResolveFully()) {
    result.setOpenAPI(resolver.resolve());
    new ResolverFully(options.isResolveCombinators()).resolveFully(result.getOpenAPI());
} else if (options.isFlatten()) {
    InlineModelResolver inlineModelResolver = new InlineModelResolver(options.isFlattenComposedSchemas());
    inlineModelResolver.setSkipMatches(options.isSkipMatches());
    inlineModelResolver.flatten(result.getOpenAPI());
}
```

Is it intentional for resolve=true and resolveFully=true to resolve the document twice, or is this missing an `else` condition plus resolution logic in the `isFlatten` block? I see the same behavior in `readLocation` and `readContents`, so I assume it's intentional but I don't understand the use case.

I'm looking at setting either resolve or resolveFully, but not both. I'm hesitant to do so because it looks like the parser may be implicitly relying on some caching done by the first resolve whenever resolveFully is invoked, but there are no checks for if resolve and resolveFully are both set.

**Comment by mih-kopylov** [comment]
Agree, it confuses.

The whole `OpanPIV3Parser` seems confusing a bit. 
I've prepared a PR with refactoring to make it more clear.

**Comment by jimschubert** [comment]
Огромное спасибо!
