### ISSUE TITLE
The regular expression "^[a-zA-Z0-9\.\-_]+$" should only be applied to fixed-fields under component

### ISSUE THREAD

**Issue by ivenxu** [swagger-api/swagger-parser#1309]
In order to fix previous ticket https://github.com/swagger-api/swagger-parser/issues/931
https://github.com/swagger-api/swagger-parser/pull/933, 

The code evaluates regular expression "^[a-zA-Z0-9\.\-_]+$" on various child nodes no matter they are in Component or Other Types.

The fixed fields mentioned in the spec https://spec.openapis.org/oas/v3.0.2#fixed-fields-5 is under Component. Therefore, this rule should only be applied to fields under Components Object.

Therefore for following swagger yaml, "Entity not found" in response should be valid, while "Customer not found" under components should be invalid.

```
get:
  responses:
    '200':
      description: It works
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
          examples:
            Entity not found:
              summary: Item not existing
  requestBody:
    content:
      application/json:
        schema:
          type: object
        examples:
          Page not found:
            summary: Page not found
    required: true
components:
  schemas:
    customer-not-found:
      type: object
      examples:
        Customer not found:
          summary: Customer not existing
```

**Comment by webron** [comment]
That's true. Example object names are meant as titles and are pretty free form.

**Comment by gracekarina** [comment]
hi @ivenxu  thanks for reporting this issue, we have addressed it, please let us know if this keeps happening.

**Comment by ivenxu** [comment]
@gracekarina Thanks for the fixing! Which official release includes this?
