### ISSUE TITLE
2.0.18 regression wrong error message when validating the server url

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-parser#1329]
This example spec:
```yaml
openapi: 3.0.0
info:
  title: Issue with server
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://{server}.swagger.io:{port}/v2
  description: petstore server
  variables:
    server:
      default: petstore
      enum:
      - petstore
      - qa-petstore
      - dev-petstore
    port:
      default: "80"
      enum:
      - "80"
      - "8080"
- url: https://localhost:8080/{version}
  description: The local server
  variables:
    version:
      default: v2
      enum:
      - v1
      - v2
paths:
  /ping:
    get:
      operationId: pingGet
      responses:
        '201':
          description: OK
```

With version `2.0.18` this is now reporting errors:
```
attribute .servers. invalid url : http://{server}.swagger.io:{port}/v2
attribute .servers. invalid url : https://localhost:8080/{version}
```

With `2.0.17` this was not the case.

---

This can also be reproduced with the example provided in the official spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#server-object-example

**Comment by jmini** [comment]
@jimschubert did some analysis in https://github.com/OpenAPITools/openapi-generator/pull/5413#issuecomment-591766929

The issue is triggered by this line:
https://github.com/swagger-api/swagger-parser/blob/ee9d1a6659fc732cf7798f8778a374fc99a5d34a/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L410-L418

The validate method:

https://github.com/swagger-api/swagger-parser/blob/ee9d1a6659fc732cf7798f8778a374fc99a5d34a/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L458-L466

Is not considering that the server can contains server-variables.

So adding a warning in the else case as introduced by PR https://github.com/swagger-api/swagger-parser/pull/1301 is not a good idea.

If you would like to validate the server URL properly, you need to resolve the server-variables first.

**Comment by r-sreesaran** [comment]
working on this issue.

**Comment by r-sreesaran** [comment]
I would suggest to revert this change as of now. I will raise a new PR for the original issue 1236

**Comment by gracekarina** [comment]
Hi, I'm going to review why has this regression happend and work a fix, if indeed we need to reverse we will. Thanks! 👍

**Comment by gavl-cdl** [comment]
This appears to happen with relative URLs, too.  For example:

``` json
{
  "openapi": "3.0.2",
  "servers": [
    {
      "url": "/api/v1"
    }
  ]
  [snip]
}
```
generates: `attribute .servers. invalid url : /api/v1`

**Comment by badsyntax** [comment]
@gracekarina i'm spotted a similar issue on the openapi generator, not sure if it's related: https://github.com/OpenAPITools/openapi-generator/issues/8033
