### ISSUE TITLE
Swagger Parser OpenAPI class does not allow same path, different verbs

### ISSUE THREAD

**Issue by subash89** [swagger-api/swagger-parser#1332]
I am using io.swagger.parser.v3:swagger-parser:2.0.17 to parse swagger OpenAPI class from swagger json. 
If I have two resource methods with same path, but with different verbs, for example

GET /profile.  - read the profile
POST /profile  - create or update a profile

OpenAPI class only keep one. When looked at the code, the OpenAPI.Paths class uses a Linked Hash Map to store paths, where key will be String type to hold the resource path. This contradicts with swagger v3 open api, where (path + verb) maintains the uniqueness, not just path itself.

Can you please let us know whether we have a workaround for this, or validity of my case ?

**Comment by webron** [comment]
In your file, you should have the path one time, and the two verbs under that single path. Is that the case?

**Comment by subash89** [comment]
I am using javax.ws.rs GET and Path Java annotations in my rest resource methods to indicate it (code first approach, generating swagger v2 from BeanConfig). Then use the io.swagger.v3.parser.converter.SwaggerConverter to convert swagger v2 in to v3.

Code snippet.

// First process to generate swagger  json from code.
 Swagger swaggerV2 = getBeanConfig(config.get("swagger")).getSwagger();
 String swaggerV2String = Files.write(Paths.get(target), Json.pretty(swagger).getBytes());

// Second process take step 1 swaggerv2 json and convert it to v3 openapi.
 SwaggerConverter converter = new SwaggerConverter();
 ParseOptions parseOptions = new ParseOptions();
 parseOptions.setResolve(true);
SwaggerParseResult result = converter.readContents(swaggerV2String, null, parseOptions);
OpenAPI api = result.getOpenAPI();

**Comment by webron** [comment]
Why are you not just generating v3 from your code?

**Comment by subash89** [comment]
I think the issue was, PathItem can hold all the Verbs, so having Paths maintain a HashMap is fine. Thanks for the clue.

**Comment by gracekarina** [comment]
Closing ticket, please reopen if you're still experiencing issues or have more questions.
