### ISSUE TITLE
Not supporting encoded objects

### ISSUE THREAD

**Issue by shireennagdive** [swagger-api/swagger-parser#1341]
https://github.com/swagger-api/swagger-parser/blob/e172a00c6c3e6e6ce8618e3a93a0fa70041ccc41/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/ResolverCache.java#L281

paramName is in encoded format while the map stores references after decoding using UTF-8 format; Even for valid objects - it returns null. 
paramName should be decoded here before doing a map.get(paramName).

**Comment by gracekarina** [comment]
Hi @shireennagdive please send us a spec to reproduce, or a PR in case you have found fix. Thanks!
