### ISSUE TITLE
How to make relative refs work?

### ISSUE THREAD

**Issue by samskiter** [swagger-api/swagger-parser#135]
If I have the following folder structure:

```
./schemas
    - contents.schema.json
    - /room
        - cupboard.schema.json
        - shelf.schema.json
```
Where contents has a ref to `./room/cupboard.schema.json`
How do I add a ref inside cupboard to shelf?

`./shelf.schema.json` does work if I have an endpoint that uses cupboard directly. But doesn't if I have another endpoint that uses contents.schema.json?

**Comment by samskiter** [comment]
I dug through the code a bit to try and work out what's going on. The `ResolverCache` is initialised with a parent directory that it always uses. I've got to a point where I have the directory it should be used passed in through `loadRef` and resolved all the compile errors associated (a change there propagates quite a way!). It should also fix a related issue which is that relative URL refs don't seem to be supported.
No tests currently pass though and I think a much better way to do this would be to change the Model and Swagger classed to have a `location` property that allows any refs contained within to be resolved better. If you'd like me to share where I'm at with this, I can submit a PR for your amusement.

**Comment by fehguy** [comment]
this has been added as of 1.0.18
