### ISSUE TITLE
ResolverFully doesn't resolve header schema $ref

### ISSUE THREAD

**Issue by kerrykimbrough** [swagger-api/swagger-parser#1352]
See attached  spec. 

The response for status=200 specifies a header named "x-my-secret-header". The schema for this header is defined by a $ref to local schema component. But `ResolverFully` does not resolve this reference.

[responses-2.json.txt](https://github.com/swagger-api/swagger-parser/files/4423293/responses-2.json.txt)

**Comment by gracekarina** [comment]
thanks @kerrykimbrough!!

**Comment by gracekarina** [comment]
Fixed by #1353
