### ISSUE TITLE
Question re the name validation regex: ^[a-zA-Z0-9\\.\\-_]+$

### ISSUE THREAD

**Issue by anentropic** [swagger-api/swagger-parser#1354]
Recently I converted some api specs in .apib format to Open API 3 yaml format using Apimatic website

Subsequently I used https://github.com/OpenAPITools/openapi-generator to build clients libs from that OpenAPI spec

I received validation errors from OpenAPI Generator which appear to originate from `swagger-parser`, such as:
```
-attribute components.schemas.Schema name Initiate:Requestaverificationcoderequest doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$ 
```
https://github.com/swagger-api/swagger-parser/blob/24b6120430c1a9176fdfcaf843e12f195c60cd71/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L2009

I could see that in some places these names should be urlencoded, and Apimatic had done so. But this seemed like a different validation - notably it does not include the `%` necessary for urlencoded values, so I think it is for a different purpose.

I could not find in the Open API Specification anything that mandated Schema names should follow that regex (and I see it's applied to various other entities from the spec too).

I am guessing that this is a restriction is because of the need to have an identifier that is valid Java, rather than something in the Open API spec itself?

That's all my question is: to understand if I missed something in the spec, or if this is an extra-spec validation specific to this project's purpose of outputting POJOs. Thanks!

**Comment by hkosova** [comment]
>  could not find in the Open API Specification anything that mandated Schema names should follow that regex (and I see it's applied to various other entities from the spec too).

Refer to the [Components Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#components-object) section:

> All the fixed fields declared above are objects that MUST use keys that match the regular expression: `^[a-zA-Z0-9\.\-_]+$`.

**Comment by anentropic** [comment]
thanks very much, it's clear now!
