### ISSUE TITLE
Does the swagger parser 1.0.36 support for Java 11? If not, any timeline or recommendation?

### ISSUE THREAD

**Issue by xinmin-zhou** [swagger-api/swagger-parser#1357]
Hi Expert,
I would appreciate if you could share your knowledge related with me? Thanks.

Regards,
Xinmin

**Comment by gracekarina** [comment]
Hi, @xinmin-zhou, swagger parser 1.x (v1 branch) doesn't currently support building in Java 11, it's in our path but with no ETA; it is however supported in client Java 11 projects.

**Comment by gracekarina** [comment]
Closing ticket, please reopen if you're still experiencing issues or have more questions.
