### ISSUE TITLE
Valid yaml open api model generate incomplete Python Flask server stubs

### ISSUE THREAD

**Issue by CosminSterie** [swagger-api/swagger-parser#1361]
Hi all,
Having a valid schema i generated the flask server stubs. But when trying to start the flask server error occurs because of an import python error. It seems that instead of importing the AllOfConfigPortsItems from all_of_config_ports_items.py file it imports Object file from no existing object.py. 

Can you please help with this. Is because I use array of Allof syntax in my yaml file?

Bellow are the error and the openapi generated yaml.
`
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util

class Config(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ports: List[AllOfConfigPortsItems]=None):  # noqa: E501
`

GENERATED YAML
`
openapi: 3.0.3
info:
  title: Athena product APIs
  version: 1.0.0
servers:
  - url: /
paths:
  /config:
    description: 'Configuration API      '
    get:
      description: Returns the entire current configuration resource
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: Test device configuration
                properties:
                  ports:
                    type: array
                    items:
                      allOf:
                        - type: object
                          required:
                            - name
                          properties:
                            name:
                              type: string
                              pattern: '^[\sa-zA-Z0-9-_()><\[\]]+$'
                              description: Unique name of an object
                          discriminator:
                            propertyName: name
                        - type: object
                          description: 'An abstract test port. Primarily used to associate a name with a physical or virtual test endpoint. Different types of endpoints can be an appliance, chassis, local interface, or container.'
                          properties:
                            location:
                              type: string
                              format: '../products#/components/schemas/port/location'
                              pattern: '^([A-Za-z0-9\:._-]+)\/\d+\/\d+|\d+|\/\d+\/\d+$'
                              description: |-
                                The location
                              example: 10.36.66.1/1/1
components:
  schemas:
    Config:
      type: object
      description: Test device configuration
      properties:
        ports:
          type: array
          items:
            allOf:
              - type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                    pattern: '^[\sa-zA-Z0-9-_()><\[\]]+$'
                    description: Unique name of an object
                discriminator:
                  propertyName: name
              - type: object
                description: 'An abstract test port. Primarily used to associate a name with a physical or virtual test endpoint. Different types of endpoints can be an appliance, chassis, local interface, or container.'
                properties:
                  location:
                    type: string
                    format: '../products#/components/schemas/port/location'
                    pattern: '^([A-Za-z0-9\:._-]+)\/\d+\/\d+|\d+|\/\d+\/\d+$'
                    description: |-
                      The location
                    example: 10.36.66.1/1/1
`

**Comment by gracekarina** [comment]
Hi can you please, share the spec you use to generate the project, not sure if it is the one you posted above, if so, please send it with a format. thanks
