### ISSUE TITLE
Swagger-parser compatibility with older jackson libraries

### ISSUE THREAD

**Issue by shireennagdive** [swagger-api/swagger-parser#1365]
Will the latest version of swagger-parser be compatible with an older version of jackson - to be specific with version 2.9.8 ? Currently, it requires jackson libraries with version 2.10.2. If you do not know the answer to this, can you direct me how to find this?! Thanks

**Comment by gracekarina** [comment]
Hi, it should be compatible, there shouldn't be any Jackson 2.9.9+ features
used within the project.

**Comment by shireennagdive** [comment]
Hi Grace, Thank you for your response. To be double sure, I was planning of checking all the PR's after release version 2.0.12 (thats the version I am currently using) to see if there are any new jackson functions used (after 2.9.8+). Was also trying to check jackson libraries to see what new features they released after 2.9.8 - was unable to see specific changes/PR's like swagger displays ; will try harder

**Comment by shireennagdive** [comment]
Looks like the swagger-parser is not backward compatible with jackson library version 2.9.8 since it uses some classes introduced in version 2.10; 
<img width="1440" alt="Screen Shot 2020-05-07 at 3 13 27 PM" src="https://user-images.githubusercontent.com/12156581/81349710-6814fa00-9075-11ea-8742-f4ecdaecf678.png">
