### ISSUE TITLE
OpenAPIDeserializer produces NPE when a path references an undeclared path parameter

### ISSUE THREAD

**Issue by brhaible** [swagger-api/swagger-parser#1402]
The OpenAPIDeserializer runs into a NPE and, as a consequence, produces a diagnostic message with content "null", when a path references a path parameter that is not declared in the respective operation.

How to reproduce:

1. Store this file as input.json

[input.json.gz](https://github.com/swagger-api/swagger-parser/files/4934685/input.json.gz)
.

2. Store this file as ParseOpenAPI3File.java.

[ParseOpenAPI3File.java.gz](https://github.com/swagger-api/swagger-parser/files/4934689/ParseOpenAPI3File.java.gz)

Compile it with a classpath that contains
slf4j-api-1.5.8.jar
slf4j-jdk14-1.5.8.jar
jackson-core-2.11.0.jar
jackson-dataformat-yaml-2.11.0.jar
jackson-databind-2.11.0.jar
jackson-annotations-2.11.0.jar
jackson-datatype-jsr310-2.11.0.jar
commons-io-1.4.jar
commons-lang3-3.1.jar
swagger-models-2.1.3.jar
swagger-core-2.1.3.jar
swagger-parser-v3-2.0.20.jar
swagger-parser-core-2.0.20.jar
snakeyaml.jar

3. Run it with one argument, namely the absolute file name from step 1.

Expected output:
```
Messages from OpenAPIV3Parser:
attribute paths.'/restTest/arraytypes/complexArrayEcho/{value}'. Declared path parameter value needs to be defined as a path parameter in path or operation level
attribute paths.'/restTest/arraytypes/complexArrayEcho/{value}'. Declared path parameter value needs to be defined as a path parameter in path or operation level
```

Actual output:
```
Messages from OpenAPIV3Parser:
null
```

**Comment by brhaible** [comment]
The following patch fixes it:
[1402-fix.diff.gz](https://github.com/swagger-api/swagger-parser/files/4934763/1402-fix.diff.gz)

**Comment by brhaible** [comment]
The following patch fixes it:
[1402-fix.diff.gz](https://github.com/swagger-api/swagger-parser/files/4934772/1402-fix.diff.gz)

**Comment by gracekarina** [comment]
thanks @brhaible
