### ISSUE TITLE
Exception while reading from Swagger URL

### ISSUE THREAD

**Issue by disha-hegde** [swagger-api/swagger-parser#1404]
I'm trying to parse an OPEN API URL and getting an error in the following line

`OpenAPI openAPI = new OpenAPIV3Parser().read("https://petstore3.swagger.io/api/v3/openapi.json");
`

the exception is

`org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactoryBuilder
`

Dependency added is

`<dependency>
<groupId>io.swagger.parser.v3</groupId>
<artifactId>swagger-parser-v3</artifactId>
<version>2.0.19</version>
`

**Comment by gracekarina** [comment]
Hi, I haven't been able to reproduce this issue, please send us a PR with a test showing the issue, so we can work on it, thanks!
