### ISSUE TITLE
Swagger is not parsing definitions with properties along with allOf

### ISSUE THREAD

**Issue by anshumandas** [swagger-api/swagger-parser#141]
```  
User:
    allOf:
    - $ref: '#/definitions/Resource'
    type: object
    required:
      - userId
    properties:
      userId:
        type: string
```
This does not work correctly when parsed. allOf contains two objects instead of one, and the other object does not contain properties, neither does the main ComposedModel.

It works fine in the swagger editor however.

Note that the workaround of adding the properties as another element of allOf is not good as this means that we are inheriting from an anonymous class. It causes issues if any property there is composition of the same class. Eg. User having a property called friends that is list of Users, since then it is inheriting from a class that composes it. 
```
  User:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      required:
      - userId
      properties:
        userId:
          type: string
```

What is needed is an ability to inherit from a super class and also have the ability to add new fields that can compose of the same class.

**Comment by anshumandas** [comment]
I have made some code changes that will support the above in io.swagger.parser.util.SwaggerDeserializer in my own machine (sorry cannot create a pull request)

'''

    public Model definition(ObjectNode node, String location, ParseResult result) {
        if(node == null) {
            result.missing(location, "empty schema");
        }
        
        Model model = null;
        
        //A model can either be a reference or be specified here
        if(node.get("$ref") != null) {
        	model = refModel(node, location, result);
        } else {
	
	        String type = getString("type", node, false, location, result);
	        if("array".equals(type)) { //array cannot have allOf
	            ArrayModel am = new ArrayModel();
	            ObjectNode propertyNode = getObject("properties", node, false, location, result);
	            Map<String, Property> properties = properties(propertyNode, location, result);
	            am.setProperties(properties);
	
	
	            ObjectNode itemsNode = getObject("items", node, false, location, result);
	            Property items = property(itemsNode, location, result);
	            if(items != null) {
	                am.items(items);
	            }
	
	            model = am;
	        }
	        else {
	        	String value = null;
	            ModelImpl impl = new ModelImpl();
	            impl.setType(value);
	
	            JsonNode ap = node.get("additionalProperties");
	            if(ap != null && ap.getNodeType().equals(JsonNodeType.OBJECT)) {
	                impl.setAdditionalProperties(Json.mapper().convertValue(ap, Property.class));
	            }
	
	            value = getString("default", node, false, location, result);
	            impl.setDefaultValue(value);
	
	            value = getString("format", node, false, location, result);
	            impl.setFormat(value);
	
	            value = getString("discriminator", node, false, location, result);
	            impl.setDiscriminator(value);
	
	            JsonNode xml = node.get("xml");
	            if(xml != null) {
	                impl.setXml(Json.mapper().convertValue(xml, Xml.class));
	            }
	
	            ObjectNode externalDocs = getObject("externalDocs", node, false, location, result);
	            ExternalDocs docs = externalDocs(externalDocs, location, result);
	            impl.setExternalDocs(docs);
	
	            ObjectNode properties = getObject("properties", node, true, location, result);
	            if(properties != null) {
	                Set<String> propertyNames = getKeys(properties);
	                for(String propertyName : propertyNames) {
	                    JsonNode propertyNode = properties.get(propertyName);
	                    if(propertyNode.getNodeType().equals(JsonNodeType.OBJECT)) {
	                        ObjectNode on = (ObjectNode) propertyNode;
	                        Property property = property(on, location, result);
	                        impl.property(propertyName, property);
	                    }
	                    else {
	                        result.invalidType(location, "properties", "object", propertyNode);
	                    }
	                }
	            }
	
	            // need to set properties first
	            ArrayNode required = getArray("required", node, false, location, result);
	            if(required != null) {
	                List<String> requiredProperties = new ArrayList<String>();
	                for (JsonNode n : required) {
	                    if(n.getNodeType().equals(JsonNodeType.STRING)) {
	                        requiredProperties.add(((TextNode) n).textValue());
	                    }
	                    else {
	                        result.invalidType(location, "required", "string", n);
	                    }
	                }
	                if(requiredProperties.size() > 0) {
	                    impl.setRequired(requiredProperties);
	                }
	            }	
		        // extra keys
		        Set<String> keys = getKeys(node);
		        for(String key : keys) {
		            if(key.startsWith("x-")) {
		            	impl.setVendorExtension(key, extension(node.get(key)));
		            }
		            else if(!SCHEMA_KEYS.contains(key)) {
		                result.extra(location, key, node.get(key));
		            }
		        }

	        	if(node.get("allOf") != null) {
	        		ComposedModel cmodel = (ComposedModel) allOfModel(node, location, result);
	        		cmodel.setChild(impl);
		        	model = cmodel;
		        } else {		        
		        	model = impl;  
		        }
		        
		        if("{ }".equals(Json.pretty(model)))
		            return null;   
	        }
        }

        if(model != null) {
		        
	        JsonNode exampleNode = node.get("example");
	        if(exampleNode != null) {
	            // we support text or object nodes
	            if(exampleNode.getNodeType().equals(JsonNodeType.OBJECT)) {
	                ObjectNode on = getObject("example", node, false, location, result);
	                if(on != null) {
	                    model.setExample(on);
	                }
	            }
	            else {
	                model.setExample(exampleNode.asText());
	            }
	        }

        	String value = null;
            value = getString("description", node, false, location, result);
            model.setDescription(value);

            value = getString("title", node, false, location, result);
            model.setTitle(value);
        }

        return model;
    }
'''
and
'''

    public Model allOfModel(ObjectNode node, String location, ParseResult result) {
        JsonNode sub = node.get("$ref"); 
        JsonNode allOf = node.get("allOf");

        if (sub != null) { //should never happen
            if(sub.getNodeType().equals(JsonNodeType.OBJECT)) {
                return refModel((ObjectNode)sub, location, result);
            }
            else {
                result.invalidType(location, "$ref", "object", sub);
                return null;
            }
        } else if (allOf != null) { //should always happen
            ComposedModel model = null;
            // we only support one parent, no multiple inheritance or composition
            if(allOf.getNodeType().equals(JsonNodeType.ARRAY)) {
                model = new ComposedModel();
                int pos = 0;
                for(JsonNode part : allOf) {
                    if(part.getNodeType().equals(JsonNodeType.OBJECT)) {
                        Model segment = definition((ObjectNode) part, location, result);
                        if(segment != null) {
                            model.getAllOf().add(segment);
                        }
                    }
                    else {
                        result.invalidType(location, "allOf[" + pos + "]", "object", part);
                    }
                    pos++;
                }

                List<Model> allComponents = model.getAllOf();
                if (allComponents.size() >= 1) {
                    model.setParent(allComponents.get(0));
                    if (allComponents.size() >= 2) {
                        List<RefModel> interfaces = new ArrayList<RefModel>();
                        int size = allComponents.size();
                        for (Model m : allComponents.subList(1, size)) {
                            if (m instanceof RefModel) {
                                RefModel ref = (RefModel) m;
                                interfaces.add(ref);
                            } else {
                                model.setChild(m);                            	
                            }
                        }
                        model.setInterfaces(interfaces);
                    } 
                }
                return model;
            }
            else {
                result.invalidType(location, "allOf", "array", allOf);
            }

            return model;
        }
        return null;
    }
'''

**Comment by wing328** [comment]
@anshumandas the latest version (1.0.16) was released several days ago.

Do you mind giving it a try to see if the issue still occurs?

**Comment by Magdagan** [comment]
I confirm that it is still an issue as of today (with version 1.0.18-SNAPSHOT). That is properties alongside “allOf” are ignored as explained by @anshumandas. I am using [swagger-codegen](https://github.com/swagger-api/swagger-codegen) to generate client libraries from the following specifications I do not own: [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs). I know that Microsoft has its own generator (i.e. [autorest](https://github.com/Azure/autorest)) not subject to this issue, but for some reasons I have to use swagger-codegen implementation of the specification (e.g. dependencies, customization, community …).

I made a similar fix in io.swagger.parser.util.SwaggerDeserializer to be able to generate my client:

 ```java
public Model definition(ObjectNode node, String location, ParseResult result) {
        if(node == null) {
            result.missing(location, "empty schema");
        }
        Model model = null;
        String value = null;

        if(node.get("$ref") != null) {
            return refModel(node, location, result);
        } else {
           ...
               if (node.get("allOf") != null) {
                    ComposedModel cModel = (ComposedModel) allOfModel(node, location, result);
                    if (!"{ }".equals(Json.pretty(impl))) {
                        cModel.setChild(impl);
                    }
                    model = cModel;
                } else {
                    if ("{ }".equals(Json.pretty(impl)))
                        return null;
                    model = impl;
                }
            }
        }
```

Based on the specification, shouldn’t this behavior be taken into account?

**Comment by webron** [comment]
That's just not how `allOf` works. `allOf` requires an array of schema to validate against.

**Comment by anshumandas** [comment]
Let me explain the issue again.
The question is not regarding the working of allOf to take fields from the inherited objects, but towards the mandatory requirement of an anonymous class within allOf for the new fields.
The Swagger Editor does not allow nesting for case such as:
 User:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        friend:
          $ref: '#/definitions/User'

This is because we are trying to inherit from an anonymous class while creating User but have a property that references User. It leads to a circular relationship.

However, this structure is a valid use case which should be handled as:
User:
    allOf:
    - $ref: '#/definitions/Resource'
    type: object
    properties:
      friend:
        $ref: '#/definitions/User'

The above is allowed in Swagger Editor but not by the parser code. Thus I had fixed the same on my branch at my workplace.

**Comment by fehguy** [comment]
As @webron said, the above is not valid for JSON schema, regardless of what swagger-editor says.
