### ISSUE TITLE
1.0.52-SNAPSHOT does not exist as a release, can a release be made for it?

### ISSUE THREAD

**Issue by spacether** [swagger-api/swagger-parser#1413]
In that snapshot, additionalProperties are set to Null for both additionalProperties absent and additionalProperties=False
I am interested in creating a 1.0.53 release which will correct the handling of additionalProperties.
Can a release be made for the 1.0.52-SNAPSHOT so I can build off of it?
@gracekarina

**Comment by spacether** [comment]
Never mind, I see that this branch is the source for it: https://github.com/swagger-api/swagger-parser/tree/v1

**Comment by hkosova** [comment]
FYI, snapshot builds are available on Sonatype:
https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-parser/

To use snapshots in your pom.xml:
```xml
<repositories>
  ...
  <repository>
    <id>sonatype-snapshots</id>
    <name>Sonatype Snapshots</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by spacether** [comment]
Thank you for explaining that. My reason for asking here was to write new code in github based upon a github release
