### ISSUE TITLE
Code generation fails if accessing spec file the remote server redirects with HTTP 302

### ISSUE THREAD

**Issue by marcolucio** [swagger-api/swagger-parser#1417]
If you try to generate from command line performing:

```
./openapi-generator-cli generate -g java -i http://petstore.swagger.io/v2/swagger.json 
```

Code generation fails becouse source server is responding with HTTP 302 redirect which is not handled correctly.

Apparently the problem is in [RemoteUrl.java](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RemoteUrl.java) file line 153 (it handles only HTTP 301 redirects). I suggest to add also 302, 303 and 307 codes handling.

**Comment by gracekarina** [comment]
Hi this issue was fixed in https://github.com/swagger-api/swagger-parser/pull/1430 please let us now if this is still an issue.
