### ISSUE TITLE
Wrong reported location of error - missing `responses` for swagger

### ISSUE THREAD

**Issue by klokane** [swagger-api/swagger-parser#1432]
Hi, for following swagger

```
swagger: "2.0"
info:
  description:
   some description
paths:
  /tickets:
    get:
      responses:
        200:
          title: abc
```

Is reported location: `attribute paths.'/tickets'(get).200.title is unexpected` but I mean, it should be `attribute paths.'/tickets'(get).responses.200.title is unexpected`

It seems, there is missing modification of `location` in `SwaggerDeserializer::response()`
eg. here https://github.com/swagger-api/swagger-parser/blob/v1.0.51/modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java#L1209

**Comment by gracekarina** [comment]
Hi, thanks for pointing that out, please send us a PR with a proposal fix.

**Comment by gracekarina** [comment]
@r-sreesaran thanks for the PR https://github.com/swagger-api/swagger-parser/pull/1438, it's now merged. I'm closing the issue, @klokane please let us know if this keeps happening.

**Comment by klokane** [comment]
Thank you, it works as expected!
