### ISSUE TITLE
Swagger generation

### ISSUE THREAD

**Issue by ArulPrakas** [swagger-api/swagger-parser#144]
We have API metadata available in some format. Is there any tools available to auto generate swagger docuementation for it? I know that there are plugins to generate swagger from source code using annotations but is there a API to generate Swagger spec?

**Comment by fehguy** [comment]
Sure, you have two choices.

1) Write an extension for the swagger-parser.  You can follow the `swagger-compat-spec-parser` project, which uses java SPI to make it pluggable.  You simply need to implement the `SwaggerParserExtension` class.

2) Generate a swagger-pojo manually using the [swagger-models](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-models) artifact.  Once generated, the `SwaggerSerializer` class can write the POJO to a JSON or YAML string with [Json](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/util/Json.java) or [Yaml](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/util/Yaml.java) helpers.
