### ISSUE TITLE
Error when setting multipleOf to a value between 0 and 1

### ISSUE THREAD

**Issue by feliperuiz** [swagger-api/swagger-parser#1457]
I was getting a NullPointerException when validating a spec using `swagger-parser@2.0.22`, turns out it would happen because I had a `multipleOf` property set to `0.5`, which triggered an `else` branch that works on a `null` variable. The only limitation for multiples, as mentioned in [Swagger's own docs](https://swagger.io/docs/specification/data-models/data-types/), is that:
> The value of `multipleOf` must be a positive number

A simple schema such as the one below is enough to reproduce the error:
```yaml
openapi: 3.0.0
info:
  version: 0.0.0
  title: test
components:
  schemas:
    Test:
      type: object
      properties:
        decimal_value:
          type: number
          multipleOf: 0.3
```

I already have a patch in place and will submit a PR, if you folks don't mind it.

**Comment by gracekarina** [comment]
fixed by #1458
