### ISSUE TITLE
Using YAML anchors causes com.fasterxml.jackson.databind.node exception

### ISSUE THREAD

**Issue by chandravadans** [swagger-api/swagger-parser#146]
YAML anchors don't seem to be supported in swagger parser. An exception relating to conversion of `com.fasterxml.jackson.databind.node.TextNode`  to `com.fasterxml.jackson.databind.node.ArrayNode` occurs.

Example YAML :

``` yaml
swagger: '2.0'

info:
  version: "0.0.1"
  title: API

x-types:
  OperationType: &OperationType
    - registration

# Describe your paths here
paths:
  /checker:
    get:
      parameters:
        - name: operations
          in: query
          type: array
          items:
            type: string
            enum: *OperationType
          default: [registration]
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/OperationType'

definitions:      
  OperationType:
    type: string
    enum: *OperationType
```

example taken from [here](https://github.com/swagger-api/swagger-editor/issues/609) and the same issue filed [here](https://github.com/swagger-api/swagger-codegen/issues/1662)

**Comment by nazr** [comment]
I'm having the same issue. That makes swagger-codegen pretty useless for any decent size swagger definition

**Comment by ge1st** [comment]
I assume I have the same issue. The code generator CLI gives me the very helpful error:

```
[main] INFO io.swagger.codegen.DefaultCodegen - generated operationId puppiesGet       for Path: get /puppies
Exception in thread "main" java.lang.NullPointerException
        at io.swagger.codegen.DefaultGenerator.generateParameterId(DefaultGenerator.java:613)
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:531)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:496)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:226)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

Using one of the debug switches to the gen cli showed that many objects within the spec had null values in the object parsed in. Those with nulls were using anchors. Piping it in with a ruby yaml parser and back out as json let me work-around this.

I agree with @nazr this makes it difficult to handle large APIs.

**Comment by fehguy** [comment]
Yes, it does look like anchors are not supported in the jackson parser that we use.  It may be supported in a later version but it is not expected to work right now.

Can you use JSON pointers instead?  That is natively supported by swagger, and it is not lossy like YAML anchors.

**Comment by jeff9finger** [comment]
Looks like JSON Pointers don't work as expected. The parameter is interpreted as a string, and not the an enum.

**Comment by fehguy** [comment]
@jeff9finger are you using master?

**Comment by jeff9finger** [comment]
Using swagger-codegen 2.1.6-SNAPSHOT with uses the latest SNAPSHOT build for swagger-parser. That was the middle of last week.  Should this work?

**Comment by garydgregory** [comment]
How about updating Swagger to the current version of Jackson?

**Comment by jeff9finger** [comment]
I updated the version of jackson in swagger-core, rebuilt swagger-core. swagger-parser, and swagger-codegen. This  prevents the issue in swagger-codegen.

So, once the swagger-core has been updated, the pom in this package need to use the updated swagger-core pom.

**Comment by garydgregory** [comment]
Hi,

When can we expect new releases of the components?

Gary

**Comment by jeff9finger** [comment]
https://github.com/swagger-api/swagger-core/issues/1601 seems to be the issue that will upgrade the jackson version in swagger-core. Once that issue is complete, swagger-parser should be upgraded to use the newer swagger-core

**Comment by fehguy** [comment]
Swagger parser is depending on swagger-core 1.5.8, which we are working on right now.

I am concerned about just upgrading jackson to the latest--there will be impact on integrations.  Is there forward API compatibility from the current 2.4.x to 2.7.x?  Can one just exclude our jackson versions and add the latest, safely?

**Comment by webron** [comment]
We can update the Jackson version in the parser regardless of swagger-core, no? I don't know if it makes sense to bump the minimum required Jackson version for swagger-core (it affects a wider range of users than the parser).

**Comment by jeff9finger** [comment]
This would mean specifically excluding all the jackson packages from the swagger-core dependency and adding the newer jackson dependencies in swagger-parser. Currently, swagger-parser uses the jackson dependencies on swagger-core

**Comment by webron** [comment]
Yes, it can introduce a dependency hell for sure, but we're having enough problems telling swagger-core users the minimum requirement is 2.4.5. Not sure I want to deal with the issues that would arise from forcing a higher version.

**Comment by gracekarina** [comment]
Please let us know if the issue keeps presenting.
