### ISSUE TITLE
Duplicate operationIds should not be allowed

### ISSUE THREAD

**Issue by LarryKlugerDS** [swagger-api/swagger-parser#148]
Hi,
The [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operation-object) says that operationId values must be unique per API. But duplicate operationIds are currently accepted by the parser and validator.

This short example passes validation, but shouldn't:
http://online.swagger.io/validator/debug?url=http://assetsdp.arx.com/larry/swagger/swagger_dup_ids.json

``` json
{"swagger": "2.0",
"x-foo" : "woof",
"info": { "version": "0.0.0", "title": "Simple API" },
"paths": { "/": { 
    "get": {"operationId": "duplicateID", "responses": { "200": { "description": "OK" }}},
    "put": {"operationId": "duplicateID", "responses": { "200": { "description": "OK" }}}
}}}
```

Thank you for your time and for great software!

**Comment by fehguy** [comment]
Going to leave this out of the parser.  Some tools may choose to clean this up automatically or fail

**Comment by LarryKlugerDS** [comment]
The problem is that the "Swagger verification tool" uses the parser. And that currently the verification tool is telling fibs since it says that the Swagger file is valid when, in fact, it is not (because of non-unique operationIds.)
