### ISSUE TITLE
example vs. examples: Mutual exclusion not enforced

### ISSUE THREAD

**Issue by kerrykimbrough** [swagger-api/swagger-parser#1483]
Found in release=2.0.23

The [OpenAPI specification](http://spec.openapis.org/oas/v3.0.2#fixed-fields-11) says:

> The examples field is mutually exclusive of the example field. 

This means that it is an error to define both of these properties anywhere they are allowed. But this requirement is not enforced. For example, the following API def parses without error.

[with-examples.json.txt](https://github.com/swagger-api/swagger-parser/files/5503161/with-examples.json.txt)

**Comment by gracekarina** [comment]
closed by #1493
