### ISSUE TITLE
Duplicated references in parsed result

### ISSUE THREAD

**Issue by jennifer-7** [swagger-api/swagger-parser#1487]
I'm facing the same problem described in these issues:
https://github.com/swagger-api/swagger-parser/issues/1422
https://github.com/swagger-api/swagger-parser/issues/1475

I'm using this swagger-parser version https://github.com/swagger-api/swagger-parser/tree/v1.0.52

Do you have plans to solve this problem?

Thanks in advance.

**Comment by webron** [comment]
Closing this ticket as a duplicate. Please follow #1422 for updates (#1475 is unrelated).
