### ISSUE TITLE
Support OAS 3.1 ?

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-parser#1535]
Does swagger-parser support and validate OAS 3.1 files?

http://spec.openapis.org/oas/v3.1.0

**Comment by webron** [comment]
@chrisdudley not yet. It's in the plans, but there's no ETA yet.

**Comment by spacether** [comment]
Can adding type null be one of the first features?

**Comment by hurjmc** [comment]
Will the same parser jar support both OAS3.0.x and OAS3.1.x documents?

**Comment by ech0s7r** [comment]
> @chrisdudley not yet. It's in the plans, but there's no ETA yet.

Do you have any ETA when OpenAPI 3.1.0 will be supported or the work will kickoff?

**Comment by amelnikoff** [comment]
Probably it's time to repeat question two months later:

> Do you have any update about when OpenAPI 3.1.0 will be supported or the work will kickoff?

Thanks!

**Comment by darkbasic** [comment]
https://github.com/swagger-api/swagger-parser/commits/oas3.1

**Comment by Mark-H** [comment]
@frantuma Is there any way to help? I'm happy to throw you a €50 bounty if that helps.

**Comment by frantuma** [comment]
Hey @Mark-H, many thanks for your kind offer! 

We have 3.1 in our short term roadmap, we'll add an explanation in a few days about what we're doing and how we are adding OAS 3.1 support to swagger-core and swagger-parser, sharing some design decisions, motivations, tasks involved, needed work and ongoing implementation. I'll link that in this and other tickets related to OAS 3.1 support, any thought/comment/discussion/coding and generally any help are highly welcome. Stay tuned and thanks

**Comment by spacether** [comment]
Any chance that this bug could be fixed as part of the 3.1 roadmap?
https://github.com/swagger-api/swagger-parser/issues/1603
Composed schemas are important and when the parser processes these AnyType schemas it incorrectly sets their types as type object and array. This makes composition not work these use cases.

**Comment by gunsluo** [comment]
any updates on OAS3.1?

**Comment by frantuma** [comment]
@gunsluo on its way, should be very short term for parser support including dereferencing. Swagger Core support for representation/serialization/deserialization has been implemented, along with OAS 3.0 conversion into 3.1 as a (temporary) way to get a OAS 3.1 spec out of code first resolving by Swagger Core. No ETA but quite short term also (some 3-4 weeks) we are going for OAS 3.1 full support in Swagger Core code first resolving in terms of annotations and related logic

**Comment by frantuma** [comment]
#1730 implements OAS 3.1 Support in terms of parsing/validation and de-referencing / resolving.

Updated documentation about usage, features, limitations and remaining tasks will follow shortly (Swagger Core and Swagger Parser)

**Comment by spacether** [comment]
@frantuma should this be closed?

**Comment by samgqroberts** [comment]
It looks like as of v2.1.0 this can be closed https://github.com/swagger-api/swagger-parser/releases/tag/v2.1.0
