### ISSUE TITLE
External $ref without '/' causes exception

### ISSUE THREAD

**Issue by kaewberg** [swagger-api/swagger-parser#1543]
$ref("another_file.json#/something") causes StringIndexOutOfBounds, becuase no '/' is found in left part of reference. In addition, $ref("../../a_third_file.json#/something") also causes StringIndexOutOfBounds on Windows, because the code searches for File.separatorChar (= '\\') as path separator.

**Comment by gracekarina** [comment]
Hi@kaewberg,  can you please share the spec is causing this? Thanks.

**Comment by kaewberg** [comment]
Added a test, testRelativePathIssue1543
