### ISSUE TITLE
Update Commons IO from 2.6 to 2.11.0

### ISSUE THREAD

**Issue by JacksonBDuke** [swagger-api/swagger-parser#1586]
Current version of Apache Commons IO (2.4) suffers from the following (among others):

| Issue | Description | Fixed In |
|---|---|---|
| [IO-675](https://issues.apache.org/jira/browse/IO-675) | InfiniteCircularInputStream throws a divide-by-zero exception when reading if its input buffer is size 0 | [2.8](http://commons.apache.org/proper/commons-io/changes-report.html#a2.8.0) |

Want to update version of Commons IO to the latest release.

**Comment by gracekarina** [comment]
closed by #1587
