### ISSUE TITLE
Add support for JAR: URLs to OpenAPIV3Parser

### ISSUE THREAD

**Issue by allen-ball** [swagger-api/swagger-parser#1592]
This is a feature request: Add support for jar:jar-uri!/inputSpec.yml styled URLs to OpenAPIV3Parser.  The motivation is in Maven builds the input spec can be specified with the dependency property path mechanism like:

```xml
<inputSpec>jar:file://${ganymede:ganymede-client:jar}!/ganymede-rest-protocol.yml</inputSpec>
```

while simply providing the resource path often fails because the Maven compile classpath is often different than code generator's (combined with an issue with the plugin itself; see https://github.com/OpenAPITools/openapi-generator/issues/10016).

**Comment by gracekarina** [comment]
Hey this PR has been merged, thanks for the contribution.
