### ISSUE TITLE
Description with Empty String is not failing

### ISSUE THREAD

**Issue by SCSreekanth** [swagger-api/swagger-parser#1597]
Description field for an OpenAPI document isn't optional. However, the parser is not throwing error when given the value as "" (empty)

**In json**
{
  "title": "Sample Pet Store App",
  "description": ""
}

**In yml**

title: Sample Pet Store App
description: ''

When this document is passed, the parser is not throwing a validation error but returns null for description, and if the model is created with null, then the validation complains about a missing description.

Please check if this can be handled.

**Comment by gracekarina** [comment]
Hey @SCSreekanth in which place would be located the description you mention? which version of OpenAPI are you refering to?

**Comment by SCSreekanth** [comment]
Wrong Issue
