### ISSUE TITLE
Need Tentative Release date for 2.0.28.

### ISSUE THREAD

**Issue by mma5997** [swagger-api/swagger-parser#1598]
Hi Team,
Is there any tentative release date for 2.0.28.
We are waiting for fix for #1579 in an official release. Please can anyone help with any intel on the release date?

Thanks and regards,
Mandar

**Comment by gracekarina** [comment]
Hi @mma5997 sorry it took so long to respond, we'll release in a couple of weeks.

**Comment by mma5997** [comment]
Thanks Grace, closing this thread as got the response.
