### ISSUE TITLE
FileInputStream is not closed and the refFile cannot be deleted

### ISSUE THREAD

**Issue by lijiajun05** [swagger-api/swagger-parser#1620]
1、Springboot project. maven dependency：
 <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-parser</artifactId>
            <version>1.0.55</version>
  </dependency>

2、Issue location:
  class: [io.swagger.parser.util.RefUtils](https://github.com/swagger-api/swagger-parser/blob/v1.0.55/modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java)
  method: readExternalRef()
  line nums: 141, 152

3、Issue description:
  Source code:`result = IOUtils.toString(new FileInputStream(pathToUse.toFile()), "UTF-8");`
  The method **`IOUtils.toString()`** do not flush or close the stream. So `new FileInputStream(pathToUse.toFile()`  is not closed and the file cannot be deleted.
In my project, the refFiles are temporary and need be deleted, then found this issue.
Thanks for replying to this issue.

4、Suggestion:
`FileUtils.readFileToString()` could be considered.

**Comment by frantuma** [comment]
fixed in #1721
