### ISSUE TITLE
OpenAPIV3Parser assigns null for empty string in response description

### ISSUE THREAD

**Issue by Sarangan0219** [swagger-api/swagger-parser#1631]
### Problem statement

We have a response definition in the swagger as given below:

```
    "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
```
We are executing the below code snippet over this swaggerContent :

   ```
        
        // Validate Swagger definition - Line 1

       OpenAPI getOpenAPI(String oasDefinition) {
          OpenAPIV3Parser openAPIV3Parser = new OpenAPIV3Parser();
          SwaggerParseResult parseAttemptForV3 = openAPIV3Parser.readContents(oasDefinition, null, null);
          if (CollectionUtils.isNotEmpty(parseAttemptForV3.getMessages())) {
              log.debug("Errors found when parsing OAS definition");
          }
          return parseAttemptForV3.getOpenAPI();
       }

        OpenAPI openAPI = getOpenAPI(swaggerContent);
        Paths paths = openAPI.getPaths();
        // some logic here
       String swaggerContent  = Json.pretty(openAPI);

        // Validate swaggerContent - Line 101
```

The open API object generated is as given below:

```
 responses: class ApiResponses {
                    {200=class ApiResponse {
                        description: null
                        headers: null
                        content: null
                        links: null
                        extensions: null
                        $ref: null
                    }}
                    extensions: null
                }
```

And the returned swagger definition from Json.pretty() method is as given below:

```
    "responses" : {
          "200" : { }
        },
```
First, we are validating the swagger definition before applying the logic and there are no errors. But, when revalidating this returned swaggerContent from Json.pretty() method we encounter an error message from OAS3Parser as **attribute paths.'/auth/signup'(post).responses.200.description is missing**. We are using OAS Parser version 2.0.20 and it generates definitions in version 3.0.1 - [1].

So the issue is when  `"description": ""` in the swagger definition the swagger validation is passing. After converting it to an open API object, do some logic and reconvert it back to a swagger content to a string it removes the description attribute from the response, hence throwing an error.

### Solution

- We need to reject the swagger definition when it has a response description is an empty string from **Line-1** itself. But here due to the OpenAPIV3Parser behavior, it is rejecting the definition at **Line-101**.

- Or else OpenAPIV3Parser should  not assign null values for empty strings when converting a string swagger to an open API object

[1] [https://github.com/swagger-api/swagger-core/blob/v2.1.2/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/OpenAPI.java#L37](https://github.com/swagger-api/swagger-core/blob/v2.1.2/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/OpenAPI.java#L37)

**Comment by Sarangan0219** [comment]
Hi Team, Any update on this issue ?

**Comment by gracekarina** [comment]
Hi, we had a PR merged a few weeks ago. Which version are you using? 
https://github.com/swagger-api/swagger-parser/pull/1619

**Comment by Sarangan0219** [comment]
We are using 2.0.20. 
As this is urgent shall we get a release with this fix ASAP ?

**Comment by vithu30** [comment]
@gracekarina when we can expect the next release of swagger-parser?

**Comment by gracekarina** [comment]
@Sarangan0219 we are currently on 2.0.29-SNAPSHOT, please update your parser, this issue was already fix.

**Comment by gracekarina** [comment]
@vithu30  @Sarangan0219  we plan to release this week 🎉

**Comment by SCSreekanth** [comment]
Even with swagger-parser-v3-2.0.29.jar I am still getting a null in the response for the open API content

```
openapi: 3.0.0
servers:
  - url: https://api.remove.bg/v1.0
info:
  title: Background Removal API
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        "200":
          description: ""
```

**Comment by gracekarina** [comment]
@SCSreekanth  are you setting the new option `allowEmptyStrings` to true?

**Comment by SCSreekanth** [comment]
Hi @gracekarina - Sorry, it's working for me now.

Thanks,
Sree
