### ISSUE TITLE
Style and Explode is getting added when content is present 

### ISSUE THREAD

**Issue by SCSreekanth** [swagger-api/swagger-parser#1637]
Hi team,

Please check the attached openapi document

openapi: 3.0.1
info:
  title: sample
  version: "1.0"
servers:
- url: www.abc.com
paths:
  /test:
    get:
      operationId: test
      parameters:
      - name: id
        in: query
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: string
      responses:
        200:
          description: Ok

When this content is read using OpenAPIV3Parser.read(), the OpenAPI model that is generated has "style" and "explode" values set as "form" and "true" respectively. Isn't that wrong? Because for the same content with style:form or explode:true, the swagger editor https://editor.swagger.io/ complains as Structural error "should not have style, explode, allowReserved, example, or examples when content is present".

The parser though doesn't complain when there style/explore along with content. What should be the expected behavior here? Thanks

Regards,
Sree

**Comment by SCSreekanth** [comment]
Hi Team, 

Any updates here? This is critical as the re-generated openapi document is invalid.

Thanks,
Sree

**Comment by zkajzer** [comment]
Same issue here. When serializing the object, I get lines like these:

`"style" : "SIMPLE",`

which according to the swagger editor is not valid.

**Comment by gracekarina** [comment]
@zkajzer thanks for reporting this issue!!, it should be fixed with the solution in the PR. please reopen if this keeps happening.
