### ISSUE TITLE
Poor error message when parameter "in" definition missing

### ISSUE THREAD

**Issue by kerrykimbrough** [swagger-api/swagger-parser#1644]
It's an error if the "in" attribute is not defined for a request parameter. In version 2.0.28, this error produces an accurate message:

```
attribute paths.'/operations'(post).parameters.[param0].in is missing
```

But in version 2.0.29, an additional error message is produced. Which is not very good. It is confusing (is "in" missing or not?) and misleading (no, there are not 2 errors).
```
attribute paths.'/operations'(post).parameters.[param0].in is not of type `string`
```

**Comment by gracekarina** [comment]
Hi @kerrykimbrough thanks for reporting this, would you please share a minimal sample of definition when this happens?

Thanks

**Comment by kerrykimbrough** [comment]
[param-in-missing.json.txt](https://github.com/swagger-api/swagger-parser/files/7981904/param-in-missing.json.txt)

**Comment by gracekarina** [comment]
Hey @kerrykimbrough I did a quick local test with tags/v2.0.29 and current snapshot and I haven't been able to reproduce the message with the definition provided.  This is what I'm getting: `[attribute paths.'/operations'(post).parameters.[param0].in is missing]`

**Comment by kerrykimbrough** [comment]
Sorry, I misstated the problem symptom. I have corrected the original description.

**Comment by kerrykimbrough** [comment]
The problem is caused by a recent change to OpenAPIDeserializer at line 1592:

```
...
8ba9dd98e	( haoyu.guo	2021-03-23 19:39:39 +0800	1590)		String value = getString("in", obj, true, location, result);
d1a151ca7	( haoyu.guo	2021-03-23 18:41:19 +0800	1591)
2d129e714	(gracekarina	2021-10-12 16:20:11 -0500	1592)		if (!result.isAllowEmptyStrings() && value == null) {
8ba9dd98e	( haoyu.guo	2021-03-23 19:39:39 +0800	1593)			return null;
8ba9dd98e	( haoyu.guo	2021-03-23 19:39:39 +0800	1594)		}
...
```

Previously, the missing "in" error caused `value == null` and an immediate return. But now the check for `isAllowEmptyStrings` allows things to continue to report the additional bogus error.  I don't understand the purpose of `isAllowEmptyStrings` but it seems very inappropriate for such a global setting to allow a violation of the OpenAPI spec to be ignored.

**Comment by kerrykimbrough** [comment]
It seems that `ParseResult.isAllowEmptyStrings` may have been added to resolve issue #1631. But using it here doesn't make sense. The "in" value is extracted using `getString` which will return an empty string without collapsing it to null. `getString` correctly returns null only when the value is missing or explicitly `null`.

In general, applying `isAllowEmptyStrings` directly to the result of `getString` appears to be a mistake, unless some additional special logic is needed to address a specific situation (like issue #1631). If so, this mistake seems to be repeated many times in `OpenAPIDeserializer`.

**Comment by gracekarina** [comment]
Hi @kerrykimbrough  There is a new option for parser to allow empty strings as valid,  you can always just set the option to false, to have the behavior from 2.0.28, but I think there is no need as I just merged a PR with a better validation in the parameters deserialization.
I hope this helps.

**Comment by kerrykimbrough** [comment]
I don't think PR #1645 is an improvement. It doesn't even change the behavior originally reported, i.e. the extra misleading "not of type string" message. I guess what you're saying is that the extra message is not really a problem.

**Comment by kerrykimbrough** [comment]
Sorry, my previous comment was mistaken. I have deleted it.
