### ISSUE TITLE
Request body: empty "content" not recognized as an error

### ISSUE THREAD

**Issue by kerrykimbrough** [swagger-api/swagger-parser#1648]
A Request Body Object is defined by a "content" attribute that specifies the possible media types. But what if no media types are specified? The OpenAPI spec doesn't say anything about this situation. But clearly the intention is that at least one media type must be defined. [This clarification ](https://github.com/OAI/OpenAPI-Specification/discussions/2875)is likely to appear in the next version of the spec.

Accordingly, an empty "content" attribute for a Request Body Object should be reported as an error.

**Comment by gracekarina** [comment]
Thanks @kerrykimbrough  Closed by merged Pr #1649
