### ISSUE TITLE
swagger-parser 1.0.57 adding responsesObject to the definition

### ISSUE THREAD

**Issue by RakhithaRR** [swagger-api/swagger-parser#1669]
We recently updated the swagger-parser from 1.0.51 to 1.0.57. After this upgrade, when we add this[1] swagger to our application, the parsed definition has an additional `responsesObject` field. The swagger editor shows this as a Structural error

![image](https://user-images.githubusercontent.com/25485273/156764635-78c48139-c240-4878-ba7f-5cb76ba2585e.png)

The output of [1] after being parsed gives the following.

```
/pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Pets'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
      responsesObject:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Pets'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
```

We are doing the following in our code
```
SwaggerParser parser = new SwaggerParser();
SwaggerDeserializationResult parseAttemptForV2 = parser.readWithInfo(oasDefinition);
```
Is there an option to disable this? Is this a bug in the parser?

[1] - https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml

**Comment by chashikajw** [comment]
I'm also getting this issue. Any update on this?

**Comment by chashikajw** [comment]
I think This happens from swagger.models.version 1.6.3.

**Comment by gracekarina** [comment]
Hi, @RakhithaRR @chashikajw I have tested locally the definition provided and I haven't been able to reproduce the issue, note that I am using latest parser release version: `1.0.58` and latest core version: `1.6.5` 

Please try test this again with the current version.

**Comment by ponelat** [comment]
I think we need to add this to the README then (cc @gracekarina )
