### ISSUE TITLE
Malformed Spec Causes NPE

### ISSUE THREAD

**Issue by ricekot** [swagger-api/swagger-parser#1685]
Parsing the following spec:
```json
{
   "notswagger:"x.0"
}
```
results in an NPE instead of returning a list of errors.

This may be happening because `out.getOpenAPI()` is nullable at: https://github.com/swagger-api/swagger-parser/blob/16708906796e2e1b4a9ef6bab1e29a6c95ba5ff1/modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java#L114

Stack trace:
```
java.lang.NullPointerException
	at io.swagger.v3.parser.util.ResolverFully.resolveFully(ResolverFully.java:61)
	at io.swagger.v3.parser.converter.SwaggerConverter.readResult(SwaggerConverter.java:114)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:92)
...
```

**Comment by gracekarina** [comment]
Hi @ricekot thanks for reporting this issue, we have added a pr with a test and the fix. Please reopen if this keep happening.

**Comment by ricekot** [comment]
It seems that the NPE is resolved, but the error is still not reported. The spec I provided above is deliberately malformed, and the SwaggerParserResult object should contain the following (or similar) error message: 
```
Unexpected character ('x' (code 120)): was expecting a colon to separate field name and value
 at [Source: (String)"{
  "notswagger:"x.0"
}
```
This is printed to the output but not returned in the error messages list.

**Comment by gracekarina** [comment]
@ricekot please check, I have added a solution for the messages don't get lost in the process of conversion.

**Comment by ricekot** [comment]
Yes, thank you, this issue is resolved now.
