### ISSUE TITLE
SSL-error when reading swagger definition 

### ISSUE THREAD

**Issue by olensmar** [swagger-api/swagger-parser#169]
The following code:

```
        SwaggerParser parser = new SwaggerParser();
        final Swagger swagger = parser.read("https://api.rocrooster.net/api-docs.json");
```

Will fail with an SSL-related error - I've created a patch in branch https://github.com/swagger-api/swagger-parser/tree/httpclient-for-ssl which uses a lax:ed HttpClient for reading the definition - after which the above code works fine (it's added as a simple unit test in the branch)

Not sure if you wanted to introduce the httpclient dependency in the core parser - so I haven't done a PR until you've had a look

**Comment by frantuma** [comment]
@fehguy @olensmar An alternative approach possibly limited to the specific or similar issue (call to https://api.rocrooster.net/api-docs.json with server checking user agent) without adding deps, would be adding User-Agent header to RemoteUrl connection, as in #171

**Comment by olensmar** [comment]
thanks - the original issue that spurred this is at http://community.smartbear.com/t5/SoapUI-NG/How-to-create-SoapUI-NG-project-from-Swagger-over-HTTPS/m-p/112463#U112463 - but since we don't have access to their swagger-definition it's hard to know if neither efforts would help... I would prefer to "shoot broadly" and go with the http-client solution - but it's your call...

**Comment by olensmar** [comment]
ok - their Swagger definition actually seems to work fine with older versions of the parser now - so I'm changing my mind and would be fine with just adding a User-Agent header to the RemoteUrl connection as suggested by @frantuma

**Comment by fehguy** [comment]
Ok, parser 1.0.17 was released yesterday, can you update to that?

**Comment by olensmar** [comment]
will do - thanks

**Comment by olensmar** [comment]
I still get 

```
reading from https://api.rocrooster.net/api-docs.jsonjavax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2011)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1113)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:101)
```

when trying to load https://api.rocrooster.net/api-docs.json

**Comment by fehguy** [comment]
I botched the release.  stay tuned.

**Comment by garydgregory** [comment]
I also do not see swagger-parser 1.0.17 in Maven Central.

Gary

On Tue, Feb 2, 2016 at 8:58 AM, Tony Tam <notifications@github.com> wrote:

> I botched the release. stay tuned.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-parser/issues/169#issuecomment-178686633>
> .
>



-- 
E-Mail: garydgregory@gmail.com | ggregory@apache.org
Java Persistence with Hibernate, Second Edition
<http://www.manning.com/bauer3/>
JUnit in Action, Second Edition <http://www.manning.com/tahchiev/>
Spring Batch in Action <http://www.manning.com/templier/>
Blog: http://garygregory.wordpress.com
Home: http://garygregory.com/
Tweet! http://twitter.com/GaryGregory

**Comment by fehguy** [comment]
it's there now, sorry about that.
