### ISSUE TITLE
missing inner type causes failure in compat lib

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-parser#17]
if you have a model property like such:

```
"topics": {
  "type": "array",
  "description": "Topics present in the newsletter"
}
```
the parser will die because it's expecting `items` to be populated.  Make it friendly.  Make it fun

**Comment by webron** [comment]
Did you make it fun?

**Comment by fehguy** [comment]
@webron https://github.com/swagger-api/swagger-parser/commit/9a4193a7983f2cca43d2bd5ffec7525c559512c7#diff-e280195c2ed7ce7e15912f4990b54e5aR269

**Comment by webron** [comment]
You should add the :tada: character to the error message, otherwise it's not 'fun'.
