### ISSUE TITLE
Enforce type object in Schema object containing allOf

### ISSUE THREAD

**Issue by jeanbaptistebenoist-sage** [swagger-api/swagger-parser#1708]
In the openapi specifications there is:
`The OpenAPI Specification allows combining and extending model definitions using the allOf property of JSON Schema, in effect offering model composition. allOf takes an array of object definitions that are validated independently but together compose a single object.`
So considering the fact that all the components inside allOf are objects, the combination will be a type object for sure but currently we are just taking the type of the object containing the allOf but if the type is empty like here (example from Models with Composition in https://swagger.io/specification/):
```
ExtendedErrorModel:
    allOf:
      - $ref: '#/components/schemas/ErrorModel'
      - type: object
        required:
        - rootCause
        properties:
          rootCause:
            type: string
```
We will return an object with the aggregation resolved but without any type. Will you agree that we add a feature that enforce the type object if the current ComposedSchema doesn't have any type and contain a allOf? (And we can give a warning if there is already a type specified and the type is not object but we will keep the type enforced for the result)

**Comment by kerrykimbrough** [comment]
Disagree. The OpenAPI spec (actually, the JSON schema spec) does not require a `type` keyword in any schema. This parser implementation must not add any such requirement.  As long as each `allOf` member either defines the same `type` or no `type`, there is not _necessarily_ any inconsistency in aggregating all member assertions into a single schema.

**Comment by jeanbaptistebenoist-sage** [comment]
Ok I understand the point of view so let's close this issue and not change anything, thank you for your opinion
