### ISSUE TITLE
Can you please create a release with this new code. 

### ISSUE THREAD

**Issue by herrhilmi** [swagger-api/swagger-parser#1720]
https://github.com/swagger-api/swagger-parser/blob/50d8cfbdd1735ce893a0e66952bba4fd38a8a588/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RefUtils.java#L251

Hi, 

In fact,  the below version  has a memory leak in Line 111. The FileInputStream used to read the  spec is never closed. 

<dependency>
    <groupId>io.swagger.parser.v3</groupId>
    <artifactId>swagger-parser</artifactId>
    <version>2.0.32</version>
</dependency>

I think the current code could help solve this, since it's used within try-with-resources block. 

Thank you

**Comment by frantuma** [comment]
@herrhilmi thanks for reporting this, can you please clarify what you mean with `the below version has a memory leak in Line 111`? (e.g. which version, and can you share the pointer to the line in the file you are referring to?

**Comment by herrhilmi** [comment]
@frantuma 

In fact, I use io.swagger.parser.v3:swagger-parser:2.O.32 in my code. This dependency has a transitive dependency to 
io.swagger:swagger-parser:1.0.59 as shown in  the line below within pom

https://github.com/swagger-api/swagger-parser/blob/50d8cfbdd1735ce893a0e66952bba4fd38a8a588/pom.xml#L397

Leak memory is found in this class
https://github.com/swagger-api/swagger-parser/blob/0cd775a10f75bd0ac5f89823282b3fa2a2ed9f30/modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java#L141

Thank you

**Comment by frantuma** [comment]
@herrhilmi thanks for the details, we have fixed that in #1721 , and we'll cut a release for v1 and v2 with the fix in around 2 weeks.

Closing ticket, please reopen if still experiencing issues
