### ISSUE TITLE
Exporting API - null values in resolved YAML and JSON

### ISSUE THREAD

**Issue by gracekarina** [swagger-api/swagger-parser#1737]
note: 
This is caused by InlineModelResolver calling setExample in various places, independently of its value that might be null; this causes the null example to be serialized. Please update the code to do null checks along with check of value of exampleSetFlag` (only set example when value not null OR exampleSetFlag is true).

**Comment by alebastrov** [comment]
link this issue with https://github.com/swagger-api/swagger-core/issues/4381
