### ISSUE TITLE
ExampleSetFlag leaks in the output generated

### ISSUE THREAD

**Issue by hibaline** [swagger-api/swagger-parser#1743]
It seems that when I generate An openapi file after parsing an old one which is a valid openAPI file, this property "ExampleSetFlag" is either been set to false or true and then it'is added to the specification file that is generated which won't be a valid openapi speciication

Can someone help me figure out why is hapening, knowing that I am using the latest version of swagger parser 
here is the artefact :
		<dependency>
			<groupId>io.swagger.parser.v3</groupId>
			<artifactId>swagger-parser</artifactId>
			<version>2.0.33</version>
		</dependency>

by the way this a portion of the generated file, and here is what it looks like : 
"paths" : {
    "/rs-services/v2/authentication/hostedFieldsInitialize" : {
      "post" : {
        "tags" : [ "Authentication" ],
        "description" : "",
        "operationId" : "hostedFieldsInitialize",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/HostedFieldsInitializeInput",
                "exampleSetFlag" : false
              },
              "example" : "",
              "exampleSetFlag" : true
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "The request has succeded",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/HostedFieldsInitializeOutput",
                  "exampleSetFlag" : false
                },
                "example" : "",
                "exampleSetFlag" : true
              }
            }
          }
        }
      }
    },

and also in the components section, here is a portion of it

 "components" : {
    "schemas" : {
      "AcceptChallengeInput" : {
        "required" : [ "interfaceVersion", "merchantId" ],
        "type" : "object",
        "properties" : {
          "comment" : {
            "type" : "string",
            "description" : "",
            "exampleSetFlag" : false
          },
          "interfaceVersion" : {
            "type" : "string",
            "description" : "",
            "exampleSetFlag" : false
          },
          "intermediateServiceProviderId" : {
            "type" : "string",
            "description" : "",
            "exampleSetFlag" : false
          },
          "keyVersion" : {
            "type" : "integer",
            "description" : "",
            "format" : "int64",
            "exampleSetFlag" : false
          },
          "merchantId" : {
            "type" : "string",
            "description" : "",
            "exampleSetFlag" : false
          },
          "operationOrigin" : {
            "type" : "string",
            "description" : "",
            "exampleSetFlag" : false
          },
          "s10TransactionReference" : {
            "description" : "",
            "$ref" : "#/components/schemas/S10TransactionReference",
            "exampleSetFlag" : false
          },

**Comment by alebastrov** [comment]
see https://github.com/swagger-api/swagger-core/issues/4381 issue

**Comment by frantuma** [comment]
please see [this comment](https://github.com/swagger-api/swagger-core/pull/3637#issuecomment-682370287) about using the correctly configured object mapper.

closing ticket, please reopen if you're still experiencing issues
