### ISSUE TITLE
Accidentally removed "test" scope from "slf4j-simple"?

### ISSUE THREAD

**Issue by christopher-cudennec** [swagger-api/swagger-parser#1753]
Hey everyone!

I just had to fix an update to your latest version in our open source library sda-dropwizard-commons: https://github.com/SDA-SE/sda-dropwizard-commons/pull/1663

The issue was that you removed the "test" scope from dependency "slf4j-simple" which I guess happened by accident, right? Could you double check your changes and add the scope again?

Here's the file:
https://github.com/swagger-api/swagger-parser/blob/v2.1.0/modules/swagger-parser-v3/pom.xml

Here's the commit that removed the scope:
https://github.com/swagger-api/swagger-parser/commit/3ac5401380befc336dbab077d0fe73c3a1b64a24#diff-39aeb849fc2cee74ac7373cabe6e5b9c3b40174d433ca537067c6ac44e5841bf

Thanks!

Christopher

**Comment by frantuma** [comment]
Thanks for reporting this! It has been indeed an accident gone unnoticed, fixed in #1754 and released 2.1.1 with the fix
