### ISSUE TITLE
Component schema with a value of true or false throws an error

### ISSUE THREAD

**Issue by spacether** [swagger-api/swagger-parser#1757]
Component schema with a value of true or false throws and error

```
openapi: 3.0.3
info:
  title: openapi 3.0.3 sample spec
  description: sample spec for testing openapi functionality, built from json schema
    tests for draft6
  version: 0.0.1
paths: {}
components:
  schemas:
    BooleanSchemaTrue: true
    BooleanSchemaFalse: false
```
Throws the error:
BooleanSchemaTrue is not of type `object`
BooleanSchemaFalse is not of type `object`

For openapi v3.0.3 this is probably correct, I got these results using swagger-parser 2.0.31
But for v3.1.0 specs, should we get this result?

**Comment by frantuma** [comment]
thanks for reporting this. Fixed in https://github.com/swagger-api/swagger-parser/pull/1768 for 3.1 specs
