### ISSUE TITLE
Parser parse swagger with wrong version without errors

### ISSUE THREAD

**Issue by DaniShMyGit** [swagger-api/swagger-parser#1780]
If i'm testing the following swagger spec in swagger editor:
```
{
  "openapi": "3.0",
  "info": {
    "description": "This is a credit card account service tier 3 microservice",
    "title": "SC-CCS-CCSRV_AC Credit Card Account Service",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "creditCardAccount",
      "description": "Credit Card Accounts"
    }
  ],
  "paths": {},
  "x-ibm-configuration": {}
}
```

The swagger editor knows to show an error:

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/43296520/183302391-ac3435ba-15bd-4661-a772-d3e70e617e54.png">

But when using the library to parse the same swagger, I'm getting an openApi with version "3.0" without error message.
nevermind If i'm using:
`OpenAPIV3Parser().readLocation` nor `OpenAPIV3Parser().readContents`

**Comment by gracekarina** [comment]
Hi @DaniShMyGit We've committed a PR for this issue, parser will show a validation message, but it will continue the parsing.
