### ISSUE TITLE
ApiParser does not support reference path that contains numbers

### ISSUE THREAD

**Issue by gracekarina** [swagger-api/swagger-parser#1803]
ApiParser does not support reference path that contains numbers

**Comment by Abhiintheweb** [comment]
@gracekarina  Can you put an example. Link you have shared is not available in public.

**Comment by gracekarina** [comment]
Hi @Abhiintheweb  please see this PR I've been working on https://github.com/swagger-api/swagger-parser/pull/1827

**Comment by gracekarina** [comment]
closed by https://github.com/swagger-api/swagger-parser/pull/1765
