### ISSUE TITLE
Schema type is null

### ISSUE THREAD

**Issue by ihsanciftci** [swagger-api/swagger-parser#1864]
I'm parsing sendgrid api: https://raw.githubusercontent.com/sendgrid/sendgrid-oai/main/oai_v3_stoplight.json
The types of some schemas are null but they are not in the json.

PS. 
Java Version: 18
swagger-parser version: 2.1.9 

(I'm using stoplight version because  original version (https://raw.githubusercontent.com/sendgrid/sendgrid-oai/main/oas_v3.json) contains references to other files. And swagger java parser cannot handle reference name containing curly braces. That's another story or bug)

```java
        String url = "https://raw.githubusercontent.com/sendgrid/sendgrid-oai/main/oai_v3_stoplight.json";

        ParseOptions options = new ParseOptions();
        options = null;
        //options.setResolve(true);
        //options.setFlatten(true);

        SwaggerParseResult result = new OpenAPIParser().readLocation(url, null, options);
        OpenAPI openAPI = result.getOpenAPI();
```

e.g. for schema type is null

```json
{
    "mail_send": {
        "post": {
            "operationId": "POST_mail-send",
            "summary": "v3 Mail Send",
            "tags": [
                "Mail Send"
            ],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "personalizations": {
                                    "type": "array",
                                    "description": "An array of messages and their metadata. Each object within personalizations can be thought of as an envelope - it defines who should receive an individual message and how that message should be handled. See our [Personalizations documentation](https://sendgrid.com/docs/for-developers/sending-email/personalizations/) for examples.",
                                    "uniqueItems": false,
                                    "maxItems": 1000,
                                    "items": {}
                              }
                        }
                  }
            }
     }
````

**Comment by ihsanciftci** [comment]
After debugging the API, I have realized that instead of setting type attribute, API adds it to types attribute.
Is it related with v3.1?

**Comment by frantuma** [comment]
yes, please see [Swagger Core Wiki](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---OpenAPI-3.1)

and [this comment](https://github.com/swagger-api/swagger-parser/issues/1821#issuecomment-1300918559) for a discouraged option to have `type` bound to `types`

For 3.1 specs please use `Yaml31` and `Json31` helper classes for serialization

please close ticket if this answers your question
