### ISSUE TITLE
Is is possible to convert OpenAPI(v3) model to Swagger(v2) model?

### ISSUE THREAD

**Issue by shyr** [swagger-api/swagger-parser#1881]
Hello. io.swagger.v3.parser.converter.SwaggerConverter seems to support converting from v2 model to v3 model. Is it possible to convert model v3 to v2?

**Comment by frantuma** [comment]
Hi, it is not possible (also because a lossless conversion v3->v2 is not achievable)

Closing ticket, please reopen if you have further questions
