### ISSUE TITLE
Parsing Swagger Doc with Path Parameter Not in Path

### ISSUE THREAD

**Issue by kevinmeredith** [swagger-api/swagger-parser#189]
Given `res3` equals the following simple Swagger Doc.

_Note_ that, per this [StackOverflow answer on path Swagger Path Params](http://stackoverflow.com/questions/27155516/swaggerissue-with-path-parameter/27156661#27156661), I did not append the path, `/{id}`, in the `/pets` path.

``` json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Swagger Petstore",
    "description": "A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "name": "Swagger API Team"
    },
    "license": {
      "name": "MIT"
    }
  },
  "host": "petstore.swagger.io",
  "basePath": "/api",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/pets": {
      "get": {
        "description": "Return a specific pet.",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "id of pet",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "a Pet."
          }
        }
      }
    }
  }
}
```

However, it parses successfully via `new Swagger20Parser().read(res3)`:

```
scala> import io.swagger.parser.Swagger20Parser
import io.swagger.parser.Swagger20Parser

scala> new Swagger20Parser().parse(res3)
res4: io.swagger.models.Swagger = io.swagger.models.Swagger@b6b5ef07

scala> res4.getPaths
res5: java.util.Map[String,io.swagger.models.Path] = {/pets=io.swagger.models.Path@23c163da}
```

Should there be a parse error since the `/pets` path did not equal `/pets/{id}` per the **path** parameter?

**Comment by fehguy** [comment]
Yes, right now the parser is focused on structural aspects rather than content validation.  But I agree that it can be improved to handle cases like this.  I'll leave your ticket open for us to get it supported.

**Comment by kevinmeredith** [comment]
Thanks for replying, @fehguy.

Has a discussion already happened on how to fix this? 

I'm only asking since I may have time to implement a fix. I'm looking at the code now, but, if you/others already have a fix in mind, that would help me out.

**Comment by fehguy** [comment]
not yet.  There is one class that does the structural validation and adds human-friendly error messages:

https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java#L41

It's slightly tricky because you may have references at this stage that you cannot verify.  For example the `{id}` parameter may be a JSON pointer with `$ref` syntax that cannot resolve here.  But for most cases, having a parameter check in this code would be great.

**Comment by kevinmeredith** [comment]
OK - I've almost got a PR ready. I will mention you on the PR to request your review, please.

However, I'd like to make sure that I properly understand path parameters, @fehguy.

Since a `path` may have multiple operations, as I understand, I believe it's possible that a Swagger doc contain a single path two 2 operations:

Example:

> path : `/foobar/{id}` with both `GET` and `PUT` operations.

That means that, per this issue, both `GET` and `PUT` operations would need to define a `path` parameter of value `id`?

And, more broadly, if a `path` has a path parameter with `1..n` operations, then each operation must define such a `path parameter`?

**Comment by kevinmeredith** [comment]
And, looking at [thing.json](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/test/resources/thing.json#L32-L65), I realize that I don't understand where path parameters must be specified within the Swagger Doc.

Given a `/pets/{id}` path, where must `id` appear in the Swagger Doc? It can appear in either the top-level `parameters` versus a Path Parameter of a Path's Operation?

**Comment by webron** [comment]
@kevinmeredith The parameter can appear in two places - either at the operation level https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationParameters or at the Path Item level - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathItemParameters.

The top level parameters object is unrelated.

**Comment by kevinmeredith** [comment]
Thanks, @webron, for the input. I'll adjust my [PR](https://github.com/swagger-api/swagger-parser/issues/196) accordingly.

**Comment by fehguy** [comment]
Not going to enforce this in the parser at this time.
