### ISSUE TITLE
DeserializationUtils in 2.13.1 with SnakeYaml 2 no longer loads large YAML files

### ISSUE THREAD

**Issue by StevenWallTR** [swagger-api/swagger-parser#1912]
I am trying to use 2.13.1 with Snakeyaml 2 and our large (4+ MB) YAML file will no longer load.

This code was working with 2.11.1 and Snakeyaml 1.33:
```
int maxCodePoints = 5 * 1024 * 1024;  //5MB
System.setProperty("maxYamlCodePoints", Integer.toString(maxCodePoints));
OpenAPIV3Parser v3parser = new OpenAPIV3Parser();
openApi = v3parser.read(OPEN_API_SPECIFICATION);
```
Now with 2.13.1 and Snakeyaml 2, I receive this error:
`org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.`

The issue is with this [commit to the DeserializationUtils class](https://github.com/swagger-api/swagger-parser/commit/27a690e91017780156dd1f3015348e4eac93b044#diff-8b270598eca1e0d7cef77e9bb04d916f9281047aa13f85cd80a6ae8821b2c656).  Prior to the commit, line ~266 would set the maxYamlCodePoints on the LoaderOptions class.  That code was replaced by the buildLoaderOptions() method, which does not set the maxYamlCodePoints property.

**Comment by frantuma** [comment]
Thanks for reporting this!

Fixed by #1914
