### ISSUE TITLE
SerializableParameter getMinLength() and getMaxLength() not returning values

### ISSUE THREAD

**Issue by brando76** [swagger-api/swagger-parser#192]
swagger-parser : version 1.0.16
We have a parameter as below.  However when parsing our swagger file we get the expected pattern value with getPattern() but getMinLength() and getMaxLength() return null even though they have values.

      parameters:
        - name: Code
          in: path
          description: The code
          required: true
          type: string
          minLength: 4
          maxLength: 5
          pattern: '^[a-zA-Z]'

**Comment by fehguy** [comment]
Can you please retest with 1.0.17?  If that doesn't work, it's a bug that needs to be addressed.

**Comment by brando76** [comment]
I just retested with 1.0.17 and the same problem exists.  Thanks.
