### ISSUE TITLE
SwaggerCompatConverter loses default value for parameters

### ISSUE THREAD

**Issue by benken-parasoft** [swagger-api/swagger-parser#20]
When SwaggerCompatConverter is reading a Swagger 1.2 document, default values are lost on parameters.  This can be seen in the 1.2 version of the petstore example for ""/pet/findByStatus".  It has a status parameter with a default value of "available".  The problem is in SwaggerCompatConverter.convertParameter().

As a workaround, I am extending SwaggerCompatConverter and overriding convertParameter():

    @Override
    public Parameter convertParameter(io.swagger.models.apideclaration.Parameter param) {
        Parameter ret = super.convertParameter(param);
        String defaultValue = param.getDefaultValue();
        if (defaultValue != null) {
            if (ret instanceof PathParameter) {
                ((PathParameter) ret).setDefaultValue(defaultValue);
            } else if (ret instanceof QueryParameter) {
                ((QueryParameter) ret).setDefaultValue(defaultValue);
            } else if (ret instanceof HeaderParameter) {
                ((HeaderParameter) ret).setDefaultValue(defaultValue);
            } else if (ret instanceof FormParameter) {
                ((FormParameter) ret).setDefaultValue(defaultValue);
            } else if (ret instanceof CookieParameter) {
                ((CookieParameter) ret).setDefaultValue(defaultValue);
            }
        }
        return ret;
    }

**Comment by fehguy** [comment]
fixed in 1.0.3-SNAPSHOT https://github.com/swagger-api/swagger-parser/commit/9aaba27431425579bde766fc6fdb8ad44b32538f
