### ISSUE TITLE
[question] `io.swagger.parser.SwaggerParser` w/ v1.2 Docs

### ISSUE THREAD

**Issue by kevinmeredith** [swagger-api/swagger-parser#201]
I've been using `new SwaggerParser().read("PATH_TO_SWAGGER_V.1.2")` in my code.

Just now I ran this test:

```
scala> new SwaggerParser().read("<MY_V2_Swagger_Doc>").equals(
                            new SwaggerCompatConverter().read("<MY_V2_Swagger_Doc>")
     | )
reading from <MY_V2_Swagger_Doc>
reading from <MY_V2_Swagger_Doc>
res16: Boolean = true
```

If using `SwaggerParser` handles Swagger v1.2, then why include the `SwaggerCompatConverter` in the README?

**Comment by fehguy** [comment]
The `new SwaggerParser().read(...)` will go through the extension chain until it reads a spec correctly.  Without having the SwaggerCompatConverter in the classloader, you cannot load a 1.2 spec, period.
