### ISSUE TITLE
Swagger Parser doesn't have SafeURLResolve option for OAS 3.0 and OAS 2.0.

### ISSUE THREAD

**Issue by MiloszTarka** [swagger-api/swagger-parser#2030]
The following PRs:

1. https://github.com/swagger-api/swagger-parser/pull/1910
2. https://github.com/swagger-api/swagger-parser/pull/1911

Added a possibility for swagger-parser to provide a Allow & Block list when resolving external refs. Thanks to that, it is possible provide additional security layer when using this tool inside services. This functionality is still missing when resolving 3.0 and 2.0 versions of OAS. 

I've the proposal of the code prepared, so I'll put it on the PR when done.

**Comment by MiloszTarka** [comment]
Addressed in: 
https://github.com/swagger-api/swagger-parser/pull/2032
https://github.com/swagger-api/swagger-parser/pull/2031

**Comment by frantuma** [comment]
implemented in #2031 and #2032
