### ISSUE TITLE
allOf deserialised incorrectly

### ISSUE THREAD

**Issue by demonfiddler** [swagger-api/swagger-parser#204]
Whilst researching swagger-codegen Issue [#2161](https://github.com/swagger-api/swagger-codegen/issues/2161), it would appear that the following code at io.swagger.parser.util.SwaggerDeserializer lines 821-822 can potentially deserialise the elements of an `allOf` list incorrectly:
```java
                    if (allComponents.size() >= 2) {
                        model.setChild(allComponents.get(allComponents.size() - 1)); // <== 822
                        List<RefModel> interfaces = new ArrayList<RefModel>();
                        int size = allComponents.size();
                        for (Model m : allComponents.subList(1, size - 1)) { // <== 825
                            if (m instanceof RefModel) {
                                RefModel ref = (RefModel) m;
                                interfaces.add(ref);
                            }
                        }
```
The above line 822 incorrectly assumes that the last component is always an anonymous local type defining the owned properties of the current type definition. If the definition in question only composes super-types by reference but declares no owned properties, model.child will incorrectly be set to the last allOf **super** type!

Similarly, line 825 incorrectly excludes the last composed super type, based on the same erroneous assumption that it must necessarily be a local definition. Again, if the definition in question merely composes other definitions by reference, the last such definition needs to be included in the interfaces list.

In fact, since `allOf` can apparently include a local child definition at **any** list index, shouldn't the above code also be amended to handle this case?

**Comment by fehguy** [comment]
Can you please add a test case for this so it can be handled?

**Comment by demonfiddler** [comment]
Sure @fehguy, will do. In fact, since this is urgent for us I'm working on a fix - would you entertain a PR?

**Comment by fehguy** [comment]
yes of course!

**Comment by anshumandas** [comment]
Relevant to issue https://github.com/swagger-api/swagger-parser/issues/141

**Comment by demonfiddler** [comment]
I have a fix and test case prepared, just awaiting consent from our Legal department before submitting a PR.

**Comment by fehguy** [comment]
Fixed by https://github.com/swagger-api/swagger-parser/commit/6b3cf711f7e4a43eddf6ee195d463e295903cd4c
