### ISSUE TITLE
Question: is it possible to modify a source OpenAPI spec through the parser?

### ISSUE THREAD

**Issue by madediosg** [swagger-api/swagger-parser#2053]
Hello,

I am interesting to know if, using the parser, it could be possible to:
1. Pass one (or more) OpenAPI (v2 in my case) specs to the parser, and parse them to the parser core model.
2. Modify the core model generated from (1). For example, extending the model by including vendor extensions.
3. Generate back the OpenAPI specs provided in (1), but including the modifications done in (2).

Thanks in advance.

**Comment by frantuma** [comment]
Swagger Parser provides deserialization with validation and optional dereference/bundling (e.g. dereferencing external references  and including them into the result). The result is a `Swagger` or `OpenAPI` POJO (what you refer to as "core model") with related APIS (e.g. getters and setters and fluid interfaces to add/modify vendor extensions. This POJO is provided by [Swagger Core](https://github.com/swagger-api/swagger-core). If you don't need validation or dereference all the 3 tasks above can be provided by Swagger Core. Your point 3 is a matter to call `JSON.pretty()` passing the modified pojo.

Please close the ticket if this answers your question

**Comment by madediosg** [comment]
Thanks a lot for clarifying.
I close the issue, 😄.
