### ISSUE TITLE
Resolver / OperationProcessor 

### ISSUE THREAD

**Issue by OliverSanftleben** [swagger-api/swagger-parser#207]
Hello,

why are RefResponses resolved but not normal Responses with references in items of array schemas?

f.e.

```json
"responses":{

    "200":{

        "description":"successful operation",

        "schema":{

            "type":"array",

            "items":{

                "$ref":"#/definitions/Pet"

            }

        }

    }

}
```

will not be resolved.

Best Regards
Oliver Sanftleben

**Comment by OliverSanftleben** [comment]
Ok, I see the real work is done in ResponseProcessor and PropertyProcessor.

But why are in processRefProperty only external reference formats resolved?

**Comment by fehguy** [comment]
I don't know what you mean.  Please post a complete example and I'm happy to look into it.

**Comment by OliverSanftleben** [comment]
Maybe you can try to resolve the example above with new SwaggerResolver(swagger, null).resolve() (it's taken from http://petstore.swagger.io/);

The RefProperty in items will not be resolved...

**Comment by fehguy** [comment]
OK so please see tests added here:

https://github.com/swagger-api/swagger-parser/pull/218/commits/9c7d6547f993bd747812eda87fed2a55dbf29ce1

Unless I'm misunderstanding your concern, the resolver works just fine with your example.
