### ISSUE TITLE
vendor extensions not deserialized with composedModel

### ISSUE THREAD

**Issue by antyriad** [swagger-api/swagger-parser#208]
vendor extension, in following definitions, is not deserialized:

    "Dog" : {
      "title" : "Dog",
      "type" : "object",
      "allOf" : [ {
        "$ref" : "#/definitions/Pet"
      }],
      "x-color" : "red"
    }

I think this is a problem in ComposedModel deserialization because following definition works:

    "Dog" : {
      "title" : "Dog",
      "type" : "object",
      "properties" : {
        "name" : "medor"
      },
      "x-color" : "red"
    }

**Comment by fehguy** [comment]
@webron is this valid?  The parser can be updated to support it.
