### ISSUE TITLE
Properties in ComposedModel

### ISSUE THREAD

**Issue by beikov** [swagger-api/swagger-parser#2083]
[The Azure OpenAPI specification](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2024-03-01/virtualMachine.json#L3321) uses "properties" in definitions that also have `allOf` i.e. are a `ComposedModel`.

I don't know if this is valid or not, but Swagger should support parsing this.

**Comment by frantuma** [comment]
fixed by #2084

**Comment by beikov** [comment]
Awesome, thanks so much @frantuma! I don't want to rush you, but do you have a release planned soon? I'd like to get past my SNAPSHOT dependency :)

**Comment by frantuma** [comment]
@beikov released 1.0.71

**Comment by beikov** [comment]
Thank you so much!
