### ISSUE TITLE
Replace system.out.println with SLF4J

### ISSUE THREAD

**Issue by RobWin** [swagger-api/swagger-parser#209]
Hi,
is there any reason why the swagger-parser does not use a Logger like SLF4J but instead uses system.out.println? I can create a PR if there is none.

**Comment by garydgregory** [comment]
Or Log4j 2.

**Comment by RobWin** [comment]
Thats the Impl. I talk about the API. You can then use logback, log4j or whatever you like as the client of swagger-parser.

**Comment by fehguy** [comment]
I'd be happy to move all logging to use a proper logger.

**Comment by garydgregory** [comment]
No it is not. Log4j 2 is an API as well, with implementations for other logging frameworks, including its own.

**Comment by rgoers** [comment]
Logback chose to publish its API as one open source project (SLF4J) and the impl as another.  Log4j 2 simply separates the API as one jar and the impl as another. You can use the Log4j 2 API only and route logging events to SLF4J if you want. Log4j 2's API happens to have many more features than SLF4J.

**Comment by RobWin** [comment]
Sry. Wasn't aware of that.

**Comment by webron** [comment]
We should stick with SLF4J as that's the facade we use for the other project. Unless, of course, you want to change it in all the projects. ;)

**Comment by RobWin** [comment]
There is already a PR which implemented it and can be merged.
https://github.com/swagger-api/swagger-parser/pull/181

**Comment by ceki** [comment]
SLF4J was created to **preserve** log4j from failures observed when using log4j+commons-logging combination under Tomcat. I wrote two lengthy articles on the subject with the titles [Think again before adopting the commons-logging API](http://articles.qos.ch/thinkAgain.html) and [Taxonomy of class loader problems encountered when using Jakarta Commons Logging](http://articles.qos.ch/classloader.html)

The current success of SLF4J which was far from certain at the time, made log4j viable as a logging framework people could reliably use under Tomcat. As the founder of the log4j project, and VP Apache Logging Services for over 5 years, having spent countless hours maintaining log4j, I take objection to R. Goers revisionist claims. When he asserts that logback chose to publish its API in a separate project, he is being disingenuous at best. Given that R. Goers has illegally copied the [logback manual in log4j2](http://tinyurl.com/rev-1479072) (note the copy-paste where he forgot to replace logback by log4j2) I am no longer shocked by his intrigues. In a less forgiving context, he would be sued for copyright infringement.

By the way, I apologize for the digression and assure you that it is a one-time event not to be repeated.

**Comment by rgoers** [comment]
Wow. We certainly didn't mean to hijack this issue or disparage SLF4J, Logback or Ceki in any way. All we were trying to point out is that Log4j 2 has an API and an implementation.

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-parser/issues/214
