### ISSUE TITLE
Relative refs inside of a ref'd section have the wrong context.

### ISSUE THREAD

**Issue by nicksloan** [swagger-api/swagger-parser#213]
Observed when running `swagger-codegen generate -l typescript-node -o SDK -i index.yaml` against [this source](/communityelf/UpContent-API-Spec).

I've created two branches with minimal examples. The only relevant files for these branches are `index.yaml`, `path/infomous.yaml` and `definitions/error.yaml`.

The [testforron branch](/communityelf/UpContent-API-Spec/tree/testforron) demonstrates the breakage on what I believe to be the correct syntax/path for the ref in `path/infomous.yaml`. 

The [testforron2 branch](/communityelf/UpContent-API-Spec/tree/testforron2) demonstrates that the ref is working in `path/infomous.yaml`. In this case, the path is being resolved as if it were from the root, not from the path subdirectory.

This may be related to an [issue reported on swagger-codegen](/swagger-api/swagger-codegen/issues/1551).

**Comment by crankydillo** [comment]
@nicksloan Did this resolve things for you?  I'm working with a spec and referenced schemas that live on a file system, and the master branch still appears to suffer from the same problem you describe here.  I can try to craft a failing test; however, if this works for you and you're using a file system as opposed to hosting these files, I'm pretty sure I must be misunderstanding something.

**Comment by crankydillo** [comment]
@fehguy Can you verify this fix is supposed to work for specs on the filesystem?  If so, isn't [this test data](../tree/master/modules/swagger-parser/src/test/resources/relative-file-references/json/paths/healthPath.json#L4) problematic?  IMO, it should be:

```code
"$ref": "../paramaters/params.json#/param1"
```

As an aside, I hope to help some.  Just have to convince the powers that be!

**Comment by saguinav** [comment]
@crankydillo I think you are right. That reference points to a folder that doesn't exist at that level, but one above (inside `json` directory).
