### ISSUE TITLE
io.swagger.models.Model - "type" attribute - getter

### ISSUE THREAD

**Issue by pakkk** [swagger-api/swagger-parser#233]
Hello,

I was wondering if you could add a new interface method getType in the class "io.swagger.models.Model" for the attribute "type", because I would want to parse the value of this attribute with my application.

Nowadays, the only way to get the value is using "casting" over the ModelImpl class and I think it is not a good idea.

Thank you :)

Regards,
Paco.

**Comment by fehguy** [comment]
There will be an overhaul of the pojos shortly.  Please consider opening an issue in swagger-core.
