### ISSUE TITLE
JSON Schema property type does not support multiple types

### ISSUE THREAD

**Issue by ebelanger** [swagger-api/swagger-parser#236]
[](http://json-schema.org/latest/json-schema-validation.html#anchor79)

According to the JSON Schema Spec, which in this case is also a valid Swagger Spec, it is possible to define multiple types for a property by setting the type property to an array containing strings.  This is especially useful for properties that support the null value, which is not the same as being a required property.

Are there any plans to support this case?

**Comment by fehguy** [comment]
We don't support 100% of JSON schema.  I suggest you please look at the [Open API specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) (FKA Swagger specification) for details.  If you feel strongly about a lack of feature in the spec, please add an issue there.

But per the spec, it's intentionally not supported.

**Comment by ebelanger** [comment]
I just read the specification and it is clearly mentionned that the type property is supported.

> Further information about the properties can be found in JSON Schema Core and JSON Schema Validation. Unless stated otherwise, the property definitions follow the JSON Schema specification as referenced here.

> The following properties are taken directly from the JSON Schema definition and follow the same specifications:

> type

The other thing is that swaggerhub actually parses this correctly just like the spec mentionned.

I would appreciate if you could put more attention to this issue.

Thank you

**Comment by webron** [comment]
@ebelanger - you're right about the documentation problem, it is indeed not clear that schema objects don't support multiple types (which is not supported anywhere else in the spec where `type` is used). 

There's a ticket about it [here](https://github.com/OAI/OpenAPI-Specification/issues/458), feel free to subscribe to it for updates.
