### ISSUE TITLE
Silent failure on malformed yaml

### ISSUE THREAD

**Issue by pierods** [swagger-api/swagger-parser#238]
Parser fails silently on malformed yaml.

Code in question is:
Swagger20Parser.java, line 98: exception is silently swallowed

        } catch (Exception e) {
            if (System.getProperty("debugParser") != null) {
                e.printStackTrace();
            }

I find it quite unbelievable...

**Comment by fehguy** [comment]
In the current extensions implementation, returning a "null" spec would signify the inability to process a definition (YAML in your bug report).  This would allow another extension to try.

Agreeing that it's not elegant, this is being changed in 1.1.x.
