### ISSUE TITLE
Reading Properties of ComposedModel

### ISSUE THREAD

**Issue by ArulPrakas** [swagger-api/swagger-parser#240]
getProperties() of ComposedModel always returns null. Is there any way to read the properties of a ComposedModel object?

**Comment by fehguy** [comment]
A composed model doesn't have properties, it has models which compose it

**Comment by ArulPrakas** [comment]
Ex:
"Dog": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Pet"
        },
        {
          "$ref": "#/definitions/Furry"
        },
        {
          "properties": {
            "propInt": {
              "type": "string"
            }
          }
        }
      ],
      "properties": {
        "propEx": {
          "type": "string"
        }
      }
    }

Above defn is a valid one by swagger spec. Swagger parser is able to deserialize models defined inside allOf BUT not the properties defined outside.

**Comment by fehguy** [comment]
Try adding "type: object" to the inline object

**Comment by ArulPrakas** [comment]
Didnt get you!. Issue is with reading of "propEx" (in above sample) which already has "type:object". 

Can you please elaborate?

**Comment by fehguy** [comment]
OK two things.  To my first comment, you can *not* have properties as a sibling to the `allOf` model.  Next, my suggestion was for the inline object, where you have `propInt` defined.

So you should change your definition to be something like this:

```json
{
  "type": "object",
  "allOf": [
    {
      "$ref": "#/definitions/Pet"
    },
    {
      "$ref": "#/definitions/Furry"
    },
    {
      "type": "object",
      "properties": {
        "propInt": {
          "type": "string"
        }
      }
    },
    {
      "type": "object",
      "properties": {
        "propEx": {
          "type": "string"
        }
      }
    }
  ]
}
```

The location of your `properties` makes no sense.  See this test for deserialization behavior:

https://github.com/swagger-api/swagger-core/blob/d98de9c8a69b569a2bf90906fe6c3faf0df4464c/modules/swagger-core/src/test/java/io/swagger/models/ComposedModelTest.java
