### ISSUE TITLE
Support model references directly to primitives

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-parser#243]
A model like this:

```yaml
swagger: '2.0'
definitions:
  User:
    $ref: 'BaseUser'
  BaseUser:
    type: string
```

Is legal but currently not supported in the parser.

**Comment by fehguy** [comment]
Also affects https://github.com/swagger-api/swagger-codegen/issues/2314

**Comment by webron** [comment]
Did you mean the following?

```yaml
swagger: '2.0'
definitions:
  User:
    $ref: '#/definitions/BaseUser'
  BaseUser:
    type: string
```

**Comment by fehguy** [comment]
This has been implemented

**Comment by sreeshas** [comment]
@fehguy  Do you have more details on implementation? Is there a PR which we can refer?

**Comment by jimvmathews** [comment]
@fehguy - Can you point us to the PR or test that has fixed this issue? I have pulled this latest version into the swagger-codegen and the problem https://github.com/swagger-api/swagger-codegen/issues/3483 is not resolved.

**Comment by robsdudeson** [comment]
Would be interested in details as well.  I'm seeing the same issue on master.

**Comment by fehguy** [comment]
see https://github.com/swagger-api/swagger-parser/pull/426/commits/5e98486315a195514b38558ee76c6e4d2bb18858

**Comment by jbx1** [comment]
While direct references to primitives are supported, none of the validation specifiers associated with it are carried over.

For example: 
```
      email:
        type: string
        pattern: '^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$'
        description: Email address of the customer.
     mobile:
        $ref: '#/definitions/Mobile'
```

with the definition:

```
 Mobile:
    type: string
    pattern: '^\\+[1-9][0-9]{3,14}$'
    description: The mobile number in E.164 format.
```

Using `swagger-codegen` version 2.3.1 for spring-boot generates the right validation annotations and javadoc for email:

```
  /**
   * Email address of the customer.
   * @return email
  **/
  @ApiModelProperty(value = "Email address of the customer.")
@Pattern(regexp="^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$") 
  public String getEmail() {
    return email;
  }

```

But not for the `mobile` property:

```
/**
   * Get mobile
   * @return mobile
  **/
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getMobile() {
    return mobile;
  }
```
