### ISSUE TITLE
Json parsing errors are not reported in the SwaggerDeserializationResult returned with readWithInfo

### ISSUE THREAD

**Issue by pablograna** [swagger-api/swagger-parser#250]
All json parsing errors are in SwaggerParser.readWithInfo(String) are converted to a single message: "malformed or unreadable swagger supplied".

Also, when using the readWithInfo(String location, ...) operation, returns a single string "unable to read location `" + location + "`", and looses all the error information from the Jackson exception.

I'll submit a PR soon ...

**Comment by pablograna** [comment]
I submitted PR https://github.com/swagger-api/swagger-parser/pull/251

One thing I noticed is the 'assimetry' between readWithInfo(String) and readWithInfo(String location,  ...): the first one tries with the parser and the second one also tries with all the extensions.

**Comment by pablograna** [comment]
This is partially fixed in PR #252. I'll open a new PR to support the same behavior when parsing a string.

**Comment by pablograna** [comment]
Added PR #253 that adds the same behavior to parseContent.

**Comment by pablograna** [comment]
Guys, I'd like to discuss something related to these PRs. There are two things I found strange in swagger parser (It may be because I don't understand the reason):

1- It looks like SwaggerParserExtension has too many operations. If I understand correctly, the operation:
     SwaggerDeserializationResult parseContents(JsonNode node, List<AuthorizationValue> auth, String parentLocation, boolean resolve) throws UnparseableContentException;

looks enough. All other could be implemented by generating a JsonNode from various sources, a responsibility that can be assigned to SwaggerParser. That would make life easier for extension writers.

2- Swagger20Parser is an extension, so it is loaded as a Service in SwaggerParser. But it is treated as a special case: it is manually created and invoked, and then invoked again as an extension if it throws an exception (ie: Swagger20Parser is called twice if it throws an exception).

**Comment by pablograna** [comment]
Please, look at #254 for a PR that addresses both things I mentioned in my previous comment. If that PR is accepted, then #253 is irrelevant.

**Comment by fehguy** [comment]
PRs merged
