### ISSUE TITLE
Examples parsing using arrays

### ISSUE THREAD

**Issue by Kabhal** [swagger-api/swagger-parser#255]
Hi,

When using definitions of type object's array, it seems examples are not correctly handled :

```
{
  "info": {
    "title": "foo"
  },
  "swagger": "2.0",
  "paths": {
    "/bar": {
      "patch": {
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SamplePayload"
            }
          }
        ]
      }
    }
  },
  "definitions": {
    "SamplePayload": {
      "type": "array",
      "items": {
        "type": "object",
        "example": {
          "op": "replace",
          "path": "/s",
          "v": "w"
        }
      },
      "example": [
        {
          "op": "replace",
          "path": "/s",
          "v": "w"
        }
      ]
    }
}
```

After parsing, SamplePayload ArrayModel object equals :

![debug](https://cloud.githubusercontent.com/assets/6772693/15924436/4ea1285e-2e32-11e6-926a-7eac7badb2e7.png)

Notice both :
* ArrayModel::example == ""
* ArrayModel::items::example == null

version used : swagger-parser:1.0.18

**Comment by Kabhal** [comment]
thanks, now a value is returned, however the example is returned as a string.
To be consistent with the object's examples, which are returned as json parser's ObjectNode, I guess the example should be returned as an ArrayNode type.

**Comment by fehguy** [comment]
Yes, that's currently how the examples are done right now.  I will open a new issue to make sure this is supported, I need to ensure it's not going to break anything in the process, which is why I changed it to keep as string.

**Comment by ajaykmr2292** [comment]
Hey, I started using swagger parser. But I am not able to get the schema of the body parameter from the swagger(no method called getSchema() in the Parameter Class). So, just want to know how to get the schema from a parameter? The swagger mentioned above is an example for a body parameter having a schema.
