### ISSUE TITLE
Parser removes enum discriminator property

### ISSUE THREAD

**Issue by diegode** [swagger-api/swagger-parser#263]
You can reproduce this bug by adding this test to `SwaggerDeserializerTest`:

    @Test
    public void testDeserializeWithEnumDiscriminator() {
        String yaml =
                "swagger: '2.0'\n" +
                        "definitions: \n" +
                        "  Animal:\n" +
                        "    type: object\n" +
                        "    discriminator: petType\n" +
                        "    description: |\n" +
                        "      A basic `Animal` object which can extend to other animal types.\n" +
                        "    required:\n" +
                        "      - commonName\n" +
                        "      - petType\n" +
                        "    properties:\n" +
                        "      commonName:\n" +
                        "        description: the household name of the animal\n" +
                        "        type: string\n" +
                        "      petType:\n" +
                        "        description: |\n" +
                        "          The discriminator for the animal type.  It _must_\n" +
                        "          match one of the concrete schemas by name (i.e. `Cat`)\n" +
                        "          for proper deserialization\n" +
                        "        enum:\n" +
                        "        - cat\n" +
                        "        - dog";

        SwaggerParser parser = new SwaggerParser();
        SwaggerDeserializationResult result = parser.readWithInfo(yaml);
        Map<String, Property> properties = result.getSwagger().getDefinitions().get("Animal").getProperties();
        assertTrue(properties.containsKey("commonName"));
        assertTrue(properties.containsKey("petType"));
    }

**Comment by fehguy** [comment]
Thank you--could you please send a PR with this test and we'll get it implemented?

**Comment by diegode** [comment]
Done :)

**Comment by diegode** [comment]
As a workaround, adding "type: string" to the petType property fixes it.

**Comment by diegode** [comment]
Wow: using the last stable release of swagger-codegen I can't just add "type: string" since it breaks the javascript code generation (I reported this issue here: https://github.com/swagger-api/swagger-codegen/issues/3143).
:(

**Comment by fehguy** [comment]
So, I don't think inferring the type based on the `enum` values is a wise thing to do.  But I have added code to support this, it will fallback to `string` if the enum values are not compatible.

**Comment by diegode** [comment]
Thanks @fehguy!
The swagger specification is even more relaxed: it permits that each item in an enum has a different type. In http://swagger.io/specification/ it says:

> The following properties are taken directly from the JSON Schema definition and follow the same specifications:
- ...
- enum
> 
So we should look what JSON schema permits. In https://spacetelescope.github.io/understanding-json-schema/reference/generic.html#enumerated-values it says:

> You can use enum even without a type, to accept values of different types.

And it even gives examples of that.
