### ISSUE TITLE
External recursive refs aren't being resolved

### ISSUE THREAD

**Issue by diegode** [swagger-api/swagger-parser#278]
This test is failing in master (the last assertion):

    @Test
    public void testLoadRecursiveExternalDef() throws Exception {
        SwaggerParser parser = new SwaggerParser();
        final Swagger swagger = parser.read("src/test/resources/file-reference-to-recursive-defs/b.yaml");
        Map<String, Model> definitions = swagger.getDefinitions();
        assertEquals(((RefProperty) ((ArrayProperty) definitions.get("v").getProperties().get("children")).getItems()).get$ref(), "#/definitions/v");
        assertTrue(!definitions.containsKey("y"));
        assertEquals(((RefProperty) ((ArrayProperty) definitions.get("x").getProperties().get("children")).getItems()).get$ref(), "#/definitions/x");
    }

where a.yaml is:

    ---
    swagger: "2.0"
    info:
      title: test
      version: '0.0.0'
    paths: {}
    definitions:
      y:
        type: object
        properties:
          name:
            type: string
          children:
            type: array
            items:
              $ref: "#/definitions/y"

and b.yaml is:

    ---
    swagger: "2.0"
    info:
      title: test
      version: '0.0.0'
    paths: {}
    definitions:
      x:
        $ref: "./a.yaml#/definitions/y"
      v:
        type: object
        properties:
          name:
            type: string
          children:
            type: array
            items:
              $ref: "#/definitions/v"

**Comment by fehguy** [comment]
This has been fixed

**Comment by diegode** [comment]
@fehguy please re-enable the test from my PR (https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java#L226)
