### ISSUE TITLE
Handling lists without inner type

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-parser#28]
for the compat parser:

1) Anytime we see “type": “List” it should transform it to “type”: “array”.  I’ve seen them appear in the following places:
  + responseModel

```js
"responseMessages": [
  {
    "code": 200,
    "message": "OK",
    "responseModel": "List"
  }
```

  + parameters
```js
{
  "allowMultiple": false,
  "defaultValue": "",
  "description": "reprice",
  "name": "body",
  "paramType": "body",
  "type": "List",
  "required": false
}
```
  + model properties
```js
"repriceItems": {
  "items": {
    "type": "RepriceItem"
  },
  "required": false,
  "type": "List"
},
```
2) When we see “type”: “List” OR “type”: “array” AND we don’t have an “items” key, I’d like to automatically add this:
```js
“items”: {
  “type”: “object”
}
```

**Comment by fge** [comment]
Would it be possible to add a set of test files failing to transform as expected?
