### ISSUE TITLE
allowEmptyValue Not Parsed

### ISSUE THREAD

**Issue by soaro77** [swagger-api/swagger-parser#290]
When using SwaggerParser to parse a Swagger file containing a parameter with allowEmptyValue, the allowEmptyValue is not parsed and included in the Swagger variable. This can be tested with the following placed in a unit test. Then inspect the swagger variable and the allowEmptyValue is not there.

Swagger swagger = new SwaggerParser().read("jsonOrYamlSwaggerFile");

**Comment by fehguy** [comment]
Track here: https://github.com/swagger-api/swagger-core/issues/1979

**Comment by fehguy** [comment]
Fixed in #364
