### ISSUE TITLE
swagger-parser does not parse the collectionFormat of query parameters if it is defined before the type

### ISSUE THREAD

**Issue by michaelkourlas** [swagger-api/swagger-parser#291]
When swagger-parser parses the following spec, it thinks that the testParam query parameter has a collectionFormat of "multi", even though it is explicitly defined as having a collectionFormat of "csv":

```json
{
  "swagger": "2.0",
  "info": {
    "title": "test spec",
    "version": "1.0"
  },
  "parameters": {
    "testParam": {
      "collectionFormat": "csv",
      "name": "test",
      "in": "query",
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "paths": {
    "/test": {
      "get": {
        "description": "test get",
        "parameters": [
          {
            "$ref": "#/parameters/testParam"
          }
        ],
        "responses": {
          "default": {
             "description": "test response"
          }
        }
      }
    }
  }
}
```
It correctly parses the collectionFormat if it is defined *after* the type, like so:

```json
"testParam": {
  "name": "test",
  "in": "query",
  "type": "array",
  "collectionFormat": "csv",
  "items": {
    "type": "string"
}
```
The ordering of JSON properties is irrelevant, so this is definitely a bug.

**Comment by fehguy** [comment]
Got it, thanks for reporting.  Looks like the parsing of parameters at the top-level is taking a different path than inside an operation.

**Comment by fehguy** [comment]
ok @michaelkourlas I see what was going on.  The issue was _only_ when parameters were shared from the top-level, the code took a different path.  This was fixed in https://github.com/swagger-api/swagger-parser/commit/ac8b4e5295ceb1adef04b03e47d9e179c1da7a1a

My test cases here didn't hit that path, but the above commit should ensure it does the right thing.
