### ISSUE TITLE
swagger-parser uses incorrect default for collectionFormat in query parameters

### ISSUE THREAD

**Issue by michaelkourlas** [swagger-api/swagger-parser#292]
**Summary**

swagger-parser incorrectly assigns a collectionFormat of "multi" to query parameters with no explicitly defined collectionFormat when parsing a spec, even though the correct default is "csv".

**Details**

I was using swagger-codegen to generate a Java API library from an API specification file. swagger-codegen uses swagger-parser to parse the API specification file. The API specification that I am using defines a particular query parameter that looks something like this:

```json
"testParam": {
  "name": "testParam",
  "in": "query",
  "type": "array",
  "items": {
    "type": "string"
  }
}
```
As you can see, the parameter is of type "array" but has no explicitly defined collectionFormat. The authors of the API specification relied on the default behaviour being "csv", as defined in the Swagger specification.

However, when swagger-parser parsed this API specification, it returned a parameter object with a collectionFormat of "multi", which caused problems with the generated Java API.

I believe this is an issue with swagger-core, so I have opened [an issue](https://github.com/swagger-api/swagger-core/issues/1893) there. However, @webron asked me to open an issue here as well.

**Comment by fehguy** [comment]
Well, I have written some tests to see if the parser will do what is described.  Doesn't look like it is so, and the issue must be in swagger-core.
