### ISSUE TITLE
Error with readOnly and vendorExtensions when parsing properties

### ISSUE THREAD

**Issue by fiore-adrian** [swagger-api/swagger-parser#301]
I found that in same cases the swagger parser don't recognize the readOnly property, or the vendorExtensions.

I generate the next pull request:
https://github.com/swagger-api/swagger-parser/pull/300

It has tests for the bugs (readOnly in array property is ignored and vendorExtensions in ref property are ignored too).
It also has a possible solution for these problems.

Regards,
Adrian

**Comment by fehguy** [comment]
Hi, I commented on the PR, this scenario is illegal.  `$ref` properties are forbidden to have siblings per JSON schema, so it's intentionally not supported in the parser.

**Comment by diegode** [comment]
@fehguy I agree. But the readOnly bug is real. @fiore-adrian can you create a new PR with the fix for that only?

**Comment by fehguy** [comment]
thanks, that'd be great.
