### ISSUE TITLE
Problems with references from external file to external or main file

### ISSUE THREAD

**Issue by Furion137** [swagger-api/swagger-parser#304]
We have several POJO's we'd like to generate from yml/json using swagger-codegen. POJO's has modular structure and modules has dependencies between them. So we'd like to keep them in several json files and have "Parent" module absolutely independent, "Child1" module depending on "Parent", "Child2" depending on "Parent", "Grandchild1.1" depending on "Child1", etc. So we need inheritance and composition.
So for codegen it looks like swagger.yml with definition block filled with links to parent.json, child1.json, etc. The problem is that currently all the refs e.g. from "Child1" "./swagger.yml/#/definitions/BaseEntityDto" I've tried to use for inheritance are just ignored. And for composition it creates something like "SwaggerYmldefinitionsAddressTypeDto". Could you please take a look?

**Comment by fehguy** [comment]
More details, please.  It's really not possible to help without a sample spec

**Comment by fehguy** [comment]
This should be fixed in the _parser_ now.  I'll ensure the codegen gets a reference to the snapshot here.

**Comment by Furion137** [comment]
Thanks a lot. Hope to try it as soon as I finish with my current task.

**Comment by Furion137** [comment]
Now I get "Exception in thread "main" java.lang.RuntimeException: Unable to load RELATIVE ref: ./child.json/swagger.json" trying to generate from example above. Looks like it's trying to find one file into another and I haven't found a way to workaround it. So in _swagger.json_ we have a link to _child.json_ where we have a link back to _swagger.json_ and it's not workings. Same if I try to link _swagger.json_->_child.json_->_parent.json_ ("Exception in thread "main" java.lang.RuntimeException: Unable to load RELATIVE ref: ./child.json/parent.json"). Could you please take a look?

**Comment by webron** [comment]
URIs/URLs can be a pain. Try using `../swagger.json` and `../child.json` and so on. When referencing the same doc, prefer `#` over actually using the filename.

**Comment by Furion137** [comment]
Have tried. Exception in thread "main" java.lang.RuntimeException: Unable to load RELATIVE ref: ../parent.json. Gonna check further tomorrow.

**Comment by Furion137** [comment]
No, ../parent.json is not working for me.
Regarding using just # for referencing inside the file I fully agree. I used the part below just to show another small issue.
"ReferenceToTheSameFile": {
      "$ref": "./swagger.json/#/definitions/InheritanceAndCompositionDto"
    }"

**Comment by fehguy** [comment]
@Furion137 please ensure you're testing _master_.  There are numerous tests to verify this working now

**Comment by Furion137** [comment]
@fehguy Have rechecked, I've been using the latest version from master. Does the example above work for you?

**Comment by fehguy** [comment]
@Furion137 I will add a test right now and report back

**Comment by Furion137** [comment]
@fehguy thanks a lot!

**Comment by fehguy** [comment]
Yes, looks like a bug--working on it, but you do have some circular references that may not be possible to use.  I'll know more in a few.

**Comment by Furion137** [comment]
@fehguy thanks a lot!

**Comment by fehguy** [comment]
OK in your `swagger.json` note that your reference patterns look like this:

```
"$ref": "./parent.json/#/definitions/BaseEntity"
```

You have an extra slash after the `parent.json` in the above example (same is true for all of them).  Please change to this:

```
"$ref": "./parent.json#/definitions/BaseEntity"
```

and it works fine.  Can you please retest and confirm?

**Comment by Furion137** [comment]
Thanks a lot! Looks like this way it works. Trying to rewrite our code this way.
