### ISSUE TITLE
duplicate refs not parsing correctly

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-parser#340]
Reported by @jaz-ah, when there are references inside a root swagger, they may resolve incorrectly

**Comment by fehguy** [comment]
Well, looks like we explicitly don't overwrite models that exist:

https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java#L48-L55

**Comment by jaz-ah** [comment]
hmm... but why does it still produce an erroneous model - i.e. could it just toss out the duplicate one?

**Comment by fehguy** [comment]
Yes, I'm looking to add logic to decide _which_ to keep.  Stay tuned...

**Comment by jaz-ah** [comment]
just tell the code to keep the best one :)
