### ISSUE TITLE
$ref in additionalProperties in external yaml ignored

### ISSUE THREAD

**Issue by rakus** [swagger-api/swagger-parser#342]
Initially opened against swagger codegen as [#4135](https://github.com/swagger-api/swagger-codegen/issues/4135). They send me here.

It seems that swagger-parser cannot handle a $ref below `additionalProperties` in a external yaml file.

Example:

---
swagger.yaml
```yaml
swagger: "2.0"
info:
  title: Test API
  version: 1.0.0
host: swagger.io
basePath: /show-bug
schemes:
- http
produces:
- application/json
consumes:
- application/json

paths:
  /tests:
    get:
      operationId: listTests
      responses:
        200:
          description: Returns results.
          schema:
              $ref: "./globals.yaml#/definitions/result"
```

---
globals.yaml
```yaml
definitions:
  link-object:
    type: object
    additionalProperties:
      $ref: '#/definitions/rel-data'

  rel-data:
    type: object
    required:
      - href
    properties:
      href:
        type: string
      note:
        type: string

  result:
    type: object
    properties: 
      name:
        type: string
      _links:
        $ref: "#/definitions/link-object"
```

After parsing the object `rel-data` (`globals.yaml#/definitions/rel-data`) is missing.
The verbose output of swagger-codegen shows it:

```JSON
{
  "swagger" : "2.0",
  "info" : {
    "version" : "1.0.0",
    "title" : "Test API"
  },
  "host" : "swagger.io",
  "basePath" : "/show-bug",
  "schemes" : [ "http" ],
  "consumes" : [ "application/json" ],
  "produces" : [ "application/json" ],
  "paths" : {
    "/tests" : {
      "get" : {
        "operationId" : "listTests",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "Returns results.",
            "schema" : {
              "$ref" : "#/definitions/result"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "result" : {
      "type" : "object",
      "properties" : {
        "name" : {
          "type" : "string"
        },
        "_links" : {
          "$ref" : "#/definitions/link-object"
        }
      }
    },
    "link-object" : {
      "type" : "object",
      "additionalProperties" : {
        "$ref" : "#/definitions/rel-data"
      }
    }
  }
}
```

**Comment by fehguy** [comment]
This is not implemented

**Comment by jimschubert** [comment]
@fehguy When you say it's not implemented, is it that this is currently not implemented in YAML? IT looks like there are tests to cover this in JSON processing.

I ask because there's a related issue reported to swagger-codegen (swagger-api/swagger-codegen#5753).

**Comment by fehguy** [comment]
hmm.  As of december last year it wasn't implemented, and it shouldn't matter if it's JSON or YAML for how the parser works.  Where are the tests that you've seen?

**Comment by jimschubert** [comment]
@fehguy it looked like tests hitting [this file](https://github.com/swagger-api/swagger-parser/blob/v1.0.29/modules/swagger-parser/src/test/resources/relative-file-references/json/parent.json) should have covered it. Specifically [testLoadRelativeFileTree_Json](https://github.com/swagger-api/swagger-parser/blob/905c295764a0043e2abacc89735a25d7ddf7bb3e/modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java#L204) and [testLoadRelativeFileTree_Yaml](https://github.com/swagger-api/swagger-parser/blob/905c295764a0043e2abacc89735a25d7ddf7bb3e/modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java#L275) look like they'd cover JSON and YAML of this scenario, although I can't seem to find the yaml file referenced in that last test. Maybe the test is parsing JSON and passing? I didn't dig much deeper than that.

**Comment by fehguy** [comment]
thanks @jimschubert I'll get into this one shortly

**Comment by slarti-b** [comment]
We just ran up against this. Any news or updates? I also left a more detailed question on the linked codegen ticket - don't think that impacts here, but it may.

**Comment by webron** [comment]
Ugh, sorry, this got lost. We'll try to have a look at it soon.

**Comment by gracekarina** [comment]
Hi, Please check in branch 2.0, we merged a PR solving the issue. @slarti-b @jimschubert @rakus

**Comment by gracekarina** [comment]
Closing Issue, please report again if this keeps presenting
