### ISSUE TITLE
Problem with inheritance for multiple jsons

### ISSUE THREAD

**Issue by Furion137** [swagger-api/swagger-parser#345]
Java code generation works wrong for AddressDto from the example below. It creates line "import com.tskdata.supplier.business.supplier.dto.**ParentJsondefinitionsBaseEntityDto**" and doesn't create "extends BaseEntityDto". Could you please take a look?

swagger.json
```
{
  "swagger": "2.0",
  "info": {
    "title": "DTO types",
    "version": "1.1.0"
  },
  "paths": {
    "empty": null
  },
  "definitions": {
    "BaseEntityDto": {
      "$ref": "./parent.json#/definitions/BaseEntityDto"
    },
    "AddressDto": {
      "$ref": "./child.json#/definitions/AddressDto"
    }
  }
}
```

parent.json
```
{
  "definitions": {
    "BaseEntityDto": {
      "type": "object",
      "discriminator": "baseEntity",
      "properties": {
        "entityId": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  }
}
```

child.json
```
{
  "definitions": {
    "AddressDto": {
      "allOf": [
        {
          "$ref": "./parent.json#/definitions/BaseEntityDto"
        },
        {
          "type": "integer",
          "format": "int64"
        }
      ]
    }
  }
}
```

build.gradle

task generateDtos(type: JavaExec) {
    description 'Generate DTO source files'
    classpath configurations.swagger_codegen
    jvmArgs '-Dmodels'
    main 'io.swagger.codegen.SwaggerCodegen'
    args 'generate',
            '-i', file("schemas/public/swagger.json").canonicalPath,
            '-l', 'java',
            '-o', file("${buildDir}/generated-sources").canonicalPath,
            '--model-package', 'com.taskdata.supplier.business.supplier.dto',
            '-DserializableModel=true',
            '-DdateLibrary=java8',
            '--library', 'feign'
}

As a workaround we can replace in swagger.json 
```
"BaseEntityDto": {
      "$ref": "./parent.json#/definitions/BaseEntityDto"
    },
```
with
```
 "DumbClass": {
      "$ref": "./parent.json#/definitions/BaseEntityDto"
    },"
```
And all will work fine. But it doesn't look like an adequate solution for me.

**Comment by Furion137** [comment]
For me it looks related to the problem https://github.com/swagger-api/swagger-parser/issues/304.

**Comment by fehguy** [comment]
this has been tested to be working in #412.
