### ISSUE TITLE
Maven Central badge points to maven-central-project

### ISSUE THREAD

**Issue by andrerichards** [swagger-api/swagger-parser#347]
In the README.md the Maven Central badge points to `swagger-parser-project`:
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/io.swagger/swagger-parser-project/badge.svg?style=plastic)](https://maven-badges.herokuapp.com/maven-central/io.swagger/swagger-parser-project)

Should this be `swagger-parser` instead?
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/io.swagger/swagger-parser/badge.svg?style=plastic)](https://maven-badges.herokuapp.com/maven-central/io.swagger/swagger-parser) 

In the **Adding to your project** section it points to `swagger-parser`, but I did not read that far but added the ArtifactId `swagger-parser-project` from the maven central badge, which failed.

**Comment by fehguy** [comment]
Fixed by #348
