### ISSUE TITLE
ResolverCache.loadInternalRef poorly written

### ISSUE THREAD

**Issue by haroldcarr** [swagger-api/swagger-parser#349]
The existing code looks in parameters for #/definitions and then later looks in definitions if it hasn't found anything yet.  It works, but the logic is very poor.

Here is a potential replacement:

    private Object loadInternalRef(String ref) {

        if(ref.startsWith("#/definitions")) {
            return getFromMap(ref, swagger.getDefinitions(), DEFINITION_PATTERN);
        }
        if(ref.startsWith("#/responses")) {
            return getFromMap(ref, swagger.getResponses(), RESPONSE_PATTERN);
        }
        if(ref.startsWith("#/parameters")) {
            return getFromMap(ref, swagger.getParameters(), PARAMETER_PATTERN);
        }
        return null;
    }

**Comment by fehguy** [comment]
it could definitely be improved, could you send a PR?

**Comment by haroldcarr** [comment]
Will do.

**Comment by fehguy** [comment]
#351 has been merged.
