### ISSUE TITLE
resolved parameter and response references are null for unresolvable refs

### ISSUE THREAD

**Issue by haroldcarr** [swagger-api/swagger-parser#350]
When using SwaggerParser with `resolve==true` and parameters or responses contain references that can't be resolved
then the operations parameters list contains a `null` at those points.

It would be better if resolution did two things:

- add the location to unresolved references to the `messages`

- for both resolved and unresolved cases, have ParameterProcess.processParameters return some sort of "Reference" object with the original reference and either a null of the inlined reference when resolving, and a null when not resolving.

Use-case: using swagger-parser for semantic validation, e.g., :
- report the location and unresolved reference (that could be done by setting `resolve==true`, but see next)
- report multiple `body` parameters (that is easiest if the parameters are resolved)

**Comment by fehguy** [comment]
See #412 for tests around this.  Should be resolved, but please reopen if you see otherwise.
