### ISSUE TITLE
StringIndexOutOfBoundsException when reference is invalid string

### ISSUE THREAD

**Issue by haroldcarr** [swagger-api/swagger-parser#352]
The following "swagger" 

    {"definitions": { "BUG": { "$ref": "#/no" } } }

gets a StringIndexOutOfBoundsException because `GenericRef.computeSimpleRef` specific correct prefixes but the prefix may be longer than an invalid reference string.

Perhaps, for this case, just return the ref unchanged.

**Comment by gracekarina** [comment]
Hi @haroldcarr sorry for the late response, I have try to reproduce this issue but with no success, can you please provide a spec, or even better a PR with a failing test, so we can fix this?
Thanks!

**Comment by haroldcarr** [comment]
I no longer work on the project and do not have the test case.
