### ISSUE TITLE
URL for Nested Refs not Resolved

### ISSUE THREAD

**Issue by samanthacatania** [swagger-api/swagger-parser#355]
Imagine having a swagger file at http://api.com/spec/swagger.json. Within this swagger file there is a reference to a definition in ../common/Common.json and within Common.json there is a reference to a definition in ./Error.json.

Common.json gets resolved to http://api.com/common/Common.json which is correct. However Error.json gets resolved to http://api.com/spec/Error.json which is incorrect as Error.json is relative to Common.json not swagger.json.

**Comment by fehguy** [comment]
I just added tests in #412 to address this.  Please try again and reopen if you have an issue with the logic--nested refs seem to behaving nicely.
