### ISSUE TITLE
Custom Format is not parsed?

### ISSUE THREAD

**Issue by RobWin** [swagger-api/swagger-parser#37]
Hello, I use the swagger-parser in https://github.com/RobWin/swagger2markup.

I have added an emailAddr with format "email" to the Swagger Petstore example:

```
"Order": {
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "petId": {
                    "type": "integer",
                    "format": "int64"
                },
                "quantity": {
                    "type": "integer",
                    "format": "int32"
                },
                "shipDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "status": {
                    "type": "string",
                    "description": "Order Status"
                },
                "complete": {
                    "type": "boolean"
                },
                "emailAddr": {
                    "type": "string",
                    "format": "email"
                }
            }
```

And it seems that the official Swagger parser does not add the emailAddr to the Swagger model:

![image](https://cloud.githubusercontent.com/assets/5815046/7175767/81eefd7c-e418-11e4-936b-31405225e30a.png)

If I have a Model like:
```
"Order":{
 "properties": {
                "emailAddr": {
                    "type": "string",
                    "format": "email"
                }
            }
}
```

The properties Map is null:

![image](https://cloud.githubusercontent.com/assets/5815046/7175794/cf5db68e-e418-11e4-9c1c-315040ac8a35.png)

The JsonNode in the parser is correct:

![image](https://cloud.githubusercontent.com/assets/5815046/7176242/e2cbc25c-e41c-11e4-99ef-40cbb15d22f3.png)

The PropertyDeserializer can see the field correctly

![image](https://cloud.githubusercontent.com/assets/5815046/7177789/cc81ce94-e429-11e4-9a13-7df0038e61ed.png)

The problem is in the PropertyBuilder and there StringProperty.isType

```
  //TODO: implement additional formats
  public static boolean isType(String type, String format) {
    if("string".equals(type) && (format == null || "uri".equals(format) || "byte".equals(format)))
      return true;
    else return false;
  }
```

There should be some DefaultProperty which is used then, if it's a custom format.

Thanks in advance.
Robert

**Comment by fehguy** [comment]
Yes, currently the swagger models in [swagger-models](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties) are typed--they go through the [PropertyBuilder](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/PropertyBuilder.java) class.  Since there is no `EmailProperty` type, it doesn't hang on to the format.

We can get more formats supported in swagger core.  Can you please open a ticket there?

**Comment by RobWin** [comment]
Ok. done. 
swagger-api/swagger-core#993
