### ISSUE TITLE
Support for enums in QueryParameter, HeaderParameter and PathParameter.

### ISSUE THREAD

**Issue by RobWin** [swagger-api/swagger-parser#38]
I would like to have support for enums in QueryParameter, HeaderParameter and PathParameter.
Swagger Spec v2 allows enums in parameter objects.

I would like to render them in https://github.com/RobWin/swagger2markup

Thanks,
Robert

**Comment by fehguy** [comment]
I believe this is supported in the snapshot version.  Are you seeing otherwise?  Or is this for converting a 1.2 specification?

https://github.com/swagger-api/swagger-core/commit/d6c69fdeceb9082fd1c3c8b4afeef11720d87932

**Comment by RobWin** [comment]
Thx. I give it a try.

**Comment by RobWin** [comment]
Thx. Works with new snapshot version.
