### ISSUE TITLE
$ref does not work

### ISSUE THREAD

**Issue by zcb22000** [swagger-api/swagger-parser#388]
I used swagger-parser-1.0.25.jar which to parser my yaml file with yaml spec 2.0. But it doesn't parser the $ref content where resolved as empty. 
`Swagger swagger = new SwaggerParser().read("src/main/resources/yaml/index.yaml");`
My yaml file partition content is:
`paths:
  $ref: ./paths/index.yaml       
            
definitions:
  $ref: ./definitions/definitions.yaml`
The paths and definitions are empty in swagger Object which parsered but the $ref specified files are not empty.
Why?

**Comment by RobWin** [comment]
See my issue: https://github.com/swagger-api/swagger-parser/issues/346

**Comment by fehguy** [comment]
See here:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

That's not legal in the spec, and therefore not supported in the parser.

**Comment by zcb22000** [comment]
OK, Thanks
