### ISSUE TITLE
does it can generate sub package for deferent models by yaml file structure?

### ISSUE THREAD

**Issue by zcb22000** [swagger-api/swagger-parser#389]
does it can generate sub package for deferent models by yaml file structure?
My file struct:
index.yaml
path/SeviceA/pathA.yaml
path/SeviceB/pathB.yaml
definitions/SeviceA/domain/A.yaml
definitions/SeviceB/domain/A.yaml
How to generate class folders like this:
servicea
servicea.domain
serviceb
seviceb.domain

**Comment by fehguy** [comment]
Please read the specification for what you can externalize.
