### ISSUE TITLE
Support for parsing a String into the Swagger model.

### ISSUE THREAD

**Issue by RobWin** [swagger-api/swagger-parser#39]
Hello,

it would be great to have support for parsing a String (Swagger JSON/YAML) into the Swagger model without the need to store it in a file or retrieve it via an URL.

I would like to reuse the Json.mapper() and Yaml.mapper(), but don't want to have the internal knowledge of the Swagger parser in my code.

Kind regards,
Robert

**Comment by fehguy** [comment]
Can you explain more?  You mean you want to parse JSON into a model without using the swagger parser logic?

**Comment by RobWin** [comment]
No. I have a Swagger Json response as a String and want to parse it into the Swagger model without having to use Json.mapper and Yaml.mapper directly.

I would like to invoke
```
Swagger swagger = new SwaggerParser().parse(jsonAsString);
```

Kind regards,
Robert

**Comment by RobWin** [comment]
Something like

```
    public static SwaggerfromString(String swagger) throws IOException {
        Validate.notEmpty(swagger, "swagger must not be null!");
        ObjectMapper mapper;
        if(swagger.trim().startsWith("{")) {
            mapper = Json.mapper();
        }else {
            mapper = Yaml.mapper();
        }
        JsonNode rootNode = mapper.readTree(swagger);

        // must have swagger node set
        JsonNode swaggerNode = rootNode.get("swagger");
        if(swaggerNode == null)
            throw new IllegalArgumentException("Swagger String is in the wrong format");

        return new mapper.convertValue(rootNode, Swagger.class);
    }
```

**Comment by fehguy** [comment]
I see, yes, there can be a convenience function to allow a simple string be passed in.  What you put looks fine, would you like to send a pull request for it?

**Comment by RobWin** [comment]
Okidoki
