### ISSUE TITLE
swagger-parser treats relative refs without leading "." as internal refs

### ISSUE THREAD

**Issue by mkistler** [swagger-api/swagger-parser#410]
If the value of a $ref is a relative reference but does not start with ".", the swagger parser treats it as an internal ref.  E.g.
```
"$ref" : "./path/to/model.json#/thing"
```
is treated as a relative URI but 
```
"$ref": "path/to/model.json#/thing"
```
is treated as internal.

I did research the syntax of $ref -- starting from the Swagger 2.0 spec, then to the JSON Schema spec, ending in IETF RFC 3986 Uniform Resource Identifier (URI): Generic Syntax -- and as best I can tell, a relative reference *does not* need to start with "." to be considered a relative reference.

**Comment by mkistler** [comment]
Sorry ... this is really a problem in swagger-core ... closing this bug and will reopen in swagger-core.

**Comment by marcelstoer** [comment]
For the record here's the reference to the swagger-core issue: swagger-api/swagger-core#2138
