### ISSUE TITLE
3.0 support?

### ISSUE THREAD

**Issue by cfineman-sfdc** [swagger-api/swagger-parser#417]
Any thoughts about when 3.0 support will be added to the parser?

**Comment by fehguy** [comment]
Working on it, stay tuned.

**Comment by cfineman-sfdc** [comment]
Thanks. I know the spec has only been out a week... was curious.

**Comment by fehguy** [comment]
No problem at all.  You will see progress as soon as next week.

**Comment by fehguy** [comment]
See the [3.0.0-rc0 branch](https://github.com/swagger-api/swagger-parser/tree/feature/3.0.0-rc0) for WIP 3.0 support.  Feedback welcome

**Comment by yanniks** [comment]
Did anybody test the 3.0.0-rc2 branch in combination with Swagger Codegen?

**Comment by bhathiya** [comment]
Are there any updates on this? :)

**Comment by damozhiying** [comment]
swagger parse can't support swagger 3.0

**Comment by gracekarina** [comment]
Hi, please checkout branch 2.0 of parser.

**Comment by gracekarina** [comment]
please checkout master branch for 3.0 support.
