### ISSUE TITLE
SwaggerParser's read method doesn't honour 'resolve' parameter

### ISSUE THREAD

**Issue by leochr** [swagger-api/swagger-parser#431]
io.swagger.parser.SwaggerParser.read(String, List<AuthorizationValue>, boolean) method doesn't take the 'resolve' parameter into consideration and always resolves.

It's behaviour should be similar to that of io.swagger.parser.SwaggerParser.read(JsonNode, List<AuthorizationValue>, boolean).

**Comment by leochr** [comment]
I'll create a PR to fix this issue.

**Comment by gracekarina** [comment]
fixed by #438

**Comment by gracekarina** [comment]
thanks! @leochr
