### ISSUE TITLE
Some $ref values from external files are not updated with the processed internal reference values

### ISSUE THREAD

**Issue by leochr** [swagger-api/swagger-parser#434]
In some cases, the reference values coming from external files are not updated with the processed internal reference value.

The value returned by invoking io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(String, RefFormat) method should be set on the reference. It's done for one instance, but not for others.

                if (isAnExternalRefFormat(refModel.getRefFormat())) {
                    refModel.set$ref(processRefToExternalDefinition(refModel.get$ref(), refModel.getRefFormat()));
                } else {
                    **processRefToExternalDefinition(file + refModel.get$ref(), RefFormat.RELATIVE);**
                }

Above method invocation in bold should be 
refModel.set$ref(processRefToExternalDefinition(file + refModel.get$ref(), RefFormat.RELATIVE));

Similar behaviour in io.swagger.parser.processors.ExternalRefProcessor.processRefProperty(RefProperty, String) method. 

    private void processRefProperty(RefProperty subRef, String externalFile) {
        if (isAnExternalRefFormat(subRef.getRefFormat())) {
            String $ref = constructRef(subRef, externalFile);
            subRef.set$ref($ref);
            if($ref.startsWith("."))
                processRefToExternalDefinition($ref, RefFormat.RELATIVE);
            else {
                processRefToExternalDefinition($ref, RefFormat.URL);
            }

        } else {
            **processRefToExternalDefinition(externalFile + subRef.get$ref(), RefFormat.RELATIVE);**
        }
    }

Above method invocation in bold should be 
subRef.set$ref(processRefToExternalDefinition(externalFile + subRef.get$ref(), RefFormat.RELATIVE));

In above method, for external ref formats, the reference value is updated correctly because later on in DefinitionsProcessor the definitions are processed one by one. At that time the external RefProperty value will be replaced by internal value. But the same external reference values is processed twice unnecessarily by processRefToExternalDefinition. Setting the internal value returned by processRefToExternalDefinition on the RefProperty the first time should avoid this and doing so would keep the behaviour consistent with the other invocations of processRefToExternalDefinition.

**Comment by leochr** [comment]
I am able to demonstrate this problem by slight modifications to existing test cases. I'll create a PR to fix this issue and will include the test cases as well.

**Comment by gracekarina** [comment]
fixed by #864
