### ISSUE TITLE
Relative reference can also start with "/"

### ISSUE THREAD

**Issue by leochr** [swagger-api/swagger-parser#435]
In io.swagger.parser.processors.ExternalRefProcessor.processRefProperty(RefProperty, String), checking whether the relative reference starts with "."

Relative reference can also start with "/" (join method within the same class, check correctly)

    private void processRefProperty(RefProperty subRef, String externalFile) {
        if (isAnExternalRefFormat(subRef.getRefFormat())) {
            String $ref = constructRef(subRef, externalFile);
            subRef.set$ref($ref);
            if($ref.startsWith("."))
                processRefToExternalDefinition($ref, RefFormat.RELATIVE);
            else {
                processRefToExternalDefinition($ref, RefFormat.URL);
            }

        } else {
            processRefToExternalDefinition(externalFile + subRef.get$ref(), RefFormat.RELATIVE);
        }
    }

**Comment by leochr** [comment]
I'll create a PR to fix this issue.

**Comment by gracekarina** [comment]
Closed by #864
