### ISSUE TITLE
Valid Swagger 2.0 file is not parsed

### ISSUE THREAD

**Issue by ArulPrakas** [swagger-api/swagger-parser#45]
I tried parsing https://kin-lane.github.io/video/swagger.json swagger file using swagger-parser and it returns null. I can very well import the file in swagger editor ui.

**Comment by webron** [comment]
You get null when doing what? I just tried loading that file and it worked fine.

**Comment by ArulPrakas** [comment]
Working with latest parser artifacts. Closing it.
