### ISSUE TITLE
When converter creates response object the content is not included

### ISSUE THREAD

**Issue by turkeylurkey** [swagger-api/swagger-parser#457]
On line 358 the method and local variables are declared:
```
    public Response convert(v2.io.swagger.models.Response v2Response, List<String> mediaTypes) {
        Response response = new Response();
        Content content = new Content();
```
While pains are taken to populate the content object it is never linked into the model. The response object has no content when it is returned.

**Comment by fehguy** [comment]
Fixed in #461
