### ISSUE TITLE
Getting the schema for the body parameter

### ISSUE THREAD

**Issue by ajaykmr2292** [swagger-api/swagger-parser#468]
I can't find any method which returns the schema of the body parameter. The Parameter class doesn't have any method (e.g. getSchema()) which returns the schema used by that parameter. Need some help asap. I started using this parser today and got stuck here.

**Comment by fehguy** [comment]
What version are you using?  If it's a `BodyParameter`, you'll need to cast the `Parameter` appropriately, as not all Parameter objects have a full blown schema.

See https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/parameters/BodyParameter.java
