### ISSUE TITLE
Is there a way to get the schema in the parameter?

### ISSUE THREAD

**Issue by xunwu** [swagger-api/swagger-parser#473]
For example we have a parameter like this:

"parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Pet object that needs to be added to the store",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Pet"
            }
          }
        ],
we have method to get the in, name, description, but is there a way to get the schema ?

**Comment by fehguy** [comment]
Unfortunately not inside this project.  You can use code from the `swagger-inflector` project if you want that information.
