### ISSUE TITLE
Validation of swagger YAML - similar to editor.swagger.io

### ISSUE THREAD

**Issue by DanielaSfregola** [swagger-api/swagger-parser#498]
Hi guys, 
I have a swagger YML file and I'd like to write a Java/Scala test that would validate our swagger file. At present, we simply copy and paste this file into http://editor.swagger.io/#/ and see if there are errors, but obviously, we'd like to automate this with a proper test. I am playing with swagger-parser, but unfortunately, I cannot manage to see errors even when I pass an invalid swagger YML...

do you guys have any idea on how this can be achieved? is `swagger-parser` the right tool for this?

**Comment by DanielaSfregola** [comment]
In case it may be of help, this is the code that I have so far:

```
      val swaggerJson = readSwaggerAsJsonString(Authority.Empty, "swagger.yml")
      val result = (new SwaggerParser).readWithInfo(swaggerJson)
      // result.getMessages is empty even if the swagger has some validation issues!
```

**Comment by webron** [comment]
Take a look at https://github.com/swagger-api/validator-badge.

**Comment by DanielaSfregola** [comment]
Thanks @webron !
