### ISSUE TITLE
ReadContents and ReadLocation have not the same behavior with OAS 3.0.0

### ISSUE THREAD

**Issue by phiz71** [swagger-api/swagger-parser#519]
Hello,

parsing a OAS 3.0.0 spec with this configuration :
```yaml
openapi: '3.0.0'
components:
  examples:
    ANull:
      value: null
```

Then
if I use `OpenAPIV3Parser.readContents`, the `ANull` JsonNode looks like `{"value":null}`.
if I use `OpenAPIV3Parser.readLocation`, the `ANull` JsonNode looks like `{}`.

The "bug" is (obviously 😄) in `io.swagger.parser.v3.OpenAPIV3Parser` class.
`OpenAPIV3Parser.readContents` uses

```java
static {
        JSON_MAPPER = ObjectMapperFactory.createJson();
        YAML_MAPPER = ObjectMapperFactory.createYaml();
}
```

wheras `OpenAPIV3Parser.readLocation` uses

```java
ObjectMapper mapper = Json.mapper(); //for JSON
DeserializationUtils.readYamlTree(data); //for YAML
```

And it seems that they don't have the same behavior.

I'm preparing a PR to propose a refactoring of this class.

**Comment by webron** [comment]
Closed as fixed.
