### ISSUE TITLE
OpenAPI v2 converter - NullPointerException when model is unexpectedly null

### ISSUE THREAD

**Issue by benken-parasoft** [swagger-api/swagger-parser#539]
The following reproduces with the 2.0 branch.  I have a couple old v2 documents that successfully parse to the v2 model but the converter fails with the following NullPointerException in the method that converts a v2 Model object to a v3 Schema object:
```
java.lang.NullPointerException
	at io.swagger.parser.v2.SwaggerConverter.convert(SwaggerConverter.java:959)
	at io.swagger.parser.v2.SwaggerConverter.convertParameterToRequestBody(SwaggerConverter.java:659)
	at io.swagger.parser.v2.SwaggerConverter.convert(SwaggerConverter.java:504)
	at io.swagger.parser.v2.SwaggerConverter.convert(SwaggerConverter.java:464)
	at io.swagger.parser.v2.SwaggerConverter.convert(SwaggerConverter.java:157)
	at io.swagger.parser.v2.SwaggerConverter.readLocation(SwaggerConverter.java:53)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:18)
```

Technically, the v2 docs that reproduce this are incorrect where a "body" parameter is missing "schema", resulting a null pointer be passed to this convert(Model) method.  However, it would still be good for the converter not to explode like this, especially since the previous 1.x version of swagger-parser didn't throw a NullPointerException.  Perhaps a simple null pointer check is all that's needed to handle this.

**Comment by benken-parasoft** [comment]
I should clarify where the NullPointerException happens since it moves around every time I pull (and still isn't fixed).  Currently it is in io.swagger.parser.v2.SwaggerConverter.convert(Model v2Model) on the line with:
```java
if ((v2Model.getProperties() != null) && (v2Model.getProperties().size() > 0)) {
```
As mentioned, this happens in cases when v2Model is null, were a v2 body parameter is incorrectly missing "schema".  It would be nice to be abl e to still build/convert the model.

**Comment by benken-parasoft** [comment]
I'm not seeing this anymore with 2.0.0-rc2.

**Comment by Alexander1972** [comment]
'swagger-parser' 2.0.0-rc2 does not exist
I have this setup and I have issue the same issue
implementation group: 'io.swagger', name: 'swagger-core', version: '2.0.0-rc2'
    implementation group: 'io.swagger', name: 'swagger-parser', version: '2.0.0-rc1'
