### ISSUE TITLE
Issue with Parser listing empty definitions

### ISSUE THREAD

**Issue by SCSreekanth** [swagger-api/swagger-parser#546]
I believe, as long as the swagger document is valid, swagger parser should be able to parse as expected. In the case where empty definitions are defined, swagger parser doesn't list them in the list of definitions.

Example as Below
```yaml
---
swagger: "2.0"
info:
  version: "1.0"
  title: "dd"
host: "abc:5555"
basePath: "/mypath"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /resource1/Id:
    post:
      description: ""
      operationId: "postOp"
      parameters:
      - in: "body"
        name: "input3"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/mydefinition"
      responses:
        200:
          description: "Successful"
        401:
          description: "Access Denied"
definitions:
  mydefinition: {}
```

As you can see mydefinition though doesn't have any property or type, it is considered as valid in the swagger editor. But when using swagger parser to parse this document, the getDefinitions method returns a list with 0 objects.

Shouldn't this be fixed? Or any valid reason to invalidate this?

Thanks,
Sree

**Comment by webron** [comment]
@SCSreekanth - the fix for this should be available in the new SNAPSHOT. Can you give it a try?

**Comment by SCSreekanth** [comment]
Hi Ron,

Thanks for the quick update. I had downloaded the swagger-parser-1.0.28 jar from the maven repository (https://repo1.maven.org/maven2/io/swagger/swagger-parser/1.0.28/) and had used it. Could you please let me know a way to download the updated jar and then retest my case?

**Comment by webron** [comment]
Hoping this would help - https://maven.apache.org/guides/getting-started/index.html#What_is_a_SNAPSHOT_version

**Comment by SCSreekanth** [comment]
Hi Ron,

I understand that a snapshot version would be available, but all this would be applicable if I have my project setup with this. I am not using pom/maven/gradle...it is a standalone project and I would not want to do necessary changes to point to the snapshot version. If you could send me the link of a downloadable jar (as i am just using as a external jar added to build path) it would be helpful. Otherwise, i am also OK to wait until the official release of jar.

Regards,
Sree

**Comment by webron** [comment]
https://oss.sonatype.org/content/repositories/snapshots/io/swagger/

**Comment by SCSreekanth** [comment]
Hi Ron,

Thanks a lot. I verified and now I am getting the full list of definitions even they do not have any properties. Appreciate all the help. Thanks

Regards,
Sree
