### ISSUE TITLE
HTTP method should be uppercase

### ISSUE THREAD

**Issue by Joengenduvel** [swagger-api/swagger-parser#550]
Looking at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#pathItemObject it seems the HTTP method is always lowercase.
Also the "io.swagger.parser.Swagger20Parser" fails if I specify GET instead of get as HTTP method.
According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.1.1 it should be "GET" instead of "get".

**Comment by webron** [comment]
You're mixing two things. The HTTP specification indeed says that the verbs should be in uppercase. The OpenAPI spec, which does not specify the protocol but rather the API, chose to go with lowercase for field names, or rather camel-case where needed. There's no contradiction between the two. The Parser, used to read OpenAPI definitions is then looking for the lowercase variant.
