### ISSUE TITLE
2.0.0-rc1: Operation security parses scope list as list of NULL items

### ISSUE THREAD

**Issue by jtaylor10** [swagger-api/swagger-parser#562]
Not sure if others are running into this issue but below is an example schema that is causing the issue. Using 2.0.0-rc1 and openapi v3 specification format. 

```yaml
openapi: "3.0.0"
info:
  title: Test OpenApi Specification
  version: 1.0.0
paths:
  /test:
    get:
      operationId: testGet
      security:
        - openId:
          - https://scopes.example.com/myScope
      responses:
        200:
          description: get response.
          content:
            "application/json":
              schema:
                type: object
components:
  security:
    securitySchemes:
        openId:
          type: openIdConnect
          openIdConnectUrl: https://....
```

If I put this through the parser the `GET /test` path item has a security object, which has `openId` but it contains a list of 1 item, with a value of `NULL` where it should be `https://scopes.example.com/myScope`

**Comment by gracekarina** [comment]
Thank you @jtaylor10
