### ISSUE TITLE
Unable to parse 'minItems', 'maxItems' properties from swagger yaml file

### ISSUE THREAD

**Issue by tingwood** [swagger-api/swagger-parser#594]
As I used v1.0.22, I found the parser can't analyze 'minItems' and 'maxItems' of array properties.
the structure example show as follow
![image](https://user-images.githubusercontent.com/33972761/33227013-37c4dba6-d1d5-11e7-93d5-8b9419ba666c.png)

**Comment by webron** [comment]
This should be fixed in the latest version, give it a try.

**Comment by tingwood** [comment]
great, hoping for the new version.
BTW, do you have any plan to support swagger 3.0

**Comment by tingwood** [comment]
Great, hoping for the new version. thanks

**Comment by lipengfeigodliness** [comment]
@webron

**Comment by lipengfeigodliness** [comment]
@webron 
i use the 1.0.33(the lastversion) parser yaml,but do not find minItems maxItems

**Comment by gracekarina** [comment]
Hi @lipengfeigodliness @tingwood, can you please post the spec you're using as text, thanks

**Comment by gracekarina** [comment]
@tingwood @lipengfeigodliness  please check if the merged solved the issue 👍

**Comment by gracekarina** [comment]
@tingwood  @lipengfeigodliness  please let us know if it's still an issue.
