### ISSUE TITLE
How can i use 1.0.33 parser yaml?

### ISSUE THREAD

**Issue by lipengfeigodliness** [swagger-api/swagger-parser#595]
before i use 1.0.22 SwaggerParser().parse(yamlstr),,it resolve success,
but when i usr 1.0.33 SwaggerParser().parse(yamlstr),it has exception,how can i use   1.0.33 parser yaml?

**Comment by gracekarina** [comment]
Hi! @lipengfeigodliness  can you please provide the spec? thanks!

**Comment by lipengfeigodliness** [comment]
my yaml like this




swagger: '2.0'
info:
  title: 查询天气
  description: 查询天气
  version: v1.0

host: 10.162.123.33:8081
schemes:
  - http
  - https

basePath: /
produces:
  - application/json
consumes:
  - application/json

paths:
  /weather:
    post:
      summary:  测试用例生成 
      tags:
        - API自动测试
      parameters:
        - name: date
          in: query
          required: true
          description: 日期
          type: string
      responses:
        200:
          description: 查询天气成功
          schema:
            type: object
            required:
              - temperature
            properties:
              temperature:
                type: string
                description: 温度
  /get/lgc:
    post:
      parameters:
        - name: body
          in: body
          description: Hello world
          schema:
            type: array
            minItems: 1
            maxItems: 1
            items:
              $ref: '#/definitions/Pet'
      responses:
        '200':
          description: ''
          schema:
            type: string
definitions:
  Pet:
    type: "object"
    required:
    - "SecondaryDnsV4"
    - "dnsGroupName"
    - "primaryDnsV4"
    properties:
      dnsGroupName:
        type: "string"
      primaryDnsV4:
        type: "string"
      SecondaryDnsV4:
        type: "object"
        required:
        - "id"
        properties:
          id:
            type: integer

**Comment by lipengfeigodliness** [comment]
@gracekarina
sorry,gracekarina,my net can not upload file,can you use swagger-editor or other tool format the yaml i copy here.
3ks

**Comment by lipengfeigodliness** [comment]
https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java

**Comment by lipengfeigodliness** [comment]
https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
this reslove my problem
