### ISSUE TITLE
conversion of method response type from Swagger 1.2 to 2.0

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-parser#60]
For `type` under `operations` in Swagger spec 1.2, there seems to be an issue converting it to Swagger 2.0.

Here is the error message returned by Codegen:
```
reading from https://raw.githubusercontent.com/swagger-api/swagger-parser/master/modules/swagger-compat-spec-parser/src/test/resources/specs/v1_2/singleFile.json

reading from https://raw.githubusercontent.com/swagger-api/swagger-parser/master/modules/swagger-compat-spec-parser/src/test/resources/specs/v1_2/singleFile.json
2366 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for Pet, null
2366 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for Pet, null
2367 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for null, null
2367 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for void, null
WARNING!  No property detected!  Falling back to string!
2367 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for null, null
WARNING!  No property detected!  Falling back to string!
2367 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for Pet, null
2368 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for void, null
WARNING!  No property detected!  Falling back to string!
2368 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for Pet, null
2368 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for void, null
WARNING!  No property detected!  Falling back to string!
2368 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for null, null
2368 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for null, null
2368 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for void, null
WARNING!  No property detected!  Falling back to string!
2370 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for null, null
2370 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for null, null
writing file /var/tmp/perl/test/lib/WWW/SwaggerClient/Object/Category.pm
writing file /var/tmp/perl/test/lib/WWW/SwaggerClient/Object/Pet.pm
writing file /var/tmp/perl/test/lib/WWW/SwaggerClient/Object/Tag.pm
writing file /var/tmp/perl/test/lib/WWW/SwaggerClient/DefaultApi.pm
writing file /var/tmp/perl/test/lib/WWW/SwaggerClient/ApiClient.pm
writing file /var/tmp/perl/test/lib/WWW/SwaggerClient/Configuration.pm
writing file /var/tmp/perl/test/lib/WWW/SwaggerClient/Object/BaseObject.pm
```

My guess is that it fails to covert the response type (void, model or not defined) from 1.2 to 2.0

ref: https://github.com/swagger-api/swagger-codegen/issues/877

Code producing the error log: https://github.com/swagger-api/swagger-core/blob/9c67549cc4e30db916dac0165f0549485a6eb4c7/modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java#L569

**Comment by tomtit** [comment]
The message from [PropertyBuilder](916dac0165f0549485a6eb4c7/modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java#L569) doesn't affect the converter. I think its level has to be changed from `ERROR` to `DEBUG`.
Another message "Falling back to string!" is more interesting for us. It tells us that `null` and `void` responses were forced to be of type `string`. This message is sent from [here](https://github.com/swagger-api/swagger-parser/blob/93b0db9f4a07f0c7873856fe69a1b9ad0e58f59e/modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java#L340) and was added after [this](https://github.com/swagger-api/swagger-parser/commit/4d9bd1ce477bc00fcae52e200e95c031414e4ed8#diff-e280195c2ed7ce7e15912f4990b54e5aR324) commit for the issue #43.

**Comment by wing328** [comment]
@tomtit agree with you that the result is not affected and the log level should be changed to avoid escalation due to the error message.
