### ISSUE TITLE
Swagger Parser not parsing external $refs

### ISSUE THREAD

**Issue by james---** [swagger-api/swagger-parser#62]
The swagger file found at 

https://raw.githubusercontent.com/swagger-api/swagger-spec/master/fixtures/v2.0/json/resources/resourceWithLinkedDefinitions.json

is a example of one that has had it's path object extracted into a separate json file and referenced using a json reference.

`paths: {`
`    /pets/{petId}: {`
`        $ref: "https://raw.githubusercontent.com/swagger-api/swagger-spec/master/fixtures/v2.0/json/resources/resourceWithLinkedDefinitions_part1.json"`
`    }`
`},`

Unfortunately, this does not appear to work as after parsing the swagger file the Path pojo for the /pets/{petId} path contains no defined operations.

I am seeing this in swagger-parser 1.0.8

**Comment by fehguy** [comment]
verified fixed in 1.0.11
