### ISSUE TITLE
swagger-compat-spec-parser 1.0.34 loses array items $refs in body parameters - REGRESSION from 1.0.33

### ISSUE THREAD

**Issue by benken-parasoft** [swagger-api/swagger-parser#641]
I just updated to the new swagger-parser 2.0.0-rc3 and found what appears to be a rather severe regression.  The regression actually appears to be in swagger-compat-spec-parser 1.0.34 (and/or one of the updated 1.5.18 io.swagger core libraries).  This wasn't happening in the previous 1.0.33/1.5.17 release.

Observe this Swagger 1.2 body parameter.  It is taken from the User API from old v1 Petstore example:
[user.json.txt](https://github.com/swagger-api/swagger-parser/files/1669538/user.json.txt)
```json
{
  "name": "body",
  "description": "List of user object",
  "required": true,
  "type": "array",
  "items": {
    "$ref": "User"
  },
  "paramType": "body",
  "allowMultiple": false
}
```
swagger-compat-spec-parser 1.0.33 converts this to the following which is correct:
```json
{
  "in": "body",
  "name": "body",
  "description": "List of user object",
  "required": true,
  "schema": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/User"
    }
  }
}
```
The new swagger-compat-spec-parser 1.0.34 loses the $ref to #/definitions/User .  Notice how the $ref in "items" has disappeared!
```json
{
  "in": "body",
  "name": "body",
  "description": "List of user object",
  "required": true,
  "schema": {
    "type": "array",
    "items": {
      
    }
  }
}
```
I noticed this from my application which uses swagger-parser to read any old Swagger definition to the v3 model.  In that case I originally noticed ArraySchema.getItems().get$ref() returning a null pointer.  However, for the purpose of isolating this issue, I ran the following code with swagger-compat-spec-parser 1.0.33 and then with 1.0.34 to observe the $ref getting lost:

```java
        SwaggerCompatConverter scc = new SwaggerCompatConverter();
        Swagger swagger2 = scc.read("petstore/user.json");
        System.out.println(io.swagger.util.Json.mapper().writeValueAsString(swagger2));
```

As a workaround, it looks like I can still use the new swagger-parser 2.0.0-rc3 which fixes a lot of bugs for me but I have to hold back the versions of the 1.x stuff as follows.
Instead of 1.0.34, I have to hold these back to 1.0.33: io.swagger:swagger-parser and io.swagger.swagger-compat-spec-parser
Instead of 1.5.18, I have to hold these back to 1.5.17: io.swagger:swagger-core and io.swagger:swagger-models

**Comment by gracekarina** [comment]
Hi @benken-parasoft thanks! Sorry for the late response.
This issue was fixed by #656 PR, please let us know if it keeps failing.

**Comment by benken-parasoft** [comment]
>Sorry for the late response

Sorry for the late reply.  😁 I verified in the 2.0.0 release and everything looks good from my end.  Thank you so much.

**Comment by gracekarina** [comment]
🎉
