### ISSUE TITLE
having allOf anywhere except the bottom causes "Resolver errorCannot read property 'Thing' of undefined" (sometimes)

### ISSUE THREAD

**Issue by manoadamro** [swagger-api/swagger-parser#649]
If a model uses 'allOf' but does not have it at the bottom, it will cause the following error

```Resolver errorCannot read property 'Thing' of undefined```

where 'Thing' is a completely different, unrelated model. 
This was incredibly hard to debug since the model described in the error does not have any obvious connection to the model causing the error. 

Moving the 'allOf' to the bottom of the model definitions eventually fixed it.
This is not the case with every model, but it is for a random few. (some of my models still have it towards the top and cause no problems, others cause errors unless they are at the bottom)

**Comment by gracekarina** [comment]
Hi, can you please send us an spec, or even better add a PR with a failing test, so we can work on a fix.
Thanks!
