### ISSUE TITLE
Map primitive string to model

### ISSUE THREAD

**Issue by atomfrede** [swagger-api/swagger-parser#66]
We have the following ``swagger.json``. The ``POST`` method just takes a ``String`` ``body`` and writes it directly into Solr (therefore no real object/datatype). The wagger parser does not map the primitive type ``string`` (property) to a ``Model``. Therefore using @RobWin swager2markup generator fails. Is there e specific reson why string property is not mapped to a model?

```
{
  "apiVersion" : "0.0.1-SNAPSHOT",
  "swaggerVersion" : "1.2",
  "basePath" : "",
  "resourcePath" : "/resource/x/v2",
  "apis" : [ {
	"path" : "/resource/x/v2",
	"operations" : [ {
	  "method" : "POST",
	  "nickname" : "createX",
	  "type" : "string",
	  "parameters" : [ {
		"type": "string",
		"description" : "The x in JSON format",
		"paramType" : "body",
		"name" : "body",
		"required" : true
	  } ],
	  "summary" : "Creates a x x.",
	  "notes" : "If id already exists, the x is updated.",
	  "responseMessages" : [ {
		"code" : 200,
		"message" : "ok"
	  }, {
		"code" : 500,
		"message" : "error"
	  } ],
	  "consumes" : [ "application/json" ]
	} ]
  }, {
	"path" : "/resource/x/v2/{id}",
	"operations" : [ {
	  "method" : "GET",
	  "nickname" : "getX",
	  "type" : "string",
	  "parameters" : [ {
		"type" : "integer",
		"description" : "A valid x x UUID",
		"paramType" : "path",
		"name" : "id",
		"required" : true
	  } ],
	  "summary" : "Gets the x x with the specified id.",
	  "responseMessages" : [ {
		"code" : 200,
		"message" : "ok"
	  }, {
		"code" : 404,
		"message" : "not found"
	  } ],
	  "produces" : [ "application/json" ]
	} ]
  } ]
}
```

**Comment by RobWin** [comment]
It semms to happen in `SwaggerCompatConverter` and method `modelFromExtendedTypedObject ` 

![blob](https://cloud.githubusercontent.com/assets/5815046/8744256/1225b5f2-2c76-11e5-89c8-20473755b1e7.png)

The input is a `StringProperty`, but the input is not mapped to the output. Therefore the output Model is `null`.

**Comment by webron** [comment]
Perhaps my logic fails me, but a string is a string, not a model. Why would it map to a model?

**Comment by RobWin** [comment]
The problem its mapped to `null` which results in a BodyParameter with an emtpy Schema/Schema. Therefor it lost its mapped body type information.

**Comment by webron** [comment]
@RobWin - fair enough, though that's slightly different than the title :)

**Comment by atomfrede** [comment]
Sorry for the misleading title :)

**Comment by fehguy** [comment]
supported in 1.0.18

**Comment by RobWin** [comment]
Thx
