### ISSUE TITLE
NPE when converting "paths" without any path

### ISSUE THREAD

**Issue by vadeg** [swagger-api/swagger-parser#662]
According to [OpenAPI v3 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#pathsObject) and [OpenAPI v2 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathsObject) 

> The Paths MAY be empty, due to ACL constraints.

`SwaggerConverter` fail with error if there are no paths in original model but should convert successfully without paths. This related only to api defined as `yaml`.

**Comment by vadeg** [comment]
Everything works as expected :)

**Comment by gracekarina** [comment]
Hi @vadeg Thanks for reporting!

**Comment by gracekarina** [comment]
We have merged the PR, please reopen in case it keeps presenting. Thanks!!
