### ISSUE TITLE
Relative $refs aren't relative to the file in which they are declared.

### ISSUE THREAD

**Issue by kevinpeterson** [swagger-api/swagger-parser#671]
**Description**

Relative ```$ref``` declarations don't resolve relative to their containing file.

For example
```
main.yaml
  - models
    - model1.yaml
  - common
    - shared.yaml
```

Assume a reference in ```model1.yaml``` like ```$ref: '../common/shared.yaml#/definitions/MyObj'```

This will fail via an ```Unable to load RELATIVE ref: ...``` error (via the codegen).

The ```ResolverCache``` resolves these references relative to a ```parentDirectory``` file that is final:

https://github.com/swagger-api/swagger-parser/blob/64a5ea7402183fc4cd8a1b58602045952311e0da/modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java#L113

Wouldn't the ```parentDirectory``` need to be variable - i.e., be set to the directory containing the file where the $ref is declared?

**Comment by webron** [comment]
@kevinpeterson which version of the parser is this in reference to?

**Comment by kevinpeterson** [comment]
I'm using swagger-codegen-maven-plugin version 2.3.1 which seems to use version 1.0.33 of the parser.

**Comment by sotty** [comment]
Thanks @webron and @gracekarina ! Knowing what the "correct" behavior is, and have the implementation match it is quite important for our project. We have some 'dev hours' resources to contribute if there is any way we can help

**Comment by webron** [comment]
@sotty we're always happy to accept PRs (well, if they solve issues and have tests with them) ;)

**Comment by sotty** [comment]
heh I know how that works :)

Based on your priorities, if you or @gracekarina have bandwidth to work on this in the next days, we'll wait. If this is further down the line, we'll discuss the fix and co-work on a PR

**Comment by sotty** [comment]
@kevinpeterson @gracekarina I have not been able to reproduce the problem with the current 1.0.35 version. I will try the older version 1.0.33, the codegen and the plugin

**Comment by sotty** [comment]
Indeed, it is fixed in 1.0.34+
The workaround is to explicitly constrain the version in the codegen-plugin, at least until a new stable version that uses 1.0.34+ is released

```xml
<plugin>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-codegen-maven-plugin</artifactId>
  <version>2.3.1</version>
  <executions>...</executions>
  <dependencies>
    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-parser</artifactId>
      <version>1.0.34</version>
    </dependency>
  </dependencies>
</plugin>

**Comment by webron** [comment]
@sotty 2.4.0-SNAPSHOT should depend on it if you want to give it a try.

**Comment by gracekarina** [comment]
Hi @kevinpeterson @sotty   please let us know if this is still an issue. Thanks!

**Comment by gumshoe-kzn** [comment]
I ran into the same problem and the 3.0.0-rc0 version works.

**Comment by kevinpeterson** [comment]
I used 1.0.35-SNAPSHOT and that seemed to take care of the problem. Thanks!

**Comment by sotty** [comment]
I could use 1.0.34 to parse a graph of mutually referencing models
successfully
Kevin took it one step further with the code generation, but had to use
1.0.35-SNAPSHOT

We did not have the time to isolate which commit(s) did fix the problem

Thanks for your assistance!

**Comment by CluEleSsUK** [comment]
I'm experiencing this same issue with version 2.3.1, but neitherupgrading the swagger parser to 1.0.34 nor 1.0.35-SNAPSHOT fixes it for me
