### ISSUE TITLE
Question for v2: OpenAPIV3Parser vs OpenAPIParser

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-parser#689]
When I parse a swagger v2 spec with the `OpenAPIV3Parser` I get this error:

```
java.lang.NullPointerException
	at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:91)
	at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:78)
	at <my class>.main(<my class>.java:25)
```

---

My understanding from `swagger-parser` code: 

`OpenAPIParser` delegates to one `SwaggerParserExtension` instance.
There are 2 implementations of the `SwaggerParserExtension` interface:

* `OpenAPIV3Parser` (only for swagger v3 spec)
* `SwaggerConverter` (does on the fly the conversion v2 => v3)

Using `OpenAPIV3Parser` is not a good idea, prefer call of `OpenAPIParser` especially if you do not know the format of the spec you are parsing.

---

Thank you in advance for your answers.

**Comment by jmini** [comment]
For example the `swagger-codegen` project in [Codegen](https://github.com/swagger-api/swagger-codegen/blob/3.0.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/Codegen.java#L92) is using `OpenAPIV3Parser`:

```
openAPI = new OpenAPIV3Parser().read(cmd.getOptionValue("i"), clientOptInput.getAuthorizationValues(), null);
```

I think this is wrong, but I would like to be sure, before I do a change.

**Comment by HugoMario** [comment]
@jmini in order to support both format we're using **`OpenAPIParser`** on codegen project.

https://github.com/swagger-api/swagger-codegen/blob/3.0.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java#L452

**Comment by jmini** [comment]
Thank you for your feedback. I close the issue.
