### ISSUE TITLE
When will the 2.0.0 version make it to maven?

### ISSUE THREAD

**Issue by thejjmiller** [swagger-api/swagger-parser#695]
When will the 2.0.0 version make it to maven?

**Comment by gracekarina** [comment]
Hi, it's there. https://search.maven.org/#artifactdetails%7Cio.swagger.parser.v3%7Cswagger-parser%7C2.0.0%7Cjar

**Comment by webron** [comment]
:tada:

**Comment by thejjmiller** [comment]
Cool! Thank you. You may want to update the maven repository move notification. It currently says the parser project has been moved to io.swagger.core.v3.

![image](https://user-images.githubusercontent.com/6386536/39191675-734c740e-47a5-11e8-8eb8-6d886fd11ca9.png)
