### ISSUE TITLE
Missing the value of 'deprecated' field

### ISSUE THREAD

**Issue by ackintosh** [swagger-api/swagger-parser#697]
Example json in OAS v2:

```json
{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "x-example"
    },
    "host": "httpbin.org",
    "basePath": "/anything",
    "schemes": [
        "http"
    ],
    "paths": {
        "/{foo}": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                },
                "deprecated": false
            }
        }
    }
}
```

In case of `deprecated: false` like above or the field is omitted, `Operation.getDeprecated()` returns null. 
I think `Operation.getDeprecated()` should return false in that case. There is the same issue in OAS v3.

I'll submit a PR that fixes this issue.

**Comment by frantuma** [comment]
this is fixed by related fix in core in swagger-api/swagger-core/pull/2795 , PR #715 adds a related test.
