### ISSUE TITLE
Quick Question : Regarding $ref to external files

### ISSUE THREAD

**Issue by mutkur** [swagger-api/swagger-parser#701]
I have come across a section in swagger specification that we can use $ref to external files as
 1 ) Relative Schema File Example
 2 ) Relative Files With Embedded Schema 

So the question is if we have format like $ref:"../common/shared.yaml#/definitions/MyObj' is it necessary that shared.yaml is a complete swagger file or could just be some yaml/json file with some definitions ? What is the assumption around the external references.

Thanks in advance

**Comment by webron** [comment]
A reference can be to any json/yaml file, it doesn't need to be a full API definition.
