### ISSUE TITLE
Referencing external parameter without './' is not working (Swagger 2.0)

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-parser#704]
Hi team,

When an external parameter object is referenced in the swagger file without './', parameters is not referenced correctly.

Without './' it's not working:
      parameters:
        - $ref : 'paramA.yaml#/parameters/PageSize'

After adding './, it's working
      parameters:
        - $ref : './paramA.yaml#/parameters/PageSize'

Thanks,
Mohammed Rizwan

**Comment by gracekarina** [comment]
Hi, @ymohdriz thanks for reporting this issue, can you please add a definition so we can reproduce the issue. Thanks.

**Comment by ymohdriz** [comment]
Hi @gracekarina,

I attached the zip file where serviceA.yaml is the main swagger file.
It's working fine if we change the reference from 'paramA.yaml#/parameters/PageSize' to './paramA.yaml#/parameters/PageSize' under parameters section in serviceA.yaml.

Issue:
Parameter is resolved incorrectly.

[ParamRefNOk.zip](https://github.com/swagger-api/swagger-parser/files/2000115/ParamRefNOk.zip)

Thanks,
Mohammed

**Comment by gracekarina** [comment]
Hi @ymohdriz  please checkout the branch `issue704` I ran the test and it did not failed, I removed the `./` of the refs, and worked. So my question is if the files are located the same as in your project. If you can share a test on how you are using this it would be great, so we can be able to reproduce. 👍

**Comment by markus-wa** [comment]
I'm running into this as well if I use one of the following parhs as `url` parameter:
- `C:\Users\mwalt\dev\workspaces\java\swagger-parser-ref\src\main\resources\lov-api.yaml`
- `src/main/resources/lov-api.yaml`

This works: `file:/C:/Users/mwalt/dev/workspaces/java/swagger-parser-ref/bin/lov-api.yaml`

Also this is with OpenAPI 3 for me, not just swagger

**Comment by gracekarina** [comment]
Hi this issue was solved by https://github.com/swagger-api/swagger-parser/pull/725. Please let us know if this keeps presenting.
