### ISSUE TITLE
ClassCastException when processing external refs

### ISSUE THREAD

**Issue by douglasbgray** [swagger-api/swagger-parser#706]
I am using the swagger parser in a large project like so:
```
    ParseOptions parseOptions = new ParseOptions();
    parseOptions.setResolveFully(true);
    SwaggerParseResult swagger = new OpenAPIParser().readLocation(rootDoc, null, parseOptions);
    return Yaml.pretty().writeValueAsString(swagger);
```
And am getting this exception:

```
java.lang.ClassCastException: io.swagger.v3.oas.models.media.ObjectSchema cannot be cast to io.swagger.v3.oas.models.media.ArraySchema
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processProperties(ExternalRefProcessor.java:191)
```

Looking into it, I see some unusual code in this block:

https://github.com/swagger-api/swagger-parser/blob/2.0/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java#L191-L195

It looks like a check is made to see if a cast is possible for `mapProp.getAdditionalProperties()`, but the cast actually applied to `mapProp`, which is where the exception is getting thrown.

Sorry I don't have a reproducible test file to attach. The project is large (over 100 API fragments) and when I tried to create a simplified test case, the exception did not happen.

**Comment by gracekarina** [comment]
Hi, thanks, I think I see whats happening there, I will try to provide a solution, will you be able to test it from a branch not merged yet? @douglasbgray

**Comment by douglasbgray** [comment]
@gracekarina Yes, I can test from an unmerged branch.

**Comment by gracekarina** [comment]
@douglasbgray let me know if that does it! 👍

**Comment by douglasbgray** [comment]
@gracekarina That fixed it. I am no longer getting the ClassCastException. Thanks for the quick fix.
