### ISSUE TITLE
Question: release date for 2.0.1?

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-parser#717]
Have you an idea when you will release the next bugfix release of `swagger-parser` branch `2.0`?

Having this information would be useful for downstream projects like `swagger-codegen`, `openapi-diff` or `openapi-generator` (and maybe other that I do not know).

Thank you a lot.

**Comment by frantuma** [comment]
@jmini we are planning parser 2.0 release for within this week, probably on coming Thursday

**Comment by jmini** [comment]
I hope it will also contain #716

**Comment by jmini** [comment]
Release: https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.1
