### ISSUE TITLE
Is it possible to validate a swagger document usi Swagger Java API

### ISSUE THREAD

**Issue by r-sreesaran** [swagger-api/swagger-parser#718]
I have sample swagger document and i wish to validate it and find out whether it is valid swagger document. Is this possible using Swagger Java API.

**Comment by jmini** [comment]
You can have a look at how OpenAPI Generator is using it: [`Validate.java`](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Validate.java) (or similar code in swagger-codegen)

**Comment by gracekarina** [comment]
Hi @r-sreesaran I suggest you use validator-badge. https://github.com/swagger-api/validator-badge

**Comment by r-sreesaran** [comment]
@gracekarina  I am looking for validator that is available as a Java API. Which i could include as part of my maven build environment.

**Comment by gracekarina** [comment]
@r-sreesaran  for validation you can use the parser itself, by using the `getMessages()` method of `SwaggerParseResult` object, to check the validity of a spec, as long as the the `getMessages` it's empty.

**Comment by r-sreesaran** [comment]
Issue resolved.
