### ISSUE TITLE
All vendor extensions in responses are ignored

### ISSUE THREAD

**Issue by matthewadams** [swagger-api/swagger-parser#719]
https://github.com/swagger-api/swagger-parser/blob/be9ba9db4880d907bc4b421a48d1dc37a1e5d0ed/modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java#L1101 The above line shows that _all_ vendor extensions that are defined in a response are simply dropped on the floor, which is a blocker for me.

**Comment by frantuma** [comment]
this should be addressed/tested also in swagger-core deserializer

**Comment by gracekarina** [comment]
closed by #737
