### ISSUE TITLE
Can swagger-parser read a spec, make changes and then write back to file?

### ISSUE THREAD

**Issue by naddison** [swagger-api/swagger-parser#739]
I have a use case in which I would like to read a swagger spec in JSON format, make some changes to the models programatically, and then write the spec back out to file in JSON format. Can swagger-parser do that?

**Comment by ymohdriz** [comment]
Hi @naddison,

Swagger parser read your input spec in form of file or url and return you a swagger/OpenAPI object.
Then you can change the swagger/OpenAPI object accordingly and write it to file.

Thanks,
Mohammed

**Comment by ymohdriz** [comment]
Hi @naddison,

You can close this issue, if your question is answered.

Thanks,
Mohammed

**Comment by Malligarjunan** [comment]
@naddison  The following should solve your requirement

 File file = new File("C:\\Users\\malli\\AppData\\Local\\Temp\\testOpenAPI.json");
 FileWriter fw = new FileWriter(file);
 String str = io.swagger.v3.core.util.Json.pretty(openAPI);
 fw.write(str);
 fw.flush();
 fw.close();
