### ISSUE TITLE
Issue in converting server url in RFC 3986 format from OpenAPI Spec 2 to Open API Spec 3

### ISSUE THREAD

**Issue by sandeeprajub4u** [swagger-api/swagger-parser#745]
If the host is defined without defining schema in OpenAPI Spec 2 then Server.url shoud be //{hostname}/{basePath} but it is {hostname}/{basepath}

The same is explained in swagger documentation under Server URL format ( RFC 3986 )
https://swagger.io/docs/specification/api-host-and-base-path/ 

It is a minor bug fix in the SwaggerConvert.convert(List<Scheme> schemes, String host, String basePath) by changing to below lines

private List<Server> convert(List<Scheme> schemes, String host, String basePath) {
        List<Server> servers = new ArrayList<>();
        String baseUrl;

        if (StringUtils.isNotEmpty(basePath)) {
            baseUrl = basePath;
        } else {
            baseUrl = "/";
        }

        if (StringUtils.isNotEmpty(host)) {
            baseUrl = "//" + host + baseUrl;
        }

        if (!StringUtils.startsWith(baseUrl, "/") && schemes != null && !schemes.isEmpty()) {
            for (Scheme scheme : schemes) {
                Server server = new Server();
                server.setUrl(scheme.toValue() + ":" + baseUrl);

                servers.add(server);
            }
        } else {
            if (!"/".equals(baseUrl)) {
                Server server = new Server();
                server.setUrl(baseUrl);

                servers.add(server);
            } else {
                return null;
            }
        }

        return servers;
    }

**Comment by ymohdriz** [comment]
Hi @sandeeprajub4u,

Can you please raise a PR if your code fixed this issue.

Thanks,
Mohammed

**Comment by gracekarina** [comment]
Closed By #794
