### ISSUE TITLE
Not parsing enums in definitions object

### ISSUE THREAD

**Issue by samxye** [swagger-api/swagger-parser#75]
Enum fields in definitions object are not being parsed. However, enum fields under a property in definitions object are parsed properly. Example:

**swagger.json**
```
"AdvStateType": {
   "description": "Advertising State",
   "enum": [
      "off",
      "on"
   ],
   "type": "string"
},
```

**Corresponding output of - DdebugSwagger in swagger-codegen**
```
"AdvStateType": {
   "type": "string",
   "description": "Advertising State"
},
```

**Comment by fehguy** [comment]
I believe this is addressed, see https://github.com/swagger-api/swagger-core/commit/f65425b878afa16ca10ae171db6efdc82ce4813a

**Comment by chandravadans** [comment]
I have this exact same issue as @samxye . I'm using the latest snapshot releases of `swagger-parser (swagger-parser-1.0.11-SNAPSHOT.jar)` and `swagger-core (swagger-core-1.5.4-SNAPSHOT.jar)` from Maven in my project. What can be done to fix this?

**Comment by webron** [comment]
@chandravadans - I pushed a new snapshot of swagger-core 1.5.4 earlier today. can you try again with the latest?

**Comment by chandravadans** [comment]
@webron the issue seems to be fixed now. Thanks! :beers:

**Comment by webron** [comment]
@chandravadans - and to be certain, you've tested it with 1.5.4-SNAPSHOT?

**Comment by chandravadans** [comment]
@webron Yes, I'd used the version 1.5.4-SNAPSHOT from Maven Central. `swagger-core-1.5.4-SNAPSHOT.jar`

**Comment by roykachouh** [comment]
For those of you who stumble on this...

I was having the same issue. Defining a definition with the following spec:

```
definitions:
  GlobalEnum:
    type: string
    enum:
      - ONE
      - TWO
```

Results in a null object being passed backed from the `SwaggerDeserializer` line 742 of swagger parser 1.0.11

Upgrade to latest parser `1.0.21` resolves the issue.
