### ISSUE TITLE
Is the artifact in maven central built from master or 2.0 branch?

### ISSUE THREAD

**Issue by northwood88** [swagger-api/swagger-parser#770]
Just wondering if the artifact in maven central is built from master or the 2.0 branch. I am assuming OpenAPI 3.0 is only supported on 2.0?

**Comment by naddison** [comment]
What artifact should I be using if I want to be able to read 2.0 and 3.0, but do not need to read anything older than 2.0?

Currently I am using 
`<dependency>
            <groupId>io.swagger.parser.v3</groupId>
            <artifactId>swagger-parser</artifactId>
            <version>2.0.1</version>
        </dependency>
`

**Comment by naddison** [comment]
Never mind, figured this out.
