### ISSUE TITLE
Parsing swagger-spec copies responses.200.schema into property responses.200.responseSchema?

### ISSUE THREAD

**Issue by naddison** [swagger-api/swagger-parser#772]
Here is an example of an endpoint with the schema property being copied.
```javascript "/users/{userId}/games/{gameId}/start": {
	"post": {
		"tags": [
			"users"
		],
		"consumes": [
			"application/x-www-form-urlencoded"
		],
		"produces": [
			"application/xml",
			"application/json"
		],
		"parameters": [
			{
				"name": "userId",
				"in": "path",
				"description": "the ID of the user",
				"required": true,
				"type": "string"
			},
			{
				"name": "AuthToken",
				"in": "header",
				"description": "Authentication token",
				"required": true,
				"type": "string"
			}
		],
		"responses": {
			"200": {
				"description": "Successful operation",
				"schema": {
					"$ref": "#/definitions/GameUsage"
				}
			},
			"400": {
				"description": "Invalid status value"
			}
		}
	}
}
```

is transformed into

```javascript
"/users" : {
      "post" : {
        "tags" : [ "users" ],
        "consumes" : [ "application/x-www-form-urlencoded" ],
        "produces" : [ "application/xml", "application/json" ],
        "parameters" : [ {
          "name" : "userId",
          "in" : "path",
          "description" : "the ID of the user",
          "required" : true,
          "type" : "string"
        },
		{
          "name" : "AuthToken",
          "in" : "header",
          "description" : "Authentication token",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "responseSchema" : {
              "$ref" : "#/definitions/GameUsage"
            },
            "schema" : {
              "$ref" : "#/definitions/GameUsage"
            }
          },
          "400" : {
            "description" : "Invalid status value"
          }
        }
      }
    }
```

**Comment by gracekarina** [comment]
Hi, what is the issue exactly? Does this throws an error?

**Comment by naddison** [comment]
Why is the parser adding this property? Is responseSchema even a valid
property of an OperationModel?

**Comment by hkosova** [comment]
@gracekarina the issue is that the parser(?) adds an extra `responseSchema` property which is not a valid property in OpenAPI:
```
        "responses" : {
          "200" : {
            "description" : "Successful operation",

            "responseSchema" : {  // <--------- should not be there
              "$ref" : "#/definitions/GameUsage"
            },

            "schema" : {
              "$ref" : "#/definitions/GameUsage"
            }
          },
```

**Comment by gracekarina** [comment]
Hi, how exactly are you getting that issue, are you using Json.mapper or Yaml.mapper or another mapper. Also I have tested the parser outcome with Yaml.prettyPrint and there is only a schema item in response.

**Comment by naddison** [comment]
I am executing the following code:

```java
SwaggerParser parser = new SwaggerParser();
Swagger swagger = parser.read(new File(PATH_TO_SWAGGER_JSON_FILE);

ObjectMapper mapper = new ObjectMapper();
mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
mapper.enable(SerializationFeature.INDENT_OUTPUT);
mapper.writeValueAsBytes(swagger);
```
I am not using YAML anywhere, and using Jackson to write out the Swagger object to file as JSON.

**Comment by frantuma** [comment]
You have two options:

1.  either use the configured mapper provided by `swagger-core` via `io.swagger.v3.core.util.Json.mapper()` (or `Yaml.mapper()`) and if needed customize it further e.g with `SerializationFeature.INDENT_OUTPUT`

2. add the following to your mapper config:
`mapper.addMixIn(Response.class, ResponseSchemaMixin.class);`

**Comment by naddison** [comment]
Ahh this is fantastic. Okay, I have flipped to using the ObjectMapper provided by the package. I didn't know this existed, I didn't see it in the documentation anywhere, but it works!

Can you provide a brief explanation what the ResponceSchemaMixin.class does?

**Comment by gracekarina** [comment]
Glad to see your issue is solved.
About the ResponseSchemaMixin, it establishes the `responseSchema` attribute as the `schema` property.  This is part of a change made in core.
https://github.com/swagger-api/swagger-core/blob/1.5/modules/swagger-core/src/main/java/io/swagger/jackson/mixin/ResponseSchemaMixin.java

**Comment by naddison** [comment]
Merci! Closing.
