### ISSUE TITLE
Swagger converter throws error when converting 2.0 to 3.0

### ISSUE THREAD

**Issue by preithig** [swagger-api/swagger-parser#776]
Hi,

We are trying to convert the swagger 2.0 to OpenAPI(3.0) using the library io.swagger.v3.parser.converter.SwaggerConverter.java. It is throwing error.
Attached the file for reference. It is a valid Swagger 2.0 file
[petStore.zip](https://github.com/swagger-api/swagger-parser/files/2215943/petStore.zip)

**Comment by ymohdriz** [comment]
Hi @preithig

Can you please add the error details and which parser version are you using?

Thanks,
Mohammed

**Comment by ymohdriz** [comment]
Hi @preithig,

This is a duplicate of #732 and fix will be available in the next release.
You can close this issue.

Thanks,
Mohammed

**Comment by preithig** [comment]
Thanks @ymohdriz . I will close this issue
