### ISSUE TITLE
Plans for a 2.0.2 release?

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-parser#780]
Are there any roadmap/due date/plans for a `2.0.2` release?

I think all downstream projects could benefit from a release that includes all the fixes that were made to the parser and to the v2-to-v3 converter.

Yesterday I had a discussion https://github.com/quen2404/openapi-diff/issues/53#issuecomment-407803871 about an issue that is already fixed but not released yet. => [quen2404/openapi-diff](https://github.com/quen2404/openapi-diff/) project.

Of course the [OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator) is also interested.

And probably other downstream project that I do not know and do not follow.

---

I think it would be great to merge #775 and then to do a release.

If I can help with something, please let me know.

---

For me it would be great to have it this week or at the beginning of next week.

Do you think it is possible?

**Comment by jeff9finger** [comment]
Agreed. This issue is preventing migration to Open API v3. #746 in particular is the fox that I require in the downstream projects.

**Comment by jeff9finger** [comment]
It looked like it was merged, but not included in the release. But it looks like it is now in the release. Sorry for the confusion.

**Comment by jmini** [comment]
Swagger-Parser `2.0.2` is released: https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.2

**Comment by jmini** [comment]
FYI, I got a big regression when using `2.0.2`: https://github.com/swagger-api/swagger-parser/issues/797
