### ISSUE TITLE
Composed models in the properties of a parameter

### ISSUE THREAD

**Issue by dvallejo** [swagger-api/swagger-parser#781]
Hi,

When I have composed models in the properties of a parameter, the field _allOf_ is handled as a _UntypedProperty_ and I lost all the information about the childs.
Here a swagger example with the problem:
```
swagger: '2.0'
info:
  description: 'Good'
  version: '2.0.0'
  title: 'Test'
paths:
  /foo:
    post:
      parameters:
        - name: id
          in: body
          description: Dummy header
          required: false
          schema:
            type: object
            required:
              - id
            properties:
              event:
                allOf:
                  - type: object
                    properties:
                      child1:
                        type: string
                  - type: object
                    properties:
                      child2:
                        type: string
      responses:
        200:
          description: 'OK'

```

**Comment by dvallejo** [comment]
I´ve added a solution here: https://github.com/swagger-api/swagger-parser/pull/782

**Comment by ymohdriz** [comment]
Hi @dvallejo,

If I understood correctly, we have a model as ComposedModel but not as ComposedProperty which is introduced in https://github.com/swagger-api/swagger-core/pull/2622.

Once ComposedProperty model is merged, then we can handle the same way as ComposedModel (allOf case).  Just a thought.

Thanks,
Mohammed

**Comment by dvallejo** [comment]
Hi @ymohdriz .
You are right. I didn't see that PR in the swagger-core. I think that when that PR will be merged, we have solved this issue.
Do you know when will be merged and when will be updated swagger-parser with the new core version?
Thanks!

**Comment by ymohdriz** [comment]
Hi @dvallejo,

I am not sure when it will be merged. I feel it's good to wait for the merge and check whether it's resolved.

Thanks,
Mohammed

**Comment by dvallejo** [comment]
Sure. Totally agree.

**Comment by gracekarina** [comment]
Hi thanks for this PR, I think we do have an issue with the allOf (or any model) not being able to be in any place in the swagger object that has only the property object. But I don't think this is the way to go to solve this issue, We'll discuss with @frantuma and @webron what is the best way to solve this, as we already did a similiar change in the responses object schema in the following PR: swagger-api/swagger-core#2583.

**Comment by frantuma** [comment]
@dvallejo @ymohdriz thanks for your effort! Implemented the core change in swagger-api/swagger-core#2890, please check if you're still experiencing the issue, if not please close ticket and related PR #782

**Comment by gracekarina** [comment]
Hi @dvallejo @ymohdriz please let us know if this issue was fixed by https://github.com/swagger-api/swagger-core/pull/2890.

**Comment by gracekarina** [comment]
Hi, I'm closing this issue, in case the solution is not in  swagger-api/swagger-core#2890 please let us know.
