### ISSUE TITLE
Where are the releases

### ISSUE THREAD

**Issue by SiKing** [swagger-api/swagger-parser#784]
I see that version 2.0.1 was [released](https://github.com/swagger-api/swagger-parser/releases), but [Maven Central](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.swagger%22%20AND%20a%3A%22swagger-parser%22) only has 2.0.0-rc1. Your [instructions](https://github.com/swagger-api/swagger-parser/tree/2.0#adding-to-your-project) for using this is my project do not specify any special repos. So where do I get this?

**Comment by gracekarina** [comment]
Hi @SiKing is this what you need? https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.swagger.parser.v3%22

**Comment by SiKing** [comment]
Yes. I missed the ".v3" in the groupId. :(
Sorry.
