### ISSUE TITLE
Converter to v3: java.lang.NoClassDefFoundError: io/swagger/parser/SwaggerParser

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-parser#797]
When parsing this spec: [v1beta3.json](https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/v1beta3.json). This spec is using an old version: `"swaggerVersion": "1.2"`

With this code:

```java
OpenAPIParser openApiParser = new OpenAPIParser();
ParseOptions options = new ParseOptions();
options.setResolve(true);
options.setFlatten(true);

OpenAPI openAPI = openApiParser.readLocation(inputSpec, null, options).getOpenAPI();
String string = Yaml.mapper().writerWithDefaultPrettyPrinter().writeValueAsString(openAPI);

System.out.println(string);
```

I get following error with version `2.0.2`:

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/swagger/parser/SwaggerParser
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:92)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:19)
	at fr.jmini.openapi.swagger.SwaggerParserMain.main(SwaggerParserMain.java:18)
Caused by: java.lang.ClassNotFoundException: io.swagger.parser.SwaggerParser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

This is a big regression in comparison to `2.0.1`.

---

Maven GAV:

```xml
    <dependency>
      <groupId>io.swagger.parser.v3</groupId>
      <artifactId>swagger-parser</artifactId>
      <version>2.0.2</version>
    </dependency>
```

**Comment by jmini** [comment]
I think the problem is located in version `1.0.36` of `io.swagger:swagger-parser`. If you force maven to use the previous version like this:

```xml
    <dependency>
      <groupId>io.swagger.parser.v3</groupId>
      <artifactId>swagger-parser</artifactId>
      <version>2.0.2</version>
    </dependency>
    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-parser</artifactId>
      <version>1.0.36</version>
    </dependency>
```

You do not have the problem I have described in this issue.

---

FYI: 
I do not have the problem with the custom release made from the `2.0` branch (see release notes: [2.0.2-OpenAPITools.org-1](https://github.com/OpenAPITools/swagger-parser/releases/tag/v2.0.2-OpenAPITools.org-1)):

```xml
    <dependency>
      <groupId>org.openapitools.swagger.parser</groupId>
      <artifactId>swagger-parser</artifactId>
      <version>2.0.2-OpenAPITools.org-1</version>
    </dependency>
```

Until this issue is solved, I have no choice other than to stick to this custom version instead of the official one.

**Comment by frantuma** [comment]
This doesn't seem to be reproducible, e.g. in [this gist](https://gist.github.com/frantuma/7165404463a398e1c2f3ecccc7399a61); I would suspect some deps issue in your project possibly, can you check and share dep tree?

**Comment by jmini** [comment]
Thank you for your feedback, after doing a replay of your gist, I have spotted:

```
[ERROR] error reading /_____/.m2/repository/io/swagger/swagger-parser/1.0.37/swagger-parser-1.0.37.jar; invalid LOC header (bad signature)
```

I did a new download of the lib, and now it works...

**Comment by jmini** [comment]
The real problem we have with `2.0.2` is https://github.com/swagger-api/swagger-parser/issues/799
Until it is solved, I have no choice other than to stick to this custom version instead of the official one.

**Comment by lkgamor** [comment]
> I think the problem is located in version `1.0.36` of `io.swagger:swagger-parser`. If you force maven to use the previous version like this:
> 
> ```
>     <dependency>
>       <groupId>io.swagger.parser.v3</groupId>
>       <artifactId>swagger-parser</artifactId>
>       <version>2.0.2</version>
>     </dependency>
>     <dependency>
>       <groupId>io.swagger</groupId>
>       <artifactId>swagger-parser</artifactId>
>       <version>1.0.36</version>
>     </dependency>
> ```
> 
> You do not have the problem I have described in this issue.
> 
> FYI: I do not have the problem with the custom release made from the `2.0` branch (see release notes: [2.0.2-OpenAPITools.org-1](https://github.com/OpenAPITools/swagger-parser/releases/tag/v2.0.2-OpenAPITools.org-1)):
> 
> ```
>     <dependency>
>       <groupId>org.openapitools.swagger.parser</groupId>
>       <artifactId>swagger-parser</artifactId>
>       <version>2.0.2-OpenAPITools.org-1</version>
>     </dependency>
> ```
> 
> Until this issue is solved, I have no choice other than to stick to this custom version instead of the official one.

This worked for me. Thanks @jmini 
 

```
   <dependency>
      <groupId>org.openapitools.swagger.parser</groupId>
      <artifactId>swagger-parser</artifactId>
      <version>2.0.2-OpenAPITools.org-1</version>
    </dependency>
```
