### ISSUE TITLE
SwaggerLegacyConverter does not convert Operation's AuthorizationScope to SecurityRequirement

### ISSUE THREAD

**Issue by michaelkwan** [swagger-api/swagger-parser#8]
Using the latest snapshot, load the petstore api-doc using the SwaggerLegacyConverter.

Inspect the Swagger object produced, the "/pet" path's post operation did not have any security requirement Operation.getSecurity() == null (but it's defined in AuthorizationScope for the 1.2 object)

**Comment by fehguy** [comment]
Thanks, fixed in https://github.com/swagger-api/swagger-parser/commit/93c478547f93a0684716738c5d7771182b00f251#diff-e280195c2ed7ce7e15912f4990b54e5aR343

**Comment by fehguy** [comment]
Tests added here: https://github.com/swagger-api/swagger-parser/commit/93c478547f93a0684716738c5d7771182b00f251#diff-401a5582dc3faec8e415f69973e1464bR68
