### ISSUE TITLE
ResourceListingParser#read *always* returns null

### ISSUE THREAD

**Issue by kevinmeredith** [swagger-api/swagger-parser#80]
https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-compat-spec-parser/src/main/java/io/swagger/models/reader/ResourceListingParser.java#L20-L92

`returns null` with many lines of code commented out.

Why now throw an `UnsupportedOperationException` instead?

**Caveat** - I've never looked at this code before today. So I don't know if returning **null** is consistent.

**Comment by fehguy** [comment]
Currently returning null tells the processor chain to go to next. Not pretty but expected.
