### ISSUE TITLE
Handle default type according to schema type. OAS 3

### ISSUE THREAD

**Issue by gracekarina** [swagger-api/swagger-parser#817]
```default - The default value represents what would be assumed by the consumer of the input as the value of the schema if one is not provided. Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object defined at the same level. For example, if type is string, then default can be "foo" but cannot be 1.```
related #814

**Comment by r-sreesaran** [comment]
@gracekarina  if the wrong value is defined for default then we have log the error and proceed processing. It this the expected behavior here ?.

**Comment by spacether** [comment]
Why not raise a validation error instead of continuing?

**Comment by gracekarina** [comment]
Hi, the scope of the issue changed, the validation of this new scope made in another PR. Thanks @jason-cohen for reporting this and sorry for the long reply. I will close this because is no longer an issue.
