### ISSUE TITLE
Availability of Swagger Parser v2.0.2 in Maven Central

### ISSUE THREAD

**Issue by pubudu538** [swagger-api/swagger-parser#825]
Hi,

I could not find the Swagger Parser v2.0.2 in Maven Central and I could find only upto v2.0.0 rc1 [1]. How can I get the latest release?

[1] - https://mvnrepository.com/artifact/io.swagger/swagger-parser

Thank you!
Pubudu.

**Comment by frantuma** [comment]
it's her (changed groupId) https://mvnrepository.com/artifact/io.swagger.parser.v3/swagger-parser

**Comment by pubudu538** [comment]
Thank you for the information.
