### ISSUE TITLE
SwaggerParser#read Successfully Parses Swagger 1.2 Doc

### ISSUE THREAD

**Issue by kevinmeredith** [swagger-api/swagger-parser#83]
The `io.swagger.parser.SwaggerParser` successfully reads the following swagger 1.2 doc:

swagger [doc](http://petstore.swagger.io/api/api-docs)

Note that calling `Swagger#getPaths` returns a list of size 13. 

### code

```
scala> new SwaggerParser().read("http://petstore.swagger.io/api/api-docs")
reading from http://petstore.swagger.io/api/api-docs
reading from http://petstore.swagger.io/api/api-docs
res48: io.swagger.models.Swagger = io.swagger.models.Swagger@8178b58

scala> res48.getPaths.size
res49: Int = 13
```

For what I'm trying to do (using your OSS library - thank you) is return a size of 3 (for each parent path) and then create operations for each child path.

Is this possible with your library?

Thank you,
Kevin

**Comment by Helmsdown** [comment]
@kevinmeredith The SwaggerParser converts 1.2 specs into the Swagger 2.0 models object hierarchy (i.e. the classes in the swagger-models jar). Per the swagger 2.0 spec a path is defined as a unique (possibly parameterized) string. If you go through the sub URLs of /pets, /users, and /store and count the unique paths you will come up with 13. "Operations" are meant to represent a given HTTP method associated with a given path. So if you were to arbitrarily  condense to 3 path objects, you would lose information.

For example:

1. /pet/{petId} has a GET operation
2. /pet/findByTag has a GET operation

So if you only had a /pet path object, you could only associate one GET operation with it and thus would lose information. 

Additionally, you would have lost additional path information (e.g. the parts of the path that come after the root /pet). 

Does this make sense?

**Comment by kevinmeredith** [comment]
Yes, thank you.
