### ISSUE TITLE
Need to get definition type

### ISSUE THREAD

**Issue by amargreen** [swagger-api/swagger-parser#843]
I am parsing a yaml file and trying to get definition type, but dont see a method retrieve the field:
Map<String, Model> definitions = swagger.getDefinitions();
I thought Model object has a method to return 'type' of the definition, but dont see a method.
Is there a way to retrieve this?

thanks,
amar

**Comment by gracekarina** [comment]
Hi, If I understand correctly you could use `instance of` in a conditional, once you know which instance I believe there is a type. https://github.com/swagger-api/swagger-core/blob/1.5/modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java

**Comment by amargreen** [comment]
Thanks Grace! with the usage of ModelImpl, I can get type info
