### ISSUE TITLE
Examples from external files do not get reference in the Swagger POJO

### ISSUE THREAD

**Issue by JehandadK** [swagger-api/swagger-parser#853]
If an external file reference an example as internal ref, it will not be resolved.

```yaml

application/json:
  schema:
      ...
  examples:
      testExample:
        $ref: '#/components/examples/testExample'

components:
  examples:
    testExample:
       value:
          testKey: value
```

In the case the above data is in some referenced file the testExample will not be available in final openapi.getComponents() Collection.

**Comment by gracekarina** [comment]
closed by #854
