### ISSUE TITLE
external $ref not working

### ISSUE THREAD

**Issue by mvpratap** [swagger-api/swagger-parser#861]
Hi i am new to swagger parser,i tried to create a single yaml file using swagger parser ,but its not working, in which base yaml file is having refs to other yaml.

is there any mistake i did, is there any other way to resolve all the external refs and make an single yaml file.

following are the code snippet i used

String filelocation = "base.yaml";
SwaggerDeserializationResult result = new SwaggerParser().readWithInfo(filelocation, null, true);
 Swagger swagger = result.getSwagger();
System.out.println(Yaml.pretty().writeValueAsString(swagger));

attached expected output and actual output and yaml files used.
[swaggerparser.txt](https://github.com/swagger-api/swagger-parser/files/2446509/swaggerparser.txt)

**Comment by gracekarina** [comment]
Hi @mvpratap  thanks for reporting, is faster for us to find a solution, when a PR with a failing test is made. please send us a PR.

**Comment by r-sreesaran** [comment]
@mvpratap  your are currently using Swagger parser to parse open api. You have to use OpenAPI parser. 
  Kindly find the code for Open API parser
        String filelocation = "base.yaml";
        ParseOptions options = new ParseOptions();
        options.setResolve(true);
        SwaggerParseResult result = new OpenAPIParser().readLocation(filelocation, null,options);
        assertNotNull(result.getOpenAPI());

**Comment by gracekarina** [comment]
@mvpratap please let us know how it goes!
