### ISSUE TITLE
Swagger Parser error when reading local yaml files

### ISSUE THREAD

**Issue by Tasneem1434** [swagger-api/swagger-parser#87]
Hi. 

I have used a similar example in terms of hierarchy and $ref definitions as
https://github.com/mohsen1/multi-file-swagger-example

I am new to this, so I am sure I am doing something wrong...Please advise....

When trying to read the yaml file, I am getting this error. Seems like it does not like the $ref definition on the paths/index.yaml file. 
Here is the error:
Can not instantiate value of type [simple type, class com.wordnik.swagger.models.Path] from String value ('C:/IDEA/***/***/***/yaml//paths/index.yaml'); no single-String constructor/factory method
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.wordnik.swagger.models.Swagger["paths"])

Thank you

**Comment by webron** [comment]
Looks like you're using an old version of the parser.

**Comment by Tasneemb** [comment]
Hi. Thank you. I have updated the version to use the 1.0.11-SNAPSHOT....but still getting the error
Can not instantiate value of type [simple type, class io.swagger.models.Path] from String value ('./paths/index.yaml'); no single-String constructor/factory method
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.swagger.models.Swagger["paths"]->java.util.LinkedHashMap["$ref"])

**Comment by webron** [comment]
Can you share your definition(s)?

**Comment by Tasneemb** [comment]
this is the index.yaml
.....
paths:
  $ref: ./paths/index.yaml

this is in paths/index.yaml
/cars/{carId}/{modelId}:
  $ref: ./cars.yaml

Also, I have tested this using the exact code from resolve.js within node.js and it works fine...
https://github.com/mohsen1/multi-file-swagger-example

**Comment by webron** [comment]
Have you tested the parser with @mohsen1's example directly?

**Comment by Tasneemb** [comment]
Just tried now.
This is my java code
Swagger swagger = new SwaggerParser().read("C:/Users/***/Downloads/MultiFilesBkup/index.yaml");

Error I am getting with above
reading from C:/Users/***/Downloads/MultiFilesBkup/index.yaml
Can not instantiate value of type [simple type, class io.swagger.models.Path] from String value ('./paths/index.yaml'); no single-String constructor/factory method
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.swagger.models.Swagger["paths"]->java.util.LinkedHashMap["$ref"])
reading from C:/Users/***/Downloads/MultiFilesBkup/index.yaml
Can not instantiate value of type [simple type, class io.swagger.models.Path] from String value ('./paths/index.yaml'); no single-String constructor/factory method
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.swagger.models.Swagger["paths"]->java.util.LinkedHashMap["$ref"])

**Comment by Tasneemb** [comment]
Hi. Any solutions to this please?

**Comment by Helmsdown** [comment]
I happened to come across this issue, please pardon me butting in.

Here is the root yaml file:
```yaml
swagger: '2.0'
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
```

I don't think this is valid swagger 2.0 yaml. My reading of the swagger spec says that you can reference individual paths via a $ref but it does not say you can put multiple paths into a single yaml file and reference that file via a single ref.

For example you could do the following
```yaml
swagger: '2.0'
paths:
  /foo:
   $ref: ./paths/foo.yaml
 /bar:
   $ref: ./paths/bar.yaml
definitions:
 Foo:
   $ref: ./models/foo.yaml
 Bar:
  $ref: ./models/bar.yaml
```

@webron Am I reading the spec correctly?

**Comment by Tasneem1434** [comment]
Hi

Apologies, for the late reply.

I get what you are saying, but the above was based on a swagger example. If you look at https://github.com/mohsen1/multi-file-swagger-example/blob/master/index.yaml
This is the root yaml file
swagger: '2.0'
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml

**Comment by fehguy** [comment]
Hi, unfortunately that post isn't accurate for what is allowed inside swagger.  The JSON pointers are not legal arbitrarily, even if they technically could be.  So the source of truth should be the [swagger-spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md), not the general internet.

**Comment by Tasneemb** [comment]
Hi. Thank you very much for your reply. Ok, So like user Helmsdown says, I should basically take all the paths that I have in /paths/index.yaml and put them in the root yaml?

**Comment by fehguy** [comment]
Yes--best if you use the validator to ensure the spec is valid.  You can do so like such:

```
curl -X POST -H "application/json" -d @petstore.json http://online.swagger.io/validator/debug
```

Then you can validate your JSON.  For example this:

```json
{
  "swagger": "2.0",
  "info": {
    "$ref": "foo/bar"
  }
```

Will cause a parse error
