### ISSUE TITLE
Parameter Internal Ref Not Resolved

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-parser#877]
Hi team,

When OpenApiV3Parser parses a operation with a parameter ref, the ref isn't being resolved for the parameter.

Attached the spec
[issue_877.txt](https://github.com/swagger-api/swagger-parser/files/2473821/issue_877.txt)

Thanks,
Mohammed

**Comment by gracekarina** [comment]
Fixed by #878
