### ISSUE TITLE
$ref in swagger-editor running locally 

### ISSUE THREAD

**Issue by Tasneemb** [swagger-api/swagger-parser#88]
Hi 

I am running a local instance of swagger-editor. I had a single yaml file which had no errors in it. I then decided to split the files for each of the paths defined in the single yaml file. Since splitting , I am getting this error in my validator window...

Additional properties not allowed: $ref
Relative paths to the individual endpoints. They must be relative to the 'basePath'.
Jump to line 21
Details
Object
code: "OBJECT_ADDITIONAL_PROPERTIES"
message: "Additional properties not allowed: $ref"
path: Array [1]
description: "Relative paths to the individual endpoints. They must be relative to the 'basePath'."
level: 900

this is the part which is in error
paths:
  $ref: '#/paths/index.yaml'

Please advise....

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-editor#639
