### ISSUE TITLE
Swagger Parser fails to remove duplicate tags

### ISSUE THREAD

**Issue by r-sreesaran** [swagger-api/swagger-parser#887]
As per open API Specification, there cannot be duplicate tags present in open API document. 
"
A list of tags used by the specification with additional metadata. The order of the tags can be used to reflect on their order by the parsing tools. Not all tags that are used by the Operation Object must be declared. The tags that are not declared MAY be organized randomly or based on the tools' logic. **Each tag name in the list MUST be unique**
"
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-requirement-object

Even in the swagger editor, while displaying duplicate tags are getting removed.

**Comment by r-sreesaran** [comment]
I have fixed the problem and raised the PR. Kindly do accept the PR if this is an issue.

**Comment by gracekarina** [comment]
Hi, @r-sreesaran I'm not sure I understand what you mean by this issue.  
The tags located at the root of the openApi Object are the one that should be unique (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#openapi-object)
As for the Operation object: there is nothing that specifies that tags at this level should be unique ( https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operation-object)
So according to the spec I think  parser should warn when it finds a duplicated tag only at the root of openApi. 
The editor removes the tags but only in a display level. 

Thanks for the PR #888  I see the test is validating duplicating tags at operation level, so the test should be changed to validate tags at root level, and add a warn to the messages map in parser. I can't merge the PR as is, please modify it so I can merge. Have a great weekend, thanks for contributing!

**Comment by r-sreesaran** [comment]
@gracekarina  yes your right currently, it is not getting logged. I will make the necessary changes and raise a PR.

**Comment by gracekarina** [comment]
Fixed y #888
