### ISSUE TITLE
Swagger parser failed to parse the input swagger url with space

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-parser#898]
Hi team,

Swagger parser failed to parse this input swagger url http://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/export?DocumentFormat=Swagger&ApiName=Face API - V1.0

Reason:
Space is not encoded to %20 in code

Thanks,
Mohammed Rizwan

**Comment by gracekarina** [comment]
Fixed by #900  #899
