### ISSUE TITLE
Headers Internal Ref Not Resolved

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-parser#918]
Hi team,

When OpenApiV3Parser parses a operation with a header ref, the ref isn't being resolved for the header.

Attached the spec
[issue_915.txt](https://github.com/swagger-api/swagger-parser/files/2564872/issue_915.txt)

Thanks,
Mohammed

**Comment by gracekarina** [comment]
Hi @ymohdriz does this solve only internal Refs? or also relative refs?

**Comment by ymohdriz** [comment]
Hi @gracekarina,

This issue is related to internal refs when resolverFully() is used.
External refs are already handled correctly when resolve is set to true in options.

Thanks,
Mohammed

**Comment by gracekarina** [comment]
fixed by #919
