### ISSUE TITLE
Making Deep Copy of `io.swagger.models.Swagger`

### ISSUE THREAD

**Issue by kevinmeredith** [swagger-api/swagger-parser#92]
I have a need to copy an `io.swagger.models.Swagger` object.

Rather than write this method in my code (which uses this `swagger-parser` library), it seems more appropriate for me to make a PR.

Would you accept a PR to make a deep copy of the `Swagger` object?

**Comment by fehguy** [comment]
Sure

**Comment by mikeholler** [comment]
Any updates on this?

**Comment by kevinmeredith** [comment]
I won't be submitting a PR.
