### ISSUE TITLE
Open API parser is not validating the invalid references

### ISSUE THREAD

**Issue by saileshsingh** [swagger-api/swagger-parser#934]
Hi,

First of all, thanks a lot for the excellent product.

PFB,
responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"

As mentioned above, If my Open API file doesn't have any schema with name ApiResponse under components/schemas then Open API parser should report the missing references and this case is applicable for all other component types as well.

Regards,
Sailesh V

**Comment by pureJEagles** [comment]
Actually, it might be a duplicate of #684 but the fix doesn't seem to be on master or in the 3.3.3 release.

**Comment by gracekarina** [comment]
Closed by #935
