### ISSUE TITLE
Inconsistent handling of resolveFully and flatten options from ParseOptions

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-parser#954]
Hi team,

Is options resolveFully and flatten from ParseOptions, mutually-exclusive? 
It looks as mutually-exclusive from readLocation() and it's not in readContents(). 

@gracekarina
Based on your answer, I will raise a PR.

Thanks,
Mohammed

**Comment by gracekarina** [comment]
Hi, yes they are mutually-exclusive. thanks

**Comment by ymohdriz** [comment]
> Hi, yes they are mutually-exclusive. thanks

Thanks for the quick reply @gracekarina

**Comment by gracekarina** [comment]
closed by #955
