### ISSUE TITLE
Parser Fails to log a warning when parameters are duplicated

### ISSUE THREAD

**Issue by r-sreesaran** [swagger-api/swagger-parser#959]
According to the specification. 
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#path-item-object

The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location. The list can use the Reference Object to link to parameters that are defined at the OpenAPI Object's components/parameters.

But when a parameter is duplicated, the parser fails to throw a warning message.

**Comment by gracekarina** [comment]
closed by #960
