### ISSUE TITLE
Unable to determine correct format of IntegerSchema

### ISSUE THREAD

**Issue by sadovnyc** [swagger-api/swagger-parser#973]
If integer field does not have format definition or have a custom format like 'uint8'/'int16', parser returns as it has format 'int32'. OpenApi specification does not have precision about default format value for integer types, so if format property is not defined, IntegerSchema should return 'null'.

**Comment by gracekarina** [comment]
@sadovnyc thanks for reporting this, We've just merged a PR with a fix for it please. Let us Know if this keep happening.
