### ISSUE TITLE
"aggressive" YAML anchors causing parser to hang

### ISSUE THREAD

**Issue by frantuma** [swagger-api/swagger-parser#998]
when passing a "YAML Bomb"-like content to SwaggerParser, the call hangs with high CPU usage.

e.g.

```
Swagger result = new SwaggerParser().read("test.yaml");
```

an example is provided [here](https://gist.githubusercontent.com/frantuma/731d477ea8d6942e17b32da8bfb355e7/raw/b2bfae681e912e80aefc13a3afc5f1783a448325/malicious.yaml)

related to [this snakeyaml issue](https://bitbucket.org/asomov/snakeyaml/issues/432/aggressive-yaml-anchors-causing)

**Comment by gracekarina** [comment]
fixed by #999
